### ISSUE TITLE
Поиск товара по цене

### ISSUE THREAD

**Issue by gsbelarus** [gsbelarus/check-and-cash#1]
Поиск товара по цене.

**Comment by hirurg-lybitel** [comment]
Ей богу, дикость какая-та.

**Comment by stasgm** [comment]
Название не помню, но цену помню!

**Comment by alexandra-gsoftware** [comment]
Потом выбираем первое попавшееся и возмущаемся, что гедымин списал не то

**Comment by gsbelarus** [comment]
Есть в других системах такая функция. Почему дикость? Ввел цену -- показывает товарные позиции подходящие. Выбрал одну из них -- добавил в чек.

**Comment by MAliaksandr** [comment]
Возможно, это удобно где ассортимент невелик, а если в розничной точке продуктового введешь 5500 и получи полсправочника-)
