### ISSUE TITLE
POSitive Check. После оплаты сумма в чеке не совпадает с суммой в отчетах клиента.Ошибка носит периодический характер.

### ISSUE THREAD

**Issue by supportkkc** [gsbelarus/check-and-cash#107]
Скрины и  бэкап переслал на почту Стасу.

**Comment by stasgm** [comment]
Судя по журналу, происходит 2 нажатия на кнопку "Оплатить". Возможно, официант успевает очень быстро нажимать (постукивать карточкой) на кнопку. 

Для решения вопроса создал новую задачу https://github.com/gsbelarus/check-and-cash/issues/109
