### ISSUE TITLE
Сделать проверку связи с ФР и вызывать её при выполнении операций связанных с обращением к ФР

### ISSUE THREAD

**Issue by stasgm** [gsbelarus/check-and-cash#108]
Сделать такой метод в классе ФР или переделать init.
Обрабатывать кнопки "пречек", "оплата", "ok"

**Comment by hirurg-lybitel** [comment]
а почему Init не подходит?

**Comment by stasgm** [comment]
Оптимизировать надо init и тогда подойдёт

**Comment by hirurg-lybitel** [comment]
Оптимизировал?

**Comment by hirurg-lybitel** [comment]
Бумаги в отдел не приходили. 
Наверное, неправильно бумаги оформил
