### ISSUE TITLE
Cash

### ISSUE THREAD

**Issue by supportkkc** [gsbelarus/check-and-cash#113]
Уже не однократно появляется проблема со скидками. Она решается, но через некоторое время в новых версиях снова появляется. Когда используют Доп скидку, входят в оплату сумма отличается с чеком продажи, разница в одну копейку.

**Comment by hirurg-lybitel** [comment]
Проблема конкретно с данным типом скидок появилась впервые.

Обновите ПИ **GS.PositiveCash.Рабочее место кассира место кассира**
