### ISSUE TITLE
Слетают скидки

### ISSUE THREAD

**Issue by supportkkc** [gsbelarus/check-and-cash#115]
positive check + Бэк Гедымин. При обновлении прайса, или загрузке нового, слетают ранее установленные скидки на группы и блюда (питание сотрудников).

**Comment by stasgm** [comment]
Нужен конкретный пример: порядок действий и база.

**Comment by hirurg-lybitel** [comment]
Конкретно пример: 
На бэке добавили в меню одну позицию. На фронте через форму загрузки меню выбрали обновлённое меню, нажам на чекбокс. Соответсвенно чекбокс проставился и у всех позиций этого меню. Загрузили меню. Итог - все скидки, установленные для позиций этого меню, слетели.

**Comment by stasgm** [comment]
Проверил. Работает на эталоне

**Comment by hirurg-lybitel** [comment]
Проверил. Скидки слетают.

Уточнение: скидки устанавливаются на фронте в документе меню через кнопку "Назначить скидку"
