### ISSUE TITLE
ALIAS

### ISSUE THREAD

**Issue by supportkkc** [gsbelarus/check-and-cash#117]
В КС товары загрузились но в Кассу не передаются.Во фронт части positive cash поле ALIAS ограничено 16тью символами, а у клиента 18-20(модель/тип/код.цвет). Нужно увеличить это поле.

**Comment by hirurg-lybitel** [comment]
https://github.com/GoldenSoftwareLtd/gedemin-apps/issues/407

**Comment by stasgm** [comment]
Может быть использовать иное поле для обозначения сложного шифра товара? Или в данном случае сделать признаком или как там в кэше называется характеристика товара

**Comment by MIchaelShoihet** [comment]
Все дело в том, что может быть множество процедур в которых задействован шифр, и они начнут ругаться...

**Comment by hirurg-lybitel** [comment]
@MIchaelShoihet  например, на что?

**Comment by hirurg-lybitel** [comment]
@stasgm надо идти попути наименьшего напряжения пользователя - людям удобней просто видеть большой артикул в одном поле, а не разбитый по признакам.

**Comment by gsbelarus** [comment]
@hirurg-lybitel "Arithmetic exception, numeric overflow, or string truncation" не слышал про такую ошибку?
```

declare variable n varchar(20);
...
select first 1 name from gd_contact where char_length(name) > 20 into :n;
...
```

**Comment by gsbelarus** [comment]
вылезти может где угодно. от пользовательского интерфейса, до богом забытого триггера. а еще есть какие-нибудь процедуры экспорта/импорта из внешних файлов.

**Comment by hirurg-lybitel** [comment]
Надо сделать отдельное поле, независмое от стандартного, и работать только с ним.

**Comment by hirurg-lybitel** [comment]
Теперь при старте программы будет изменятся длина необходимых полей
