### ISSUE TITLE
Скидка разовая на купон

### ISSUE THREAD

**Issue by gsbelarus** [gsbelarus/check-and-cash#12]
Разовые скидки (при покупки на сумму …, печатается купон  с указанием % скидки на следующий чек).

Печать купонов (нефискальный текстовый документ): разовые скидки (при покупки на сумму …, печатается купон  с указанием % скидки на следующий чек).

**Comment by hirurg-lybitel** [comment]
Никто с такими пожеланиями не обращался, так что не будем придумывать то, что не востребовано
