### ISSUE TITLE
При нажатии на кнопку "Пречек" выдаёт сообщение что отчёт не найден.

### ISSUE THREAD

**Issue by supportkkc** [gsbelarus/check-and-cash#120]
В эталонной версии Check нет форм для печати "Пречека", "Счет" печатается.

**Comment by supportkkc** [comment]
на Сервис-документах снова не правильно режет бумагу. Такое было, отрезает чек, пропуск снова отрезает чек

**Comment by stasgm** [comment]
Основной вопрос сделан.
По второму я говорил, что надо отключать или в принтере или в драйвере
