### ISSUE TITLE
Аннулирование чека

### ISSUE THREAD

**Issue by hirurg-lybitel** [gsbelarus/check-and-cash#121]
На данный момент чек аннулирования не влияет на реализацию на бэке, а должен.

**Comment by supportkkc** [comment]
+ еще проверить работу с Банковским терминалом, при аннулировании. Это очень важно!

**Comment by hirurg-lybitel** [comment]
@supportkkc для этого терминал нужен

**Comment by supportkkc** [comment]
Он на офисе есть. Подключу скину Вам доступ.

**Comment by startkkc** [comment]
Напоминаю, что задача ещё не решена.

**Comment by startkkc** [comment]
Можете ускорить решение. С каждым днем увеличивается число клиентов, которых придется заново обновлять.

**Comment by hirurg-lybitel** [comment]
Как будет возможность, к задаче кто-нибудь приступит

**Comment by hirurg-lybitel** [comment]
неконтролируемый доступ  к терминалу уже настроили?

**Comment by startkkc** [comment]
Удаленка есть.
Аннулирование все еще не влияет на реализацию, а очень хотелось бы. Чем дальше тем больше людей надо будет заново обновлять. При аннулировании питания сотрудника в кредит, в Check было замечено, что в нижней части чека печатается не его данные, а берутся из предыдущего чека.

**Comment by startkkc** [comment]
Есть информация по данному вопросу?

**Comment by hirurg-lybitel** [comment]
нет

**Comment by startkkc** [comment]
Когда будет?

**Comment by hirurg-lybitel** [comment]
Не раньше, чем будет доступ к банковскому терминалу

**Comment by startkkc** [comment]
Хотя бы влияние на реализацию можно сделать? Не руками же удалять.

**Comment by hirurg-lybitel** [comment]
@yoannawx каким документом на бэке провести аннулирование чека можно?

**Comment by hirurg-lybitel** [comment]
@yoannawx приём!

**Comment by yoannawx** [comment]
проверять только анулированные чеки, у которых установлен флаг передано - загружать их в реализацию так же, как и возвраты

**Comment by hirurg-lybitel** [comment]
@startkkc что там с доступом к БТ ?

**Comment by startkkc** [comment]
Он всегда есть, связывайтесь подключим

**Comment by startkkc** [comment]
@hirurg-lybitel При аннулировании чека в Cash, в чеках появляется чек с "типом чека" Аннулирование, и номер связанного чека, по которому проходит аннулирование. В выгрузке файла реализации DBF, ничего нет про этот чек аннулирования. Только продажи.

**Comment by hirurg-lybitel** [comment]
@startkkc  

> При аннулировании чека в Cash, в чеках появляется чек с "типом чека" Аннулирование, и номер связанного чека, по которому проходит аннулирование. В выгрузке файла реализации DBF, ничего нет про этот чек аннулирования. Только продажи.

Смотри #192
