### ISSUE TITLE
Импорт сотрудников и лимитов через xml

### ISSUE THREAD

**Issue by supportkkc** [gsbelarus/check-and-cash#122]
Необходимо для ККС сделать импорт сотрудников и лимитов через xml файл, (positive check). С каким сотрудником связаться для инициализации доработки. Предварительно @stasgm файл смотрел оценил в 3ч.

**Comment by alexandra-gsoftware** [comment]
Пишите мне, наверно.

**Comment by supportkkc** [comment]
Спасибо, все работает.
