### ISSUE TITLE
Продается один товар, а списывается другой.

### ISSUE THREAD

**Issue by supportkkc** [gsbelarus/check-and-cash#123]
Positive cash, разные товары, но продается один, а списывается другой.

**Comment by hirurg-lybitel** [comment]
Хоть немного технической информации хотелось бы получить.

**Comment by supportkkc** [comment]
Разбирался Ваш коллега, пришел к выводу, что т.к. у товара нет штрих кода, то он списывает ближайший.

**Comment by hirurg-lybitel** [comment]
так а товар как пробивается? 
через окно поиска товаров?
