### ISSUE TITLE
Ошибка во время работы cash

### ISSUE THREAD

**Issue by supportkkc** [gsbelarus/check-and-cash#125]
Positiv cash. Во время работы появляется ошибка. Предположительно проблема в работе с дисплеем покупателя, т.к. без него ошибка не возникает. Еще одно отличие, на объекте новые весы cas ER, которые стыковались совсем недавно. Дисплей покупателя spark pd2001 (USB), стоит на многих объектах. 
![image-0-02-05-5838b98b0914e5f179317eb8a15b0dc8a2d97bb50479a274e0e10fa61b8ce7b2-v 1](https://user-images.githubusercontent.com/20512230/31223423-f853d1fe-a9d2-11e7-9b64-22587180ca9a.jpg)
![image-0-02-05-cfb165c28a9403a3688a412898b776b753940a0b6b6c33f55ed4e7661fe4b620-v](https://user-images.githubusercontent.com/20512230/31724101-7ebd0872-b429-11e7-889d-8ad1b394282f.jpg)

**Comment by supportkkc** [comment]
Как будут предложения по устранению ошибки?

**Comment by hirurg-lybitel** [comment]
В какой момент появляется ошибка? 
При чтении массы с весов?

**Comment by supportkkc** [comment]
По разному, говорят и после закрытия чека, и во время работы.

**Comment by hirurg-lybitel** [comment]
а что в этот момент на дисплее покупателя?

**Comment by supportkkc** [comment]
точно не могу сказать, говорят зависает

**Comment by hirurg-lybitel** [comment]
Ну тогда вылавливать конкретный случай или ставить весь этот набор оборудования и тестировать.
