### ISSUE TITLE
Выгрузка в 1С

### ISSUE THREAD

**Issue by supportkkc** [gsbelarus/check-and-cash#126]
При формировании файла выгрузки для 1С, возникает ошибка скрипт функции.
[CASHSERVER20171006.zip](https://github.com/gsbelarus/check-and-cash/files/1390143/CASHSERVER20171006.zip)

**Comment by MAliaksandr** [comment]
Уточните. Октябрь вроде бы выгружается без проблем. "Экспорт в DBF" ? или что-то еще?

**Comment by supportkkc** [comment]
когда выбирают период 1.09 по 30.09 не сходятся данные за 29 число

**Comment by supportkkc** [comment]
за 29 число работало 2 кассы (885 и 821) данные по Z-отчётам: 885 - 36988,03р. 821 - 45300,60р.
разница с ПО 3672,33р.

**Comment by stasgm** [comment]
@supportkkc клиентские базы сюда не кидаем. Это открытый репозиторий

**Comment by stasgm** [comment]
@supportkkc На почту выслал. Проверьте и закройте тему если работает

**Comment by supportkkc** [comment]
все ок, спасибо
