### ISSUE TITLE
Не проходит регистрация ПО

### ISSUE THREAD

**Issue by supportkkc** [gsbelarus/check-and-cash#127]
НЕ регистрируется gedemin.exe на серверных машинах. Уже у двух клиентов такая проблема.
![imag0270](https://user-images.githubusercontent.com/20512230/31934678-762d3e08-b8b5-11e7-8e74-b6dd98ec8122.jpg)

**Comment by supportkkc** [comment]
Можно проверять, для перед этим надо сделать?

**Comment by hirurg-lybitel** [comment]
Поскольку у всех остальных всё хорошо, то думаю, без конкретной машины вам не помогут.

**Comment by gsbelarus** [comment]
Надо глянуть есть ли там права на запись в реестр и не используется ли roaming profile, когда реестр при логине в операционную систему переписывается с сервера. если последнее верно, то как идет вход в компьютер? через учетную запись домена? если да, то не используется ли одна запись на несколько компов?
