### ISSUE TITLE
Проблемы после обновления.

### ISSUE THREAD

**Issue by supportkkc** [gsbelarus/check-and-cash#128]
После обновления для работы с СКНО появились следующие проблемы.
1) При импорте товара в кассовый сервер, в поле Descr - грузятся данные по срокам годности, они не попадают в описание (Справочник ТМЦ) товара. 
2) При печати z-отчета, выходит контрольная лента. Галка печати контрольной ленты - убрана.
3) Раньше у клиента не грузился уникальный код ТМЦ, после обновления уникальный код начал заполняться, и на кассе происходит дублирование товара. Выгрузить остатки нет возможности, надо отключить заполнения уникального кода.

**Comment by supportkkc** [comment]
1. +
2. -
3. +

**Comment by supportkkc** [comment]
2. На офисе контр. лента не снимается, у клиента - выходит. Ручное закрытие дня не помогло.

**Comment by hirurg-lybitel** [comment]
ну если программа таже, то напрашивается вывод: дело в фр.

**Comment by supportkkc** [comment]
сразу в двух ФР?

**Comment by hirurg-lybitel** [comment]
Сказали же
> На офисе контр. лента не снимается

получается программа работает?
