### ISSUE TITLE
Генерация GTIN

### ISSUE THREAD

**Issue by supportkkc** [gsbelarus/check-and-cash#129]
В версии с СКНО, есть скрипт установить генератор GTIN, но нет генерации GTIN на ранее загруженные товары в Справочник ТМЦ. Точно в Positive check, в Cash надо проверить.
Обновить мануал по СКНО с дополнением по GTIN.

**Comment by hirurg-lybitel** [comment]
В Cash достаточно запустить "Внести начальный данные".
В Check что-нибудь придумаем

**Comment by supportkkc** [comment]
По check`у очень надо 2.11.17, т.к. 3-4.11.17 будем обновлять клиента.

**Comment by hirurg-lybitel** [comment]
Ну если срочно, то обновите ПИ **GS.PositiveCheck. Глобальные макросы**

И запустите макрос **Обновить коды GTIN** в **справочнике ТМЦ**

**Comment by supportkkc** [comment]
Спасибо
