### ISSUE TITLE
Оплата накопленными средствами с карточки

### ISSUE THREAD

**Issue by gsbelarus** [gsbelarus/check-and-cash#13]
Накопление бонусов, оплата накопленными бонусами.

**Comment by MAliaksandr** [comment]
**БОНУСЫ** - это прекрасно!
Давайте попробуем определить условия:
1.% для начисления с чека. с позиции чека.
2.МАХ СУММА для начисления с чека. с позиции чека.
(иначе говоря, есть некая сумма, начиная с которой можно начислять бонусы)
3. Период (здесь может быть как время, так и определенные дни недели так и строгий интервал времени - 36часов с момента регистрации чека)
4. Исключения. Группы/товары на которые НЕ/распространяются бонусы
5. Позиция в чеке. Или изощренные условия. (каждая 2 позиция в чеке, при условии что ее стоимость не меньше 20 % от общей суммы чека, накапливает бонус в размере 15% от суммы позиции или чека )
6. Начислять и/или не начислять бонусы от общей стоимости чека или от стоимости чека за минусом стоимости при расчете бонусом.
(Пример:
500 тыс чек
есть 200 тыс бонусов на карте, которые учитываем в расчете
вариант 1 - начисляем процент только с суммы при любом способе оплаты кроме бонусной системы т.е. - 500-200 = 300тыс и из 300тыс начисляем процент бонуса на карту )
вариант 2 - начисляем процент с общей суммы чека вне зависимости от способа расчета.
(т..е бонус от 500тыс)
вариант 3 - привязка к наличным/безнал. расчетам. ограничено только фантазиями
7. Перенос бонусов с карты на карту
7.1 - при утере (привязка к клиенту)
7.2 - какие-то переносы или дополнения. (использования 2 и более карт)

**Comment by hirurg-lybitel** [comment]
https://github.com/gsbelarus/check-and-cash/issues/35
