### ISSUE TITLE
Медленно закрываются чеки Positive Cash

### ISSUE THREAD

**Issue by supportkkc** [gsbelarus/check-and-cash#130]
При закрытии чека следующий чек открывается через 5-7 секунд. Базу cash server и cash отправил на почту Станиславу и Юре

**Comment by supportkkc** [comment]
Есть ли какая-либо информация?

**Comment by supportkkc** [comment]
Что слышно по проблеме?

**Comment by hirurg-lybitel** [comment]
Никаких проблем с базой данных не выявлено.
