### ISSUE TITLE
Остатки из Бэка

### ISSUE THREAD

**Issue by supportkkc** [gsbelarus/check-and-cash#131]
Positive cash. При выгрузке остатков из бэка. Прайс удаляется и загружаются актуальные остатки. При этом, возврат по позиции (по номеру чека), которой уже нет в прайсе, будет не возможен. Программа сообщает, что такого товара нет.

**Comment by hirurg-lybitel** [comment]
Чек возврата никак не связан с прайсом.
Так что базу и описание, пожалуйста.

**Comment by supportkkc** [comment]
Ок, отправил.

**Comment by supportkkc** [comment]
Если делать возврат по чеку, и вводить товар через штрихкод или артикул, тогда пишет что "товар не найден" (видимо тут идет ввод по прайсу), а если через поиск товара, тогда все норм. Если делать просто возврат, не по номеру чека, возврат не сделаешь.
