### ISSUE TITLE
Доработать печатную форму акт реализации (режим кассы, форма менеджера)

### ISSUE THREAD

**Issue by stasgm** [gsbelarus/check-and-cash#132]
1. Сумма должна печататься со скидкой, а сейчас без
2. Формат отображения к-ва установить без отображения нолей

**Comment by yoannawx** [comment]
проверяй https://github.com/GoldenSoftwareLtd/gedemin-apps/commit/e32684cc85ff62c1888a855537e6ff31777c3938

**Comment by hirurg-lybitel** [comment]
@stasgm работает?
