### ISSUE TITLE
Инструкция СКНО (Check и Cash)

### ISSUE THREAD

**Issue by startkkc** [gsbelarus/check-and-cash#133]
Обновить инструкцию по СКНО

**Comment by startkkc** [comment]
В мануале нет информации по счетчику заказа в позитиве чек

**Comment by hirurg-lybitel** [comment]
@startkkc а какая информация нужна?

**Comment by startkkc** [comment]
О том, что если фастфут или столовая, галочку счетчик заказов не ставим. В данном режиме он не будет вести этот счетчик, и ставим галку, если со столиками.
