### ISSUE TITLE
доработка check

### ISSUE THREAD

**Issue by startkkc** [gsbelarus/check-and-cash#136]
Необходимо доработать check со службой ФР. Очень важная доработка.

**Comment by startkkc** [comment]
Напоминаю про задачу

**Comment by hirurg-lybitel** [comment]
Это нужно кому-то конкретно?

**Comment by startkkc** [comment]
Эта функция уже должна быть с августа прошлого года и может понадобится в любой из дней.

**Comment by hirurg-lybitel** [comment]
а у разработчика драйвера случайно нет решения для такого случая?

**Comment by startkkc** [comment]
Нету. Коллеги по платформе делали через службу.

**Comment by stasgm** [comment]
Пока на уровне обсуждения принципа работы службы.

**Comment by hirurg-lybitel** [comment]
Готов тестовый вариант. Кому скинуть для проверки?

**Comment by hirurg-lybitel** [comment]
Сделать возможным корректрировать и закрывать заказ только на том ФР, на котором он был открыт.
