### ISSUE TITLE
Зависание Cash при открытии смены

### ISSUE THREAD

**Issue by supportkkc** [gsbelarus/check-and-cash#138]
При открытии смены кассиром PositiveCash долго входит в систему. Первый чек выходит из ФР для покупателя и ПО зависает на несколько минут "Идет обработка данных", что создает неудобства для очереди, потом все начинает нормально работать. Такое наблюдается последние три дня 28.11-30.11. Ссылки на базы: Ссылка для скачивания файлов:

**Comment by stasgm** [comment]
@supportkkc уже неоднократно уведомляли, чтобы сюда ссылки на базы клиентов не выкладывали. Этот репозиторий открыт для всех пользователей бескрайней сети Интернет.

Сюда добавляйте сообщение, а  базу (или ссылку на базу) высылайте  на почту ответственным лицам.

Конфиденциальность превыше всего!

**Comment by supportkkc** [comment]
Что с вариантами решения проблемы?

**Comment by supportkkc** [comment]
Я так понимаю что пока решения нет?

**Comment by stasgm** [comment]
Пока можем предложить обновиться до последних ПИ

**Comment by hirurg-lybitel** [comment]
@supportkkc 
Никаких баз вроде не получали. Актуально?
