### ISSUE TITLE
Синхронизация КС и Фронт check

### ISSUE THREAD

**Issue by startkkc** [gsbelarus/check-and-cash#139]
1) Не происходит синхронизация контактов питания сотрудников. 
2) Обновить мануал по настройке КС и фронта check.

**Comment by startkkc** [comment]
Настройка КС по инструкции не даёт результатов для синхронизации. Сотрудники не попадают во фронт.

**Comment by hirurg-lybitel** [comment]
Проверено. Попадают.

Надо рассматривать ваш конкретный случай.

**Comment by startkkc** [comment]
По работе синхронизации разберусь позже (заказы передаются, оплаты нет), КС будет убран
