### ISSUE TITLE
Продажа сертификата. 

### ISSUE THREAD

**Issue by gsbelarus** [gsbelarus/check-and-cash#14]
Продажа сертификата.

**Comment by MAliaksandr** [comment]
Сертификат, по-моему, должен продаваться как определенный товар, т.е. печататься ФЧ (который потом крепится к сертификату и хранится вместе с ним до момента расчета). При расчета сертификатом, уже интересно. Вариантов может быть несколько. Продолжать?

**Comment by hirurg-lybitel** [comment]
@MAliaksandr  Так и сделано.. в прошлом году..

Оплата покупки сертификатом происходит отдельным типом оплаты "Сертификат".
