### ISSUE TITLE
Обновление структуры БД cash (касса и КС)

### ISSUE THREAD

**Issue by startkkc** [gsbelarus/check-and-cash#142]
gedemin.exe от сентября нормально обновляет структуру БД
![91](https://user-images.githubusercontent.com/17782689/34675148-b61d2814-f499-11e7-8de9-3151b4bdbe75.png)
при текущей версии gedemin.exe не хочет обновлять
![92](https://user-images.githubusercontent.com/17782689/34675186-d7c80952-f499-11e7-8c2a-3b9af31f4c1f.png)

**Comment by gsbelarus** [comment]
надо взять с сайта простой экзешник и обновить им структуру

**Comment by startkkc** [comment]
Предлагаете возить с собой несколько exe`шников?
