### ISSUE TITLE
Коряво работают помесячные карты

### ISSUE THREAD

**Issue by MAliaksandr** [gsbelarus/check-and-cash#143]
Столкнулись с проблемой работоспособности помесячных карт. 
Накопленная сумма покупок предыдущего месяца должна влиять на процент скидки в текущем месяце. На текущий момент данная схема не работает как надо.
Пример:
покупки в прошлом месяце составили 320р т.е. в текущем месяце должна быть скидка 3%.
Если происходит первая продажа, касса верно определяет что 3% и делает верную скидку, однако последующее использование карты перестает нормально отрабатывать. т.е. согласно правилу сумм от 0 до 100р делает 1% вместо 3%. Думаю проблема в обнулении сумм по карте. Предлагаю добавить дополнительное поле суммы и, возможно, процента предыдущего месяца. а в идеале было бы сделать доп. таблицу, которая бы хранила суммы, накопленные в разных месяцах по данной карте на случай анализа.

**Comment by stasgm** [comment]
Саша, понизь градус критичности ошибок. Смотри как определять тут http://www.protesting.ru/testing/bugpriority.html

**Comment by MAliaksandr** [comment]
Стас,я не вижу смысла понижать градус, система не работает. Во-первых, если использовать ту систему, которая сейчас, можно нарваться на неприятности со стороны клиента. Представь, ты пришел в магазин, у тя есть скидка и ты рассчитал что нуужно будет отдать 30р, ты набрал товара и на кассе говорят, извините, но вы должны не 30р, а 35. наверное ты с улыбкой на лице сбегаешь домой и возьмешь еще рублей 10, чтоб наверняка. Тем более тебе тут совсем рядом. на автобусе минут 40...

**Comment by stasgm** [comment]
Статус "Severity - Critical" - значит, что ты должен не 35, а 70. А пока должен 35, то это всего лишь "Severity - High" )

**Comment by hirurg-lybitel** [comment]
@MAliaksandr если неактуально, то закрывай

**Comment by MAliaksandr** [comment]
сегодня-завтра проверим, если все норм - закроем

**Comment by hirurg-lybitel** [comment]
@MAliaksandr  ???

**Comment by MAliaksandr** [comment]
кассовая и серверная часть вроде нормально.
