### ISSUE TITLE
долго открытие брони

### ISSUE THREAD

**Issue by supportkkc** [gsbelarus/check-and-cash#144]
Программа Positive check при нажатии на вкладку бронирование она открывается примерно 3 минуты, но заказы и остальные вкладки работают нормально.

**Comment by hirurg-lybitel** [comment]
это у любого клиента или у кого-то конкретно?

**Comment by startkkc** [comment]
Конкретно у одного клиента.

**Comment by hirurg-lybitel** [comment]
Мы должны обзвонить всех своих клиентов или вы просто скинете базу?
