### ISSUE TITLE
После оплаты следующий заказ открывается через 10 секунд (POSitive Check)

### ISSUE THREAD

**Issue by supportkkc** [gsbelarus/check-and-cash#145]
После оплаты следующий заказ открывается через секунд 10. Была произведена очистка базы от заказов с помощью SQL  команд, бэкап-разбэкап базы с очисткой мусора. Через сутки проблема вернулась.

**Comment by startkkc** [comment]
Кто занимается проблемой?

**Comment by hirurg-lybitel** [comment]
Это случаем не на Керамине проблема?

**Comment by startkkc** [comment]
Как бы юр.лица писать запрещено)

**Comment by stasgm** [comment]
@supportkkc можно отправить на почту информацию по клиенту, а тут сослаться на письмо. Если это проблема частная т.к. касается конкретного клиента, то можно сразу на почту.

**Comment by hirurg-lybitel** [comment]
@supportkkc 
Никакой информации по проблеме до сих пор не получили. Ещё актуально или закрывать?
