### ISSUE TITLE
Ошибки в скидках.

### ISSUE THREAD

**Issue by startkkc** [gsbelarus/check-and-cash#147]
Positive cash
1) После применения скидки, не верно отображается строка.
![imag0478](https://user-images.githubusercontent.com/17782689/38502976-8d61662a-3c19-11e8-9e5e-ae8e03d5c103.jpg)
2) Не верно вычисляется автоматическая скидка.
![imag0478_2](https://user-images.githubusercontent.com/17782689/38503102-d04f5b36-3c19-11e8-9311-bafb2a205dfe.jpg)
3) Во время возврата, при редактировании кол-ва, не верно показана строка и итог.
![imag0479](https://user-images.githubusercontent.com/17782689/38503148-feb69df4-3c19-11e8-8f4c-6a42b2b01918.jpg)

**Comment by hirurg-lybitel** [comment]
1. И что неверного? 1.55 * (1 - 0.03) = 1.50 * 10 = 15

2.  Уверен, что там применилась не одна скидка. Надо посмотреть конкретно вашу базу

3. Поправил. Обновить **GS.PositiveCash.Рабочее место кассира**

**Comment by startkkc** [comment]
1.  После применения скидки в нижней сроке 10 * 1.55 = 15,00, это не верное утверждение.
2.  Отправил на почту.
3.  Спасибо.

**Comment by hirurg-lybitel** [comment]
1. Теперь понял. Исправил.
2. Как и предполагалось, применяется две скидки по 20%. Дело в том, что в правиле скидок вырана и группа ТМЦ и Товар, а должно быть что-то одно.
![image](https://user-images.githubusercontent.com/11502258/38767810-2663f9fc-3ff1-11e8-8f3f-5e500d510707.png)

**Comment by startkkc** [comment]
Спасибо

**Comment by hirurg-lybitel** [comment]
Всегда к вашим услугам ;)
