### ISSUE TITLE
Клиент интересуется

### ISSUE THREAD

**Issue by startkkc** [gsbelarus/check-and-cash#148]
Возможна ли доработка и сколько по времени. Positive cash
"При внесении чека в систему, необходимо добавить возможность выбора ФИО специалиста, который сформировал заказ. Эти данные должны выгружаться в 1С, а список сотрудников должен выгружаться из 1С в POS-систему."
Механизм выбора специалиста есть - продавец. Выгрузка продавца то же есть (в позиции чеков). Возможно её заменить на id? Получается нужна только доработка импорта продавцов.

**Comment by hirurg-lybitel** [comment]
Если я правильно понял, то есть две задачи:

1. Сделать загрузку продавцов в программу (либо нами через файл, либо из 1С напрямую)
2. Поменять в выгрузке продаж имя продавца на его индентификатор. 

Да, это возможно. Займёт приблизительно 3 часа.

**Comment by startkkc** [comment]
2. Он выгружается, извиняюсь не приметил.
Спасибо за информацию
