### ISSUE TITLE
Округление

### ISSUE THREAD

**Issue by startkkc** [gsbelarus/check-and-cash#149]
@stasgm Positive check, у клиента была проблема с округлением. Ты её решил. Сейчас снова реализация в 1с не загрузилась из-за округления.
3.6 * 2 + 13.97 * 0.568 = 15.13, а система выгрузила 15.14

**Comment by stasgm** [comment]
@startkkc нашёл решение. Завтра протестирую работу с фискальником и вышлю настройку

**Comment by startkkc** [comment]
Спасибо. Ждём

**Comment by stasgm** [comment]
Проверено.
Обновить клиенту ПИ:
- GS.PositiveCheck. Документы. Заказы.yml
- GS.PositiveCheck. Метаданные.yml

**Comment by startkkc** [comment]
Т.е. желательно это обновить всем клиентам?

**Comment by stasgm** [comment]
@startkkc можно только тем, кто с весовым товаром работает

**Comment by startkkc** [comment]
Частичное обновление, только эти ПИ, рассыпало всю программу.

**Comment by stasgm** [comment]
Что такое "рассыпало"?

**Comment by startkkc** [comment]
При добавлении новой позиции в чек
![131313131](https://user-images.githubusercontent.com/17782689/39240750-67d1e9fe-488d-11e8-9688-7865453e29dd.png)
Если пытаюсь закрыть окно
![ew](https://user-images.githubusercontent.com/17782689/39240784-78bd1644-488d-11e8-8538-34202e8a1eda.png)

**Comment by stasgm** [comment]
Надо ещё ставить GS.PositiveCheck.Метаданные.Параметры

**Comment by startkkc** [comment]
спасибо
