### ISSUE TITLE
Питание сотрудников

### ISSUE THREAD

**Issue by startkkc** [gsbelarus/check-and-cash#150]
Positive Cash
Клиент рассматривает возможность отпуска продукции в кредит. В Cash перенесены из Сheck, карты сотрудников, кредитные лимиты и формирования лимитов. Проверил ручное создание сотрудников и оплату. 
1)Не работает добавление "формирование лимитов". sql ошибка.
2)В логе синхронизации завис кредитный лимит, нет ошибки и касса его не забирает
3)Нужна, как и в Check возможность импорта из файла.

**Comment by hirurg-lybitel** [comment]
1) Обновить **GS.PositiveCheck.Лимиты.Функции**
2) Прикольненько. Это всё, что можно сказать по этой информации.
3) Обновить **GS.PositiveCash.CashServer.Синхронизация.Макросы**

**Comment by startkkc** [comment]
2. Я создавал руками лимиты. У тебя все данные передались? В логе ничего не осталось?

**Comment by hirurg-lybitel** [comment]
у меня где? никаких баз мне не скидывали, а на эталоне всё работает
