### ISSUE TITLE
Исправить логику применения скидок в чеке

### ISSUE THREAD

**Issue by hirurg-lybitel** [gsbelarus/check-and-cash#152]
Необходимо применять правила скидок к каждой конкретной позиции, а не ко всему чеку (так у нас работают скидки в PositiveCheke).
Сейчас, например, если на один товар действует одно правило скидки (напр., 20%), на второй - совершенно другое (напр., 30%) и в этих правилах установлен флаг "не считать далее", то скидка применится только к одному товару.
Хотя в этом случае для первого товара должно сработать свое правило (примениться скидка 20%), после чего правила с меньшим приоритетом для этого не должны примениться, а для второго товара - соответственно свое (примениться скидка 30%).

**Comment by hirurg-lybitel** [comment]
@yoannawx попробуй обновить и проверить текущую схему расчёта

**Comment by yoannawx** [comment]
спасибо, работает, только если скидки накладываются, процент не пересчитывается, поэтому не понятно, откуда возникает увеличенная сумма скидки.
добавьте еще пересчет процента, плиз

**Comment by hirurg-lybitel** [comment]
@yoannawx  Вы такая милая, что сверхурочно поработали и сделала данный пересчёт.

**Comment by yoannawx** [comment]
настолько сверхурочно, что язык заплетается, да? 
если серьезно, то все отлично. 
только сделай округление процента скидки до целого. а то в случае, если применяется только одна скидка, процент из-за погрешности при пересчетах меняется на уровне второго знака

**Comment by hirurg-lybitel** [comment]
Но ведь тогда это не будет отображать математическую действительность?

**Comment by yoannawx** [comment]
очень даже точно отображает, проверила на разных сочетаниях скидок.
