### ISSUE TITLE
Не идет накопление по картам

### ISSUE THREAD

**Issue by startkkc** [gsbelarus/check-and-cash#156]
Накопительные карты не отображают накопление. Ни на кассе ни на сервере. Продажи есть с картами, где-то карты уже поменяли процент.
БД Выслал.

**Comment by hirurg-lybitel** [comment]
Вопрос решён? 
Кому БД выслал?

**Comment by startkkc** [comment]
Ты же в отпуске был, @stasgm конечно. Тебе то же скинул

**Comment by hirurg-lybitel** [comment]
У меня не получается воспроизвести данную проблему на базах, которые мне прислали.

Попробуйте вы проделать тоже самое.
