### ISSUE TITLE
Оплата сертификатов

### ISSUE THREAD

**Issue by supportkkc** [gsbelarus/check-and-cash#158]
На объекте с PositiveCash была введена продажа сертификатов. Проблема с которой столкнулся клиент заключается в том, что ПО не дает возможности использовать несколько сертификатов за один раз. Просьба доработать функциональность сертификатов.

**Comment by hirurg-lybitel** [comment]
А опишите ситуацию поподробней, в которой есть такая необходимость.

**Comment by supportkkc** [comment]
Пример: Покупатель хочет купить серьги за 200руб, предоставляет два сертификата по 50руб и эти два сертификата нужно использовать в одной продаже.

**Comment by supportkkc** [comment]
@hirurg-lybitel Есть ли какая информация на счет скидок?

**Comment by hirurg-lybitel** [comment]
пока это невозможно
