### ISSUE TITLE
Тест дисплея покупателя

### ISSUE THREAD

**Issue by startkkc** [gsbelarus/check-and-cash#163]
@hirurg-lybitel Появилась новая модель дисплея покупателя, в check - работает, а в cash - нет. Разница в выборе типа дисплея в первом "дисплей posiflex", во втором "дисплеи COM", в чем разница .dll у этих типов?

**Comment by hirurg-lybitel** [comment]
Дисплей вообще никак не реагирует?

**Comment by startkkc** [comment]
реагирует, но паказывает символы

**Comment by hirurg-lybitel** [comment]
Проблема только с русскими буквами? 
Вообще хорошо бы просто подключиться и посмотреть

**Comment by startkkc** [comment]
в любое время, жду подключения

**Comment by startkkc** [comment]
Дисплей покупателя у Вас на офисе.

**Comment by hirurg-lybitel** [comment]
Обновить ПИ:
- GS.PositiveCash.Рабочее место кассира
- GS.PositiveCash.06Настройки
- GS.PositiveCash.Общее.VB-элементы

**Comment by startkkc** [comment]
Спасибо
