### ISSUE TITLE
Доработать питание персонала на позитив-кэш

### ISSUE THREAD

**Issue by hirurg-lybitel** [gsbelarus/check-and-cash#165]
Добавить возможность применения скидки к товарам при расчете по картам персонала

**Comment by hirurg-lybitel** [comment]
@yoannawx  можно проверять

**Comment by hirurg-lybitel** [comment]
можно закрывать?

**Comment by yoannawx** [comment]
пока не проверяла, не на ком

**Comment by hirurg-lybitel** [comment]
так а для кого делали?)

**Comment by yoannawx** [comment]
для эталона
