### ISSUE TITLE
Добавить ф-ю определения последнего номера чека с КС.

### ISSUE THREAD

**Issue by MAliaksandr** [gsbelarus/check-and-cash#167]
**Проблема:**
Периодически появляется проблема с дублированием номеров чеков в кассовом сервере. **Предпосылки:** когда идет подмена базы кассы на новую(другую, левую и т.п.), забывают определить максимальное значение номера чека в кассовом сервере для данной кассы. 
**Что получается в итоге:** касса, передает чеки на кассовый сервер, находит такие же номера и обновляет эти чеки, вставляя товары, при этом, естественно, начинается неразбериха с реализацией. Выковырять товары из обновленных чеков очень проблемно.
**Решение:** предлагаю добавить функцию проверки кассового сервера на значение максимального номера чека для текущей кассы (с этим именем). Встроить ее можно в стандартную форму "проверки настроек". Понятно, что тут надо учесть, что данная проверка должна отрабатывать после настройки кассы, иначе толку  от нее не будет. И делать предлагаю это именно программно, потому как не каждый, работающий с кассой человек, знает куда посмотреть...

**Comment by hirurg-lybitel** [comment]
Такая функция уже имеется в пункте проверки настроек кассового сервера. При обнаружении проблемы с нумерацией чеков, соответствующий пункт будет добавлен в результат проверки.

![image](https://user-images.githubusercontent.com/11502258/46812295-19aa5700-cd7d-11e8-9cce-538b4a3714ad.png)
