### ISSUE TITLE
Сделать отдельное пі для обновленія

### ISSUE THREAD

**Issue by yoannawx** [gsbelarus/check-and-cash#169]
надо предусмотреть пи чек и отдельное пи чек.обновление, в которое не будут включены пользовательские настройки, типа прав групп пользователей, опцій і т.д., т.е. того, что настраівается под організацію прі установке по тз. 
большая беда, когда такіе настройкі прі обновленіі затираются некими типовыми

**Comment by hirurg-lybitel** [comment]
Мне кажется более логичным просто сохранять пользовательские настройки перед обновлением.
Тем более многие настройки хранятся в отдельных пи, которые можно банально не обновлять.

**Comment by alexandra-gsoftware** [comment]
А почему затираются? Если ставить без галочки Всегда перезаписывать, то не должны же

**Comment by yoannawx** [comment]
потому что без галочки не перезапишутся все пи, входящие в пакет. 
а нужно, чтоб не затирались только отдельные пи из пакета (если конечно эти пользовательские параметры входят в отдельные пи). 
поэтому и предлагаю сделать отдельное пакетное пи для обновления, в котором в отличие от полного пакета не будет пи с пользовательскими настройками.
а по поводу "просто сохранять пользовательские настройки перед обновлением" и "можно банально не обновлять" - в таком случае надо написать инструкцию по обновлению, в которой указать, что сохранять и что не обновлять. 
потому что "специалисты" обновляют пи пакетом, который лежит на сайте, не подозревая, что после обновления послетают все настройки и параметры на базе.
