### ISSUE TITLE
Сервис чеки

### ISSUE THREAD

**Issue by startkkc** [gsbelarus/check-and-cash#172]
У клиента периодически возникает проблема. На точки производства, выходит задвоенное кол-во позиций. Не 10,  а 20, не 3, а 6. По логам ничего, имеются чеки с временем.

**Comment by stasgm** [comment]
Проверьте справочник принтеров. Если на одно производство будет указан 2 раза один и тот же принтер, то будет дублировть.

**Comment by hirurg-lybitel** [comment]
Учитывая, что проблема была 17.11, а справочники в последний раз редактировались 23.11, то вариант предложенный @stasgm очень вероятен. В любом случае без архива до 23.11 ничего сказать поэтому поводу точно невозможно

**Comment by stasgm** [comment]
Я проверил запрос. Единственный вариант дублирования позиций это дубликат принтера в справочнике. Косвенно указывает на это то, что в присланных фото все позиции задублированы ровно в 2 раза и только по бару.

**Comment by stasgm** [comment]
Пока закрываем. Если повторится то откроем
