### ISSUE TITLE
Отчеты по питанию сотрудников

### ISSUE THREAD

**Issue by startkkc** [gsbelarus/check-and-cash#174]
В ПО Positive Check, есть возможность использовать питание "В КРЕДИТ", и строить отчеты (общие, по сотруднику итд). В ПО Positive Cash, так же есть возможность исользовать питание "В КРЕДИТ", но вот посмотреть отчет по этой операции нельзя, их попросту нет. Возможно эти отчеты были реализованы в backoffice Торговля и склад. Сдейлайте возможным строить отчеты, как в Positive Check на Кассовом сервере.

**Comment by hirurg-lybitel** [comment]
@yoannawx есть ли какие-то отчёты на складе? если да, то можно ли их перенести на КС?

**Comment by yoannawx** [comment]
есть два отчета на бэке (на форме удаленного просмотра), деланные под заказчика. могу передать тебе их настройкой, чтоб ты проанализировал, те ли формы нужны для эталона

**Comment by hirurg-lybitel** [comment]
Обновить пакет ПИ **GS.PositiveCheck.Лимиты**

![image](https://user-images.githubusercontent.com/11502258/50374179-72a72e80-05fb-11e9-81cf-33e81e553010.png)

**Comment by startkkc** [comment]
@hirurg-lybitel Там еще без СКНО, какие ПИ обновить?

**Comment by hirurg-lybitel** [comment]
это же кэш. Тут пофиг на скно.
Обновлять отдельно ПИ не рекоменую, особенно на старых базах.

**Comment by hirurg-lybitel** [comment]
Как отчёты? Правиьно всё показывают? Нужны ли ещё отчёты?
