### ISSUE TITLE
Ошибка в работе службы ФР.

### ISSUE THREAD

**Issue by startkkc** [gsbelarus/check-and-cash#175]
В работе службы ФР positive Check, есть ошибка. Появляется при попытке обратититься к ФР с другого терминала.

**Comment by hirurg-lybitel** [comment]
Пока решение следующее.

- Зайти в административную часть программы под пользователем Term (пароль 1).
- Открыть Редактор скрипт-объхетов
![image](https://user-images.githubusercontent.com/11502258/50525184-0fca0180-0aeb-11e9-9b0c-f7d74a6cdb91.png)

- Установить использование отладочной информации
![image](https://user-images.githubusercontent.com/11502258/50525168-e315ea00-0aea-11e9-9555-f7215b2a4437.png)

- Переподключиться

**Comment by hirurg-lybitel** [comment]
Ещё одно решение - вернуть всё, как было и обновить GS.PositiveCheck. Глобальные макросы
