### ISSUE TITLE
Выгрузка в весы VPMProffessional

### ISSUE THREAD

**Issue by hirurg-lybitel** [gsbelarus/check-and-cash#176]
Добавить на кассовый сервер выгрузка в данные весы.

- [x] Код взять с базы БЭКа из функции usrg_actUnLoadInScalesOnExecute

- [x] в поле CONTENT текстового файла записывать description із gd_good

**Comment by yoannawx** [comment]
дополнить выгрузку:
в поле CONTENT текстового файла записывать description із gd_good

**Comment by hirurg-lybitel** [comment]
@MesnikRoman
