### ISSUE TITLE
Пересчет скидки

### ISSUE THREAD

**Issue by startkkc** [gsbelarus/check-and-cash#178]
@hirurg-lybitel В Positive cash в эталоне, существует пересчет скидки с учетом округления. Клиенту не нравится дробная скидка (хоть это и правильно), каждому клиенту объяснять почему так. Можно ли сделать механизм округления до целой, либо убрать пересчет?

**Comment by hirurg-lybitel** [comment]
Добавил округление до целого числа  в основном окне и при печати чека
