### ISSUE TITLE
Не корректно работае служба ФР (Check)

### ISSUE THREAD

**Issue by startkkc** [gsbelarus/check-and-cash#179]
@hirurg-lybitel 1) При использовании Аванса в коррекцию не идет сумма Аванса (если реализовано через скидку). На оплату идет только остаток от заказ - аванс. 2) В системе больше заказов чем в ФР.

**Comment by hirurg-lybitel** [comment]
Обновить **GS.PositiveCheck. Term. Формы. Заказ. Оплата**
