### ISSUE TITLE
На сайте, в инстоляцию сервера включается какая-то левая база

### ISSUE THREAD

**Issue by startkkc** [gsbelarus/check-and-cash#18]
Провожу тест positive cash (+server), скаченные с сайта 9.06.16.
1) Список оборудования практически пуст, всего две позиции,
2) Проверка связи работает, проверка настроек - НЕТ, такая вот ошибка
скрипт-функция usrg_actTestServerSettingsOnExecute: 
**Dynamic SQL Error
SQL error code = -206
Column unknown
USR$SYNCHR
At line 1, column 23, строка: 37

Обратитесь к администратору**
3) Синхронизация не проходит, видимо из-за того, что ни одного пользователя нет кроме Administrator и созданного при первом входе, а должен быть еще как минимум Synchronizer.

**скрипт-функция pf_SynchronizePrice: 
Dynamic SQL Error
SQL error code = -204
Table unknown
USR$PF_CASHLOG
At line 1, column 199, строка: 78

Обратитесь к администратору**

**Comment by hirurg-lybitel** [comment]
@gsbelarus инсталляция кассового сервера как-то не так собирается. В установленной базе нет ни одного ПИ с префиксом CashServer.

**Comment by hirurg-lybitel** [comment]
@gsbelarus ну что там?

**Comment by gsbelarus** [comment]
На выходных разберусь.

**Comment by gsbelarus** [comment]
Все ок. Проверено.

На всякий случай:

1) инстоляция никогда не перезаписывает файл бд, если он существует
2) деинстоляция никогда не удаляет файл бд

т.е. если какой-то левый файл бд лежит в нужном нам месте, то он останется
после инстоляции.

Вывод:

Проверить куда ставим. Если там занято, то деинстолировать и удалить
оставшиеся после деинстоляции файлы вручную. затем ставить начисто.
