### ISSUE TITLE
Накопительная система скидок

### ISSUE THREAD

**Issue by MesnikRoman** [gsbelarus/check-and-cash#181]
- [ ] техническое задание
- [ ] таблицы для ведения учёта
- [ ] форма для интерфейса пользователя
- [ ] синхронизация с бэком
- [ ] отчёты

**Comment by hirurg-lybitel** [comment]
@MesnikRoman хотелось бы сегодня увидеть ТЗ

**Comment by stasgm** [comment]
И мне. Совместим наши ТЗ получим Супер ТЗ!

**Comment by hirurg-lybitel** [comment]
[ТЗ](https://docs.google.com/document/d/1SqkBfC723S9kHDDLCsn_Vl7GjvyTcHdEGFzl9ZRGd5o/edit?ts=5c519c9d)

**Comment by hirurg-lybitel** [comment]
@MesnikRoman  ещё актуально?

**Comment by hirurg-lybitel** [comment]
Задача отменена
