### ISSUE TITLE
Статус фискольной смены

### ISSUE THREAD

**Issue by startkkc** [gsbelarus/check-and-cash#183]
@hirurg-lybitel После обновления ПИ в Positive Cash, ПО перестало видеть статус фискальной смены ФР. Сняли z-отчет, а внизу в поле **фискальная смена** написано, что Открыта.

**Comment by startkkc** [comment]
есть информация по решению?

**Comment by hirurg-lybitel** [comment]
обновить:
**GS.PositiveCash.Общее.VB-элементы
GS.PositiveCash.Рабочее место кассира**
