### ISSUE TITLE
отчет по продовцам

### ISSUE THREAD

**Issue by startkkc** [gsbelarus/check-and-cash#184]
@hirurg-lybitel Positive cash, не правильно показывает "отчет по продавцам".  В кол-ве чеков за период ,  итоги нулевые, за день суммы и товары есть, чеков ноль. Если строить за конкретный день, цифры верные.

**Comment by hirurg-lybitel** [comment]
Это какой-то баг. 
Будем разбираться

**Comment by hirurg-lybitel** [comment]
Обновить **GS.PositiveCash.05Отчет**
