### ISSUE TITLE
При расчете питания персонала не считается сумма скидки по чеку

### ISSUE THREAD

**Issue by yoannawx** [gsbelarus/check-and-cash#186]
При расчете итога в кассе (pf_btnTotal, проверка isDiscForStaff ), если была применена дисконтная карта Питание персонала, к позициям чека применяется скидка 100% (в обход правил скидок), но поле USR$ISDISC не заполняется. Это влияет на дальнейшие расчеты.

**Comment by hirurg-lybitel** [comment]
@yoannawx 
Нужен пример конкретный. 
Пока такой проблемы на эталоне не обнаружил.

**Comment by yoannawx** [comment]
это было замечено при применении ДИСКОНТНОЙ карты, к которой привязана эталонная полная скидка 100 % без создания правила скидок. сборка на кассе последняя

**Comment by hirurg-lybitel** [comment]
а в каком слкчае надо применять карточку со стопроцентной скидкой без применения этой скидки?

**Comment by yoannawx** [comment]
в смысле "без применения скидки". Скидку как раз хотели применить. И она применилась, в позициях. Только в шапке чека не рассчиталась.

**Comment by yoannawx** [comment]
последний релиз от 02.04.19?

**Comment by hirurg-lybitel** [comment]
от сегодня
