### ISSUE TITLE
Криво закрылась фискальная смена.

### ISSUE THREAD

**Issue by startkkc** [gsbelarus/check-and-cash#187]
@stasgm Positive Check. Добрый день, на кассе 639 не вышел Z отчет. вышел только дубликат его. И получается данные по закрытию смены не прошли в базу.(по нашей базе касса не закрыла смену).что делать в такой ситуации? По ФР смена закрыта. В базе кассы во вкладке смены фискального регистратора - такая смена (номер 1408) отсутсвует

**Comment by stasgm** [comment]
Написал на почту. После проверки закройте эту задачу.

**Comment by startkkc** [comment]
все ок, спасибо
