### ISSUE TITLE
Счетчик заказов на ФР

### ISSUE THREAD

**Issue by startkkc** [gsbelarus/check-and-cash#188]
@hirurg-lybitel Positive Check. Обнаружил две проблемы:
- печать предчека на ФР, заказа содержащий АВАНС. Выдаёт Bad Value.
- Авансы оформлять и использовать может только менеджер. Он оформляет заказ через бронь с внесенный предоплатой. Система не может сразу передать этот столик новому официантом, а просит сохранить заказ (в счетчик залетает кол +1, сумма 0). Мы его сохраняем и переносим на официанта. Официант вносит блюда и отправляет их на производство (в счетчик залетает кол +1, сумма заказа без аванса).

**Comment by hirurg-lybitel** [comment]
- пытается напечатать строку Аванс с отрицательной суммой. Уберём её и будет на пречеке просто сумма без учёта аванса отображаться. Пойдёт? 
- можно проверять на базе Неро, стенд ККС.

**Comment by startkkc** [comment]
#235 Задача обсуждается там
