### ISSUE TITLE
пречек

### ISSUE THREAD

**Issue by startkkc** [gsbelarus/check-and-cash#189]
@stasgm @hirurg-lybitel  Если не отправлять на производство, а сразу нажать пречек, к заказу не цепляется номер ФР, и заказ становится не виден для данной кассы. Positive Check

**Comment by hirurg-lybitel** [comment]
нужен конкретный пример на конкретной базе. На эталоне всё нормально

**Comment by hirurg-lybitel** [comment]
@startkkc @supportkkc  актуально?

**Comment by startkkc** [comment]
@hirurg-lybitel недавно это повторилось, но ты поправил.
