### ISSUE TITLE
Загрузка скидок применяемых автоматически

### ISSUE THREAD

**Issue by startkkc** [gsbelarus/check-and-cash#19]
В Positive Cash нет загрузки скидок применяемых автоматически.

**Comment by hirurg-lybitel** [comment]
Это относится к GoldenSoftwareLtd/gedemin-apps #138
так что ждём.

**Comment by supportkkc** [comment]
Видел тема 138 закрыта, какой результат?

**Comment by hirurg-lybitel** [comment]
Вы ошиблись. 
Тема 138 открыта.

**Comment by hirurg-lybitel** [comment]
Описание файла обмена [тут](https://github.com/gsbelarus/check-and-cash/blob/master/POSitiveCash/PDF/%D0%A4%D0%BE%D1%80%D0%BC%D0%B0%D1%82%20%D1%84%D0%B0%D0%B9%D0%BB%D0%BE%D0%B2%20DBF.pdf)

Макрос называется "**Импорт автоматических скидок**"

**Comment by supportkkc** [comment]
@hirurg-lybitel Закрывай.
