### ISSUE TITLE
Удаление товаров-исключений с кассового сервера

### ISSUE THREAD

**Issue by yoannawx** [gsbelarus/check-and-cash#190]
Удаление товаров-исключений на бэке не синхронизируется с кассовым сервером. Также не синхронизируется изменение перечня правил скидок (и возможно сертификатов) для переданных товаров-исключений.

**Comment by yoannawx** [comment]
Еще одна проблема с синхронизацией товаров-исключений: если подключается новый сервер, невозможно на него передать уже существующие товары-исключения.
В общем нужно пересмотреть синхронизацию этой таблицы.

**Comment by hirurg-lybitel** [comment]
> Еще одна проблема с синхронизацией товаров-исключений: если подключается новый сервер, невозможно на него передать уже существующие товары-исключения

Для этого есть макрос "Занести данные в лог синхронизации по выбранной таблице" в "00. Таблицы для синхронизации".
Установить крусор на желаемой таблице и запустить макрос. Должно всё необходимое добавиться в лог и для вновь созданного сервера и для уже имеющегося.
