### ISSUE TITLE
Стыковка с новым оборудованием

### ISSUE THREAD

**Issue by startkkc** [gsbelarus/check-and-cash#191]
Positive cash и принтер spark pp7000

**Comment by hirurg-lybitel** [comment]
Ждём принтер

**Comment by startkkc** [comment]
Моё предложение, я буду делать заявку сюда на чек и кэш стыковку оборудования.

**Comment by hirurg-lybitel** [comment]
Клиент сегодня привезёт

**Comment by hirurg-lybitel** [comment]
Стыковки не требуется. Принтер работает с теми же командами, что и предыдующий.
