### ISSUE TITLE
Не верно печатается сдача.

### ISSUE THREAD

**Issue by startkkc** [gsbelarus/check-and-cash#195]
в positive cash в чеке из ПРИНТЕРА (не из ФР), не верно считает сдачу.

**Comment by hirurg-lybitel** [comment]
Проблема с округлениями.

**Comment by startkkc** [comment]
Какие ПИ надо обновить клиенту?

**Comment by hirurg-lybitel** [comment]
обновление будет доступно только со следующей версией программы
