### ISSUE TITLE
Подключить весы CAS в PositiveCheck

### ISSUE THREAD

**Issue by startkkc** [gsbelarus/check-and-cash#196]
@stasgm Весы CAS состыковать c Check. Весы есть в Cash, но нету в Check`е.

**Comment by hirurg-lybitel** [comment]
@startkkc в комплекте нет провода для подключения к компьютеру

**Comment by startkkc** [comment]
Возьми из принтера

**Comment by startkkc** [comment]
глянул, но этих весов нет в кэше, это PR

**Comment by startkkc** [comment]
@hirurg-lybitel Сегодня у вас будет кабель.

**Comment by stasgm** [comment]
@startkkc Кабель у нас есть (в коробке pos-принтера был). У нас нет куда подключить. Отсутствует компьютер с  COM разъёмом.

**Comment by startkkc** [comment]
Кабель и терминал переданы на офис.

**Comment by startkkc** [comment]
@stasgm как обстоят дела?

**Comment by stasgm** [comment]
@startkkc насколько я помню, весы у нас забрали, а новые не привозили

**Comment by startkkc** [comment]
@stasgm их не забрали, и к сожалению не могу организовать себе такие же весы. Пока нет поставки

**Comment by stasgm** [comment]
@startkkc спустя время и мы заметили, что весы не забрали.

**Comment by startkkc** [comment]
@alexandra-gsoftware в Cash работает. Как перенесешь в check - закрывай. Спасибо

**Comment by startkkc** [comment]
@alexandra-gsoftware вижу в чеке появились весы CAS. Можешь закрывать.

**Comment by alexandra-gsoftware** [comment]
сейчас одін і тот же модуль весов для чека и для кэша. Добавляем новые весы - появляются там и там
