### ISSUE TITLE
Сообщение

### ISSUE THREAD

**Issue by startkkc** [gsbelarus/check-and-cash#197]
В Positive Cash, установлен вместо ФР, принтер. Выскакивает сообщение примерно каждый час. Нажимают ОК. и продолжают работать
![изображение_viber_2019-07-08_09-37-35](https://user-images.githubusercontent.com/17782689/60806603-1b7a3d00-a18c-11e9-90aa-abc9999b7833.jpg)

**Comment by hirurg-lybitel** [comment]
а чек при этом печатается?

**Comment by startkkc** [comment]
да

**Comment by startkkc** [comment]
после установки ПИ , GS.PositiveCash.05Отчет.yml Печатает только шапку а не весь чек и ошибку частично
![изображение_viber_2019-07-10_11-54-09](https://user-images.githubusercontent.com/17782689/60957553-843cf300-a30d-11e9-988f-df4f8945b7ca.jpg)
