### ISSUE TITLE
Аннулирование чека (positive check)

### ISSUE THREAD

**Issue by startkkc** [gsbelarus/check-and-cash#199]
@stasgm @hirurg-lybitel Бала такая задача "Аннулирование чека #121", её привязали к CASH. Такая же проблема есть и в CHECK, аннулирование проходит (печатается фискальный чек), а чек остаётся висеть в системе, его сейчас удаляют вручную из ЗАКАЗов.

**Comment by hirurg-lybitel** [comment]
Ничего и не дожно удаляться.

Так что, пожалуйста, поподробней о проблеме.

**Comment by startkkc** [comment]
Я не говорю, что чек должен удаляться из системы, но он НЕ ДОЛЖЕН идти в реализацию в xml, и бэк Гедымин. Операция аннулирование, похожа на возврат, только в текущую смену.

**Comment by startkkc** [comment]
@hirurg-lybitel произвел аннулирование 7 чеков, все чеки попали в отчеты и в реализацию.

**Comment by startkkc** [comment]
@alexandra-gsoftware чек который аннулировали так и выгружается в реализацию. (экспорт-выгрузка продаж за период-sales.xml)
