### ISSUE TITLE
Подсказки для кассиров

### ISSUE THREAD

**Issue by gsbelarus** [gsbelarus/check-and-cash#2]
Подсказки для кассиров в зависимости от выполнения условия по скидке.

**Comment by MAliaksandr** [comment]
для подсказок кассиру нужно уже дополнительный монитор ставить.
а вообще информативность окон и функционала нужна

**Comment by hirurg-lybitel** [comment]
Тут имеется ввиду, что отображаться где-то какие скидки были применены к текущему чеку.
