### ISSUE TITLE
Окно оплаты

### ISSUE THREAD

**Issue by startkkc** [gsbelarus/check-and-cash#20]
Новая функция окна оплаты BYR и BYN, это круто. Посоветовался с коллегами, все-таки нужно сделать возможность ввода кассиром полученных денег в BYR и BYN раздельно. Сейчас сумма вводится синхронно в два окна оплаты. И еще при вводе денег больше 1000BYN и попытке расчета - появляется сообщение что не верная сумма.(positive cash)

**Comment by hirurg-lybitel** [comment]
Исправлено в новой версии
