### ISSUE TITLE
Отчеты в Cash на контрольной ленте

### ISSUE THREAD

**Issue by alexandra-gsoftware** [gsbelarus/check-and-cash#200]
Есть три отчета: по тмц, по секциям, по кассирам
Все дают разные результаты.
В одних учитываются отмены и аннулирования, в других нет
В отчетах по тмц и секциям поле количество продаж имеет разное значение по смыслу
и тд
Если эти отчеты не нужны - может, убрать их?
Если нужны - проверить?

**Comment by hirurg-lybitel** [comment]
не нужны

**Comment by alexandra-gsoftware** [comment]
т.е. нужно выкинуть из ПИ действие "отчеты на КЛ", форму "отчеты на КЛ", и сами отчеты, так?
Но в этой же форме строится отчет по ЭКЛЗ.

**Comment by alexandra-gsoftware** [comment]
Вообще не понимаю, что с этой формой.
Три кнопки, которые не работают, и одна, которая нужна. Что с ней делать?

**Comment by hirurg-lybitel** [comment]
Зачем с ней что-то делать?

**Comment by alexandra-gsoftware** [comment]
На ней были кнопки для трех отчетов, которые не работали. И кнопка для отчета по КЛ. Теперь там еще кнопка для отчета по СКНО. Вроде сейчас все кнопки работают, надо посмотреть, что там в самих отчетах. Завтра скину в ветку кэш

**Comment by alexandra-gsoftware** [comment]
исправлено
