### ISSUE TITLE
Возврат с бонусами в Cash

### ISSUE THREAD

**Issue by alexandra-gsoftware** [gsbelarus/check-and-cash#201]
Может я криво настроила бонусы, но получаю такое:

продажа: 5 р нал, 5 р бонусами
возврат по этому чеку: гедымин предлагает вернуть 5р наличными, 5 р безналом и 5 р бонусами. Поменять эти суммы нельзя, и закрыть возврат нельзя, тк сумма оплат 15 р, а не 10

**Comment by hirurg-lybitel** [comment]
@ @ @
