### ISSUE TITLE
Аннулирование в Cash и контроль остатков

### ISSUE THREAD

**Issue by alexandra-gsoftware** [gsbelarus/check-and-cash#202]
Аннулирование не влияет на остатки в кассе, даже если стоит контроль остатков. По аннулированному чеку можно сделать возврат. По чеку продажи можно сделать возврат, а потом аннулировать.

как, по идее, должно быть:
1) при аннулировании, находим исходный чек. Если это продажа, проверяем. были ли возвраты. Если были, аннулировать нельзя
2) если это возврат, то... Можно ли аннулировать возврат??
3) копируем чек продажи вместе с позициями. В позициях меняем знак у кол-ва и суммы
4) если нужно, апдейтим прайс
Вроде, этого должно хватить для контроля (в том числе, при попытке возврата)

**Comment by startkkc** [comment]
@alexandra-gsoftware 2. Аннулирование предназначено только для чеков продаж.
