### ISSUE TITLE
check: аннулирование и возврат

### ISSUE THREAD

**Issue by alexandra-gsoftware** [gsbelarus/check-and-cash#206]
Можно сделать возврат по аннулированному чеку

**Comment by startkkc** [comment]
@alexandra-gsoftware такая операция невозможна. Спрашивал у коллеги, аннулирование и возврат применяются только к продаже.

**Comment by alexandra-gsoftware** [comment]
у нас в кэше можно:
- продать чек 666
- аннулировать чек 666
- сделать возврат по чеку 666
Последнее, очевидно, неверно
