### ISSUE TITLE
check: отчеты на КЛ

### ISSUE THREAD

**Issue by alexandra-gsoftware** [gsbelarus/check-and-cash#207]
отчеты по секциям и спецпитанию запрашивают даты, но не используют их, а используют номер смены, который всегда 0

**Comment by hirurg-lybitel** [comment]
Почему 0 ? 
У меня вроде нормально автоматом подставляется номер текущей смены

![image](https://user-images.githubusercontent.com/11502258/67896721-fc098480-fb6d-11e9-8387-18d244bbe193.png)
