### ISSUE TITLE
выгрузка чеков в КС и back

### ISSUE THREAD

**Issue by startkkc** [gsbelarus/check-and-cash#21]
1) При режиме работы в 24ч переходящий чек (открыт одной датой, а закрыт уже в другой) - чек остается не переданным на кассе.
2) Реализация в back загружается за дату (с 00 00- 23 59) и отображается номер кассы, дата, загруженная реализация, а z - отчет с кассы может сниматься на 5 минут раньше или на 5 минут позже, что приводит к разным итогам.

**Comment by hirurg-lybitel** [comment]
@startkkc Предлагаю ввести номер смены и строить отчёты в разрезе этого номера, а не в разрезе даты. Нормально?

**Comment by startkkc** [comment]
ты у меня спрашиваешь?! вам виднее в бэке.

**Comment by hirurg-lybitel** [comment]
@startkkc я про бэк ничего не спрашивал. Вопрос был конкретно про логику работу на кассах и использование отчётности.

**Comment by startkkc** [comment]
давай отталкиваться от фискальной смены. Возможно конечно ввести такое понятие как бизнес день и для магазина, но.... думаю будет лишним. Отчеты лучше оставить возможность сортировать по времени.

**Comment by hirurg-lybitel** [comment]
@yoannawx как бы это в бэке реализовать?

**Comment by supportkkc** [comment]
Больше идей нет?!))) Магазин, где было 24ч уже не работает, но хотелось бы закрыть этот вопрос, чтобы не возвращаться

**Comment by supportkkc** [comment]
@hirurg-lybitel Раз этот вопрос не развивается. Закрывайте

**Comment by hirurg-lybitel** [comment]
Пока нет ни одного клиента с таким графиком работы, так что такая разработка не атуальна.
