### ISSUE TITLE
Добавить в окне "поле для синхронизации" возможность указывать ссылку на связанную таблицу 

### ISSUE THREAD

**Issue by stasgm** [gsbelarus/check-and-cash#215]
Иногда разработчики добавляют в таблицу новое поле типа Integer вместо домена ссылки на таблицу (пример поля contactkey в таблице gd_company). Такие поля обрабатываются при синхронизации данных как обычные. Это приводит к проблеме при открытии диалоговых окон т.к. нарушена ссылочная целостность.

Предлагаю сделать в окне "Поля для синхронизации" ещё 1 пару таблица\поле для указания связи и во фронтовой части брать данные для получения уже локального ID.

![image](https://user-images.githubusercontent.com/8355925/65690493-da514500-e077-11e9-8995-0ada99593e5e.png)

**Comment by hirurg-lybitel** [comment]
проверь такой вариант

**Comment by hirurg-lybitel** [comment]
@stasgm подошло?
