### ISSUE TITLE
Статусы СКНО

### ISSUE THREAD

**Issue by alexandra-gsoftware** [gsbelarus/check-and-cash#217]
Нужен отчет 'Состояние СКНО' . На Пирите печатается одной командой, но надо как-то впихнуть его в меню на кассе и ресторане

**Comment by hirurg-lybitel** [comment]
А какую информацию он должен отображать? и зачем?

**Comment by alexandra-gsoftware** [comment]
Зачем - требуют для сертификации. 
Какую - фиг знает, это сам фр по команде строит

**Comment by alexandra-gsoftware** [comment]
![IMG_20191001_182856](https://user-images.githubusercontent.com/11487200/65976954-b5930e00-e479-11e9-92f5-51386eebf73b.jpg)
Такой вот он

**Comment by alexandra-gsoftware** [comment]
добавила в классы фр и меню. Нужно привязать к кнопочке

**Comment by alexandra-gsoftware** [comment]
добавила в класс кассы. Нужно привязать к кнопочке тоже

**Comment by alexandra-gsoftware** [comment]
сделано
