### ISSUE TITLE
Учет услуг на кассе и фронте

### ISSUE THREAD

**Issue by alexandra-gsoftware** [gsbelarus/check-and-cash#218]
Необходимо добавить в справочник тмц группу услуги (взять из бухгалтерии, закинуть в отдельное ПИ). Если товар входит в группу услуги, передавать его на ФР как услугу.

**Comment by hirurg-lybitel** [comment]
необходимо для чего? 
в том же спарке не припомню такого термина даже.

**Comment by alexandra-gsoftware** [comment]
Услуги есть и в пирите, и в титане. Они передаются на фр с пометкой, что это услуги. Владельцы Пирита хотят дополнительную опцию просто

**Comment by alexandra-gsoftware** [comment]
сделано
