### ISSUE TITLE
файл обмена DBF(импорт/экспорт)

### ISSUE THREAD

**Issue by startkkc** [gsbelarus/check-and-cash#22]
1. В работе back (гедымин) + positive, был убран goodcode(Уникальный код ТМЦ), предполагаю из-за возможности задвоения позиций прайса в процессе не верного ввода данных и отправки их на кассу (лучше узнать кто ведет back), а в реализации back (сторонний) + positive - Нет. На Ваше усмотрение.
2. В файле импорта есть "Уникальный код ТМЦ" (GOODCODE), и уникальный штрих-код позиции прайс-листа(BARCODE). В файле выгрузке позиций чеков в "Уникальный код ТМЦ" (GOODCODE) идет почему-то Штрих-код,а в (BARCODE) наоборот  "Уникальный код ТМЦ".

**Comment by hirurg-lybitel** [comment]
1. Выкинул это поле из обмена.
2. В BARCODE будет выгружаться ШК товара.
