### ISSUE TITLE
Классы работы с ФР

### ISSUE THREAD

**Issue by hirurg-lybitel** [gsbelarus/check-and-cash#222]
У меня тут пару вопросв возникло:

- почему типы оплат Спецпитание и Бонусы но одном счётчике в спарке? Это что-то старое?
- тут скорее не вопрос, а мысль. Наши классы имеют очень большую проблему масштабиуремости типовы оплат. В них константами забиты коды + они все зачем-то выгружаются в ФР. У нас их могут быть десятки, а ФР больше 10-15 вряд ли будет поддерживаться. Наверное, надо бы сделать установку типов оплат более динамической

**Comment by alexandra-gsoftware** [comment]
1)в спарке ограниченное число видов оплат, доступны 7 (может, в последней версии это не так). 
2)Я думала об этом, но дело в том, что руиды типов оплат активно используются в коде вне классов печати. Т.е. аванс - это не просто тип оплаты, он считается по определенному алгоритму. Также бонусы, спецпитание. Теоретически оплаты для программы и для кассы можно развязать, выделить типы оплат для фр, и указывать, чем они являются: авансом, спецпитанием и тд. Тогда можно использовать несколько видов карт и безнала.
