### ISSUE TITLE
Разовые купоны на скидку

### ISSUE THREAD

**Issue by hirurg-lybitel** [gsbelarus/check-and-cash#225]
Накидываем сюда пункты ТЗ

**Comment by hirurg-lybitel** [comment]
- учёт купонов в базе
- отключение после использование
- увязка с правилом скидок
- сочетание с другими скидками

**Comment by yoannawx** [comment]
поля:
- номер (код)
- тип купона (наименование акции)
- % скидки 
- размер суммы 
 (купон может быть на процент скидки или на определенную сумму скидки)

остальное вкладывается в правила скидок

сделать макросы генерирования кодов, загрузки из ехел.файла: номер, %, сумма.
добавить в импорт скидок, и сделать синхронизацию с бэком по принципу накопительных карт.

**Comment by hirurg-lybitel** [comment]
> сделать синхронизацию с бэком по принципу накопительных карт
а что это за принцип?

**Comment by yoannawx** [comment]
на бэке должна быть автозадача, которая с определенной периодичностью опрашивает кассовые сервера на предмет изменения информации по купонам. если на каком то кассовом сервере купон использован (отключен - кстати, да, поле отключен еще должно быть) - обновляет (отключает) этот купон на остальных кассовых серверах, чтоб на других магазинах не могли бы им воспользоваться.
