### ISSUE TITLE
Синхронизация весов ВПМ

### ISSUE THREAD

**Issue by startkkc** [gsbelarus/check-and-cash#227]
@hirurg-lybitel В последней версии КС positive cash, есть "выгрузка для весов ВПМ профессионал", нужно сделать следующее:
- в поле BEST_BEFORE, либо ноль, либо организовать (очень хотелось бы) выгрузку даты годности товара. Такого поля в КС нет, но есть в Бэке.
- в поле CONTENT выгружался СОСТАВ из справочника ТМЦ
- поля NAME и CONTENT должны заменять символ ; (точка с запятой), т.к. выгрузка в формате *.csv, а перевод строки либо enter игнорировался.

**Comment by hirurg-lybitel** [comment]
со

**Comment by hirurg-lybitel** [comment]
@startkkc 
Жду подрбностей по первому пункту.
Остальное готово.

**Comment by startkkc** [comment]
@hirurg-lybitel предполагаю, что надо 2 варианта ввода таких данных. 1) конечная дата годности продукта, будет выгружаться статическая дата 2) сколько дней годен продукт, будет выгружаться текущая дата экспорта на весы + дни годности товара. 
BEST_BEFORE | Годен до | Дата и время годности в форматеДД.ММ.ГГГГ ЧЧ:ММ:СС

**Comment by hirurg-lybitel** [comment]
@yoannawx что скажешь по второму пункту?

**Comment by hirurg-lybitel** [comment]
@startkkc это надо обсудить в телефонной бесеседе со специалистом по бэку. 
Набери как-нибудь Жанну Владимировну по этому вопросу.
