### ISSUE TITLE
Возврат товара с оплатой по сертификату

### ISSUE THREAD

**Issue by startkkc** [gsbelarus/check-and-cash#229]
@hirurg-lybitel Необходима доработка по возврату товара, если чек оплачен сертификатом

**Comment by hirurg-lybitel** [comment]
какого рода доработка?

**Comment by startkkc** [comment]
Доработка, согласно которой, при возврате товара оплаченного сертификатом, будет возможность выбрать, какими денежными средствами вернуть товар. Есть письмо от налоговой.

**Comment by hirurg-lybitel** [comment]
> при возврате покупателю стоимости товара, оплаченного ранее посредством подарочного сертификата, на кассовом суммирующем аппарате выполняется операция регистрации факта возврата денежных средств в размере стоимости возвращенного товара.

тут вроде ничего про выбор денежных средств не сказано

**Comment by startkkc** [comment]
Про выбор не написано, но написано что надо "вернуть денежные средства в размере стоимости товара,

**Comment by hirurg-lybitel** [comment]
**При возврате сертификата сумму возвращать только по налу/карте. Никакая информация, собственно, по самому сертификату не меняется.**

**Comment by hirurg-lybitel** [comment]
@aer1k проверь, пожалуйста.
Если ок, то закрой.
