### ISSUE TITLE
Ошибки в БД

### ISSUE THREAD

**Issue by startkkc** [gsbelarus/check-and-cash#230]
Проблема с актуальной БД с сайта. 
![image](https://user-images.githubusercontent.com/17782689/70785741-2c168b00-1d9c-11ea-93c6-4767d602b394.png)

**Comment by gsbelarus** [comment]
база данных на сервере или локально? если на сервере, то в папку UDF файреберда надо подкинуть библиотеку GUDF.DLL, которую взять тут:

http://gsbelarus.com/pw/downloads/?d=7117

**Comment by startkkc** [comment]
Проверяю, тут лежит gUDF, но не знаю что за он. Если это закрою. Спасибо

**Comment by gsbelarus** [comment]
если не поможет, то на базе надо глянуть зарегистрирована ли функция:

```
SELECT * FROM RDB$FUNCTIONS
```

А вообще, она уже вроде не нужна. Вопрос к ПИ, где она и куда попала...

**Comment by startkkc** [comment]
Помогло, возможно 32бит была или еще что. Спасибо
