### ISSUE TITLE
Тест обновленной версии Cash

### ISSUE THREAD

**Issue by startkkc** [gsbelarus/check-and-cash#231]
@hirurg-lybitel при оплате со сдачей за наличные
![image](https://user-images.githubusercontent.com/17782689/70907977-3d20ff80-201b-11ea-87ae-f23af33cf025.png)

**Comment by startkkc** [comment]
Сняте х-отчета
![image](https://user-images.githubusercontent.com/17782689/70908130-87a27c00-201b-11ea-8589-8885fa25c78b.png)

**Comment by alexandra-gsoftware** [comment]
В ветке "чек" я правила ошибки с мессадж боксом, если что @hirurg-lybitel

**Comment by hirurg-lybitel** [comment]
> @hirurg-lybitel при оплате со сдачей за наличные
> ![image](https://user-images.githubusercontent.com/17782689/70907977-3d20ff80-201b-11ea-87ae-f23af33cf025.png)

кассовый серер не обновили

**Comment by hirurg-lybitel** [comment]
> Сняте х-отчета
> ![image](https://user-images.githubusercontent.com/17782689/70908130-87a27c00-201b-11ea-8589-8885fa25c78b.png)

Фишка нового exe.

Поправлено

**Comment by startkkc** [comment]
Аннулировать чек
![image](https://user-images.githubusercontent.com/17782689/71069171-3c0de080-2189-11ea-8d01-aa2e3de4e71b.png)
![image](https://user-images.githubusercontent.com/17782689/71069241-5ba50900-2189-11ea-995e-4e1e445ad622.png)

**Comment by hirurg-lybitel** [comment]
> Аннулировать чек, я вводил номер чека. Я могу ошибаться но вроде раньше был "номер из ФР".
> ![image](https://user-images.githubusercontent.com/17782689/71069171-3c0de080-2189-11ea-8d01-aa2e3de4e71b.png)
> ![image](https://user-images.githubusercontent.com/17782689/71069241-5ba50900-2189-11ea-995e-4e1e445ad622.png)

Исправлено

**Comment by startkkc** [comment]
> > Аннулировать чек, я вводил номер чека. Я могу ошибаться но вроде раньше был "номер из ФР".
> > ![image](https://user-images.githubusercontent.com/17782689/71069171-3c0de080-2189-11ea-8d01-aa2e3de4e71b.png)
> > ![image](https://user-images.githubusercontent.com/17782689/71069241-5ba50900-2189-11ea-995e-4e1e445ad622.png)
> 
> Исправлено ПИ **GS.PositiveCash.Класс печати на ФР**

Обновил все ПИ по кассе, ошибки пропали по аннулированию, но пишет "Illegal command" и ничего не происходит.

**Comment by hirurg-lybitel** [comment]
может не хватает денег в кассе?

проверил, всё гуд.

**Comment by startkkc** [comment]
При обновление КС 
![image](https://user-images.githubusercontent.com/17782689/72156140-d26aa600-33c5-11ea-8f55-3931729c9bde.png)

**Comment by hirurg-lybitel** [comment]
Никаких проблем не обнаружено. 
Есть возможность базу скинуть?

**Comment by startkkc** [comment]
> Никаких проблем не обнаружено.
> Есть возможность базу скинуть?

у тебя на почте

**Comment by hirurg-lybitel** [comment]
попробуйте предварительно удалить все ПИ из базы
**Сервис >> Пространства имён**

**Comment by startkkc** [comment]
@hirurg-lybitel В данной версии ПО не предполагается списывать более одного сертификата к одной продаже. Рассмотрите вариант реализации более одного. Спасибо

**Comment by startkkc** [comment]
Продажа закрыта на пл.карту, Если по продаже сделать возврат то окно оплаты заполняется лишней суммой.
![image](https://user-images.githubusercontent.com/17782689/74735879-9e0ac500-5262-11ea-9bf1-77dff1b46dd8.png)

**Comment by hirurg-lybitel** [comment]
> Продажа закрыта на пл.карту, Если по продаже сделать возврат то окно оплаты заполняется лишней суммой.
> ![image](https://user-images.githubusercontent.com/17782689/74735879-9e0ac500-5262-11ea-9bf1-77dff1b46dd8.png)

Исправлено

**Comment by startkkc** [comment]
При проведении дисконтной картой и применении доп скидки, скидка 2 раза округляется. 3% дисконтаная и 50% доп.скидка (акции), не выходит 53% скидка

**Comment by hirurg-lybitel** [comment]
> При проведении дисконтной картой и применении доп скидки, скидка 2 раза округляется. 3% дисконтаная и 50% доп.скидка (акции), не выходит 53% скидка

Исправлено

**Comment by hirurg-lybitel** [comment]
> > > Аннулировать чек, я вводил номер чека. Я могу ошибаться но вроде раньше был "номер из ФР".
> > > ![image](https://user-images.githubusercontent.com/17782689/71069171-3c0de080-2189-11ea-8d01-aa2e3de4e71b.png)
> > > ![image](https://user-images.githubusercontent.com/17782689/71069241-5ba50900-2189-11ea-995e-4e1e445ad622.png)
> > 
> > 
> > Исправлено ПИ **GS.PositiveCash.Класс печати на ФР**
> 
> Обновил все ПИ по кассе, ошибки пропали по аннулированию, но пишет "Illegal command" и ничего не происходит.

наконец-то нашёл в чём дело. Аннулирование почему-то ломается, если в его процессе (где-нибудь между StartDocument и Tender2) вызвать считывание номера смены (GetDriverOpt(27)).

**Comment by startkkc** [comment]
> @hirurg-lybitel В данной версии ПО не предполагается списывать более одного сертификата к одной продаже. Рассмотрите вариант реализации более одного. Спасибо

@hirurg-lybitel Будет что-то делаться по этому вопросу?

**Comment by hirurg-lybitel** [comment]
@ startkkc 
Добрый день.
Не в ближайшее время

**Comment by startkkc** [comment]
@hirurg-lybitel Можешь связаться с @gsbelarus , он сказал поспособствует ускорению доработки. Мне надо знать сроки.

**Comment by startkkc** [comment]
@hirurg-lybitel при передаче чека на КС, появляется ошибка 
Скрипт-функция pf_CheckInMainBase:
Field "SUMOPLATI" not found, строка: 502

**Comment by hirurg-lybitel** [comment]
@startkkc как и час назад, рекомендую обновить ПИ

**Comment by hirurg-lybitel** [comment]
> @hirurg-lybitel Можешь связаться с @gsbelarus , он сказал поспособствует ускорению доработки. Мне надо знать сроки.

@startkkc Доработка готова. Когда сможете ознакомиться и одобрить?
Мне надо знать сроки.

**Comment by startkkc** [comment]
После обновления ПИ меняется окно авторизации. Можно сделать без gedemin cash
![image](https://user-images.githubusercontent.com/17782689/90864256-01ec8280-e399-11ea-84cb-fd151ab5174a.png)

**Comment by startkkc** [comment]
После обновления в чеке добавляется АРТИКУЛ и [, где-то есть параметр это отключить?
![image](https://user-images.githubusercontent.com/17782689/91018389-34e08180-e5f8-11ea-9336-df20e0b9a4fa.png)
![изображение_viber_2020-08-24_10-53-34](https://user-images.githubusercontent.com/17782689/91018901-dd8ee100-e5f8-11ea-8c43-6459faf28c96.jpg)

**Comment by startkkc** [comment]
Добрый день. Можно ли добавить в "Дисконтные карты", "Накопительные карты", и "Помесячные карты", такой же поиск как и "Бонусных картах". По ФИО, телефону, коду карты.?

**Comment by hirurg-lybitel** [comment]
> Добрый день. Можно ли добавить в "Дисконтные карты", "Накопительные карты", и "Помесячные карты", такой же поиск как и "Бонусных картах". По ФИО, телефону, коду карты.?

Добрый день. О каком поиске в "Бонусных картах идёт речь?


> После обновления в чеке добавляется АРТИКУЛ и [, где-то есть параметр это отключить?
Обновить ПИ **GS.PositiveCash.Класс печати на ФР**


> После обновления ПИ меняется окно авторизации. Можно сделать без gedemin cash
> ![image](https://user-images.githubusercontent.com/17782689/90864256-01ec8280-e399-11ea-84cb-fd151ab5174a.png)
Обновить ПИ **GS.PositiveCash.Рабочее место кассира**

**Comment by startkkc** [comment]
@hirurg-lybitel единая строка для поиска клиента по телефону, коду карты, и ФИО. Такая функция реализована в Бонусных картах.

**Comment by startkkc** [comment]
@alexandra-gsoftware 1) Очень долго импортируются карты, можно что-то с этим сделать. дисконые, или бонусные не важно. Если проц хороший это мин 30 на КС, и передать на кассу еще час. Кассы слабее, это занимает почти 10ч. на 5к карт.
2) При импорте дисконтных карт, контакт не подтягивается к карте.

**Comment by startkkc** [comment]
При возврате товара по номеру чека, при добавлении позиции появляется ошибка.
![image](https://user-images.githubusercontent.com/17782689/94919464-2fab0800-04bd-11eb-899e-b851f020cab9.png)

**Comment by startkkc** [comment]
> @alexandra-gsoftware 1) Очень долго импортируются карты, можно что-то с этим сделать. дисконые, или бонусные не важно. Если проц хороший это мин 30 на КС, и передать на кассу еще час. Кассы слабее, это занимает почти 10ч. на 5к карт.
> 2) При импорте дисконтных карт, контакт не подтягивается к карте.

@alexandra-gsoftware диск. карты с контактами загружаются (3.5к), на КС 9 мин., с КС на кассу 7ч. Предполагаю, что это связано с передачей с КС на кассу контактов.

**Comment by hirurg-lybitel** [comment]
> > @alexandra-gsoftware 1) Очень долго импортируются карты, можно что-то с этим сделать. дисконые, или бонусные не важно. Если проц хороший это мин 30 на КС, и передать на кассу еще час. Кассы слабее, это занимает почти 10ч. на 5к карт.
> > 2) При импорте дисконтных карт, контакт не подтягивается к карте.
> 
> @alexandra-gsoftware диск. карты с контактами загружаются (3.5к), на КС 9 мин., с КС на кассу 7ч. Предполагаю, что это связано с передачей с КС на кассу контактов.

Никаких проблем на текущей версии ПО не замечено. 

Можно получить файл с загружаемыми картами?

**Comment by alexandra-gsoftware** [comment]
@hirurg-lybitel я сегодня поправила на копии бд клиента. Если нормально будет, скину в гит.

**Comment by startkkc** [comment]
@hirurg-lybitel @alexandra-gsoftware Проверил, все грузится быстро, спасибо

**Comment by startkkc** [comment]
Появился вопрос от клиента, использовать не процент скидка, а на сумму. Если использовать цена для сотрудника, придется каждый раз проводить noname картой со скидкой без надбавки. Можно ли установить автоматическое применение к товару второй цены. Я в правиле скидок нашел галку "Вторая цена", но без указания процента она не сохраняет, те два варианта по скрину проверил, цена не применяется.
![image](https://user-images.githubusercontent.com/17782689/97200903-dd5ebd80-17c2-11eb-9b18-91724b484f9b.png)
![image](https://user-images.githubusercontent.com/17782689/97201160-2f9fde80-17c3-11eb-89f0-79b060bd3636.png)

**Comment by startkkc** [comment]
@alexandra-gsoftware @hirurg-lybitel что скажите коллеги?

**Comment by startkkc** [comment]
Будет какой-нибудь комментарий?

**Comment by startkkc** [comment]
@alexandra-gsoftware напоминаю

**Comment by startkkc** [comment]
ответа так и нет.

**Comment by startkkc** [comment]
Если к позиции применить доп.скидку, и сделать сторнирование, у позиции пропадает ранее применённая доп.скидка и появляется такая же позиция с минус кол-вом. Если сделать то же самое, только перед сторнированием зайти в расчёт и выйти, то сторнирование производится не верно. Сторнируемая позиция остаётся со скидкой, а а минусуется полная сумма позиции.
![IMG_4258](https://user-images.githubusercontent.com/17782689/105479880-102b2b80-5cb6-11eb-9181-71b1cb0a73d9.jpg)

**Comment by hirurg-lybitel** [comment]
> Появился вопрос от клиента, использовать не процент скидка, а на сумму. Если использовать цена для сотрудника, придется каждый раз проводить noname картой со скидкой без надбавки. Можно ли установить автоматическое применение к товару второй цены. Я в правиле скидок нашел галку "Вторая цена", но без указания процента она не сохраняет, те два варианта по скрину проверил, цена не применяется.
> ![image](https://user-images.githubusercontent.com/17782689/97200903-dd5ebd80-17c2-11eb-9b18-91724b484f9b.png)
> ![image](https://user-images.githubusercontent.com/17782689/97201160-2f9fde80-17c3-11eb-89f0-79b060bd3636.png)

Нет, нельзя

**Comment by hirurg-lybitel** [comment]
> Если к позиции применить доп.скидку, и сделать сторнирование, у позиции пропадает ранее применённая доп.скидка и появляется такая же позиция с минус кол-вом. Если сделать то же самое, только перед сторнированием зайти в расчёт и выйти, то сторнирование производится не верно. Сторнируемая позиция остаётся со скидкой, а а минусуется полная сумма позиции.
> ![IMG_4258](https://user-images.githubusercontent.com/17782689/105479880-102b2b80-5cb6-11eb-9181-71b1cb0a73d9.jpg)

Не получается воспроизвести ситуацию. Надо смотреть на конкретной базе.

**Comment by startkkc** [comment]
> > Появился вопрос от клиента, использовать не процент скидка, а на сумму. Если использовать цена для сотрудника, придется каждый раз проводить noname картой со скидкой без надбавки. Можно ли установить автоматическое применение к товару второй цены. Я в правиле скидок нашел галку "Вторая цена", но без указания процента она не сохраняет, те два варианта по скрину проверил, цена не применяется.
> > ![image](https://user-images.githubusercontent.com/17782689/97200903-dd5ebd80-17c2-11eb-9b18-91724b484f9b.png)
> > ![image](https://user-images.githubusercontent.com/17782689/97201160-2f9fde80-17c3-11eb-89f0-79b060bd3636.png)
> 
> Нет, нельзя

Для чего нужен этот флаг "вторая цена"?

**Comment by startkkc** [comment]
> > Если к позиции применить доп.скидку, и сделать сторнирование, у позиции пропадает ранее применённая доп.скидка и появляется такая же позиция с минус кол-вом. Если сделать то же самое, только перед сторнированием зайти в расчёт и выйти, то сторнирование производится не верно. Сторнируемая позиция остаётся со скидкой, а а минусуется полная сумма позиции.
> > ![IMG_4258](https://user-images.githubusercontent.com/17782689/105479880-102b2b80-5cb6-11eb-9181-71b1cb0a73d9.jpg)
> 
> Не получается воспроизвести ситуацию. Надо смотреть на конкретной базе.

Можешь проверить на БД, что я прислал по заявке #257. Как писал выше и на этой базе и на очень старой базе такая проблема есть.

**Comment by hirurg-lybitel** [comment]
> > > Появился вопрос от клиента, использовать не процент скидка, а на сумму. Если использовать цена для сотрудника, придется каждый раз проводить noname картой со скидкой без надбавки. Можно ли установить автоматическое применение к товару второй цены. Я в правиле скидок нашел галку "Вторая цена", но без указания процента она не сохраняет, те два варианта по скрину проверил, цена не применяется.
> > > ![image](https://user-images.githubusercontent.com/17782689/97200903-dd5ebd80-17c2-11eb-9b18-91724b484f9b.png)
> > > ![image](https://user-images.githubusercontent.com/17782689/97201160-2f9fde80-17c3-11eb-89f0-79b060bd3636.png)
> > 
> > 
> > Нет, нельзя
> 
> Для чего нужен этот флаг "вторая цена"?

Для применеия скидки на размер наценки. Подставляется значение из поля прайса Цена для сотрудников.

**Comment by hirurg-lybitel** [comment]
> > > Если к позиции применить доп.скидку, и сделать сторнирование, у позиции пропадает ранее применённая доп.скидка и появляется такая же позиция с минус кол-вом. Если сделать то же самое, только перед сторнированием зайти в расчёт и выйти, то сторнирование производится не верно. Сторнируемая позиция остаётся со скидкой, а а минусуется полная сумма позиции.
> > > ![IMG_4258](https://user-images.githubusercontent.com/17782689/105479880-102b2b80-5cb6-11eb-9181-71b1cb0a73d9.jpg)
> > 
> > 
> > Не получается воспроизвести ситуацию. Надо смотреть на конкретной базе.
> 
> Можешь проверить на БД, что я прислал по заявке #257. Как писал выше и на этой базе и на очень старой базе такая проблема есть.

Не выходит что-то и на этой базе.

https://user-images.githubusercontent.com/11502258/105857563-76d48000-5ffb-11eb-92ae-c1b437caed86.mp4
