### ISSUE TITLE
Gedemin check формы

### ISSUE THREAD

**Issue by alexandra-gsoftware** [gsbelarus/check-and-cash#232]
1. Форма фискальных операций (кнопка Касса) : раньше называлась фискальный регистратор, теперь - админимтрирование. Хотя форма администрирование уже есть, это форма операций менеджера! 
2. При вводе нового пользователя пароль теперь называется Скидка.

**Comment by alexandra-gsoftware** [comment]
1 - исправлено

**Comment by hirurg-lybitel** [comment]
@alexandra-gsoftware актуально?
