### ISSUE TITLE
Кассовый сервер

### ISSUE THREAD

**Issue by yoannawx** [gsbelarus/check-and-cash#234]
Устранить следующие вопросы:

- [x] передача чеков с кассы
- [x] скопировать исследователь с кассы
- [x] установить в пакете зависимое ПИ …Окно оплаты 
- [x] отключить "необычные" типы оплат
- [x] показывать окно оплаты при возврате

**Comment by yoannawx** [comment]
- отключить "необычные" типы оплат

**Comment by yoannawx** [comment]
- показывать окно оплаты при возврате

**Comment by startkkc** [comment]
При входе в окно купоны - параметры
![image](https://user-images.githubusercontent.com/17782689/71763393-7f3bb380-2eec-11ea-93d2-bfa15c807bfd.png)
