### ISSUE TITLE
Тест обновленного Check

### ISSUE THREAD

**Issue by startkkc** [gsbelarus/check-and-cash#235]
- Перевернута клавиатура в интерфейсе фронта. Нарисовано снизу вверх, а по факту сверху вниз, т.е. на месте 789 - 123, а на месте 123 - 789.
![image](https://user-images.githubusercontent.com/17782689/71725175-0bde6700-2e44-11ea-84a9-772dc7d56e90.png)
- Если вернуться обратно в заказ, и снова поменять кол-во, то появляется ошибка
![image](https://user-images.githubusercontent.com/17782689/71725224-2a446280-2e44-11ea-9614-5722a0c8c212.png)

**Comment by startkkc** [comment]
- Стартовая страница отличается от эталонной. Надпись Gedemin: Check, вместо Positive: Check
- Стало
![image](https://user-images.githubusercontent.com/17782689/71725358-a76fd780-2e44-11ea-9852-45bfaa937d2e.png)
- Эталон
![image](https://user-images.githubusercontent.com/17782689/71725380-bd7d9800-2e44-11ea-9a42-67f26ced6d15.png)

**Comment by startkkc** [comment]
@hirurg-lybitel есть продвижения? Необходимо обновить клиента.

**Comment by hirurg-lybitel** [comment]
@MesnikRoman ?

**Comment by alexandra-gsoftware** [comment]
в константах есть константа Логотип. Поставить ей значение 2, и загрузятся логотипы ккс

**Comment by startkkc** [comment]
> в константах есть константа Логотип. Поставить ей значение 2, и загрузятся логотипы ккс

@alexandra-gsoftware Обновил ПИ, в константах нет такого пункта.
![image](https://user-images.githubusercontent.com/17782689/72050297-d6b59700-32d1-11ea-8a62-df58a0084480.png)

**Comment by hirurg-lybitel** [comment]
> в константах есть константа Логотип. Поставить ей значение 2, и загрузятся логотипы ккс

1. Мы же уже обсуждали, что окно банально не соответсвует тому, что должно быть.
2. Константа пока должна быть по умолчанию 2.

**Comment by hirurg-lybitel** [comment]
@alexandra-gsoftware @MesnikRoman кто-то что-то будет делать? 
сейчас в мастере лежит какая-та непонятная версия программы, которая начнёт расходиться по клиентам

**Comment by startkkc** [comment]
@hirurg-lybitel уже 2 клиента работают.

**Comment by alexandra-gsoftware** [comment]
@hirurg-lybitel 
1) баги с клавиатурой я поправлю
2) потом нужно скинуть в мастер изменения в чеке
3) если нужно грузить или не грузить картинку с чашкой кофе, то это к Роману. Константу сделаю = 2.

**Comment by alexandra-gsoftware** [comment]
1) исправлены перевернутые кнопки
2) исправлена ошибка при повторном изменении кол-ва
3) работа с логотипами вынесена в отдельное ПИ. Константа = 2.
4) изменеия пока в ветке CHECK
5) картинки с чашкой пока нет, @MesnikRoman , посмотри плз в понедельник. Сделай, чтобы чашка грузилась или нет по принципу логотипов

**Comment by hirurg-lybitel** [comment]
@MesnikRoman что-то есть?

**Comment by MesnikRoman** [comment]
Сделал окно входа с чашкой в ветке CHECK.

**Comment by startkkc** [comment]
В отправленном на производство заказе, удалить более одной позиции приводит к ошибке. Счетчик заказов включён.
При удалении более одной позиции 
![image](https://user-images.githubusercontent.com/17782689/72904404-e6a49080-3d3f-11ea-83b1-4dd1c86b5df1.png)

**Comment by startkkc** [comment]
Не печатается счет (предчек из ФР) у заказа с авансом.
![image](https://user-images.githubusercontent.com/17782689/72965184-b22ae600-3dcc-11ea-914b-5ed044ac5bf8.png)

**Comment by hirurg-lybitel** [comment]
ошибка исправлена.
скоро скинем в общий доступ

**Comment by startkkc** [comment]
@alexandra-gsoftware окно заполнения бронирования не центрировано. Кнопки по внесению суммы предоплаты за пределами экрана. Разрешение 1024х768.

**Comment by hirurg-lybitel** [comment]
> @alexandra-gsoftware окно заполнения бронирования не центрировано. Кнопки по внесению суммы предоплаты за пределами экрана. Разрешение 1024х768.

fixed

**Comment by hirurg-lybitel** [comment]
@MesnikRoman на форме Раздедить блюдо (usrf_mn_DevideCourse_touch) не работает точка на клавиатуре

**Comment by startkkc** [comment]
В константах, **логотипе** чтобы было по-умолчанию = 1, и **использовать СКНО** = 1

**Comment by hirurg-lybitel** [comment]
> В константах, **логотипе** чтобы было по-умолчанию = 2, и **использовать СКНО** = 1

Сделано

**Comment by startkkc** [comment]
В дискрипторы  фискального регистратора при открытии смены вносятся не верные виды оплаты. В кредит - О!плати
![image](https://user-images.githubusercontent.com/17782689/74446704-57dfeb00-4e89-11ea-9d8e-6a8fe1a0b4fe.png)

**Comment by startkkc** [comment]
ПО не даёт создать разные настройки для двух ФР в одной БД. Т.е. если я в одном ФР указал com3 и пароль 111111, а на второй com4 и пароль 111111, то если зайти в настройки первого ФР там будет com4 и 111111, как будто единая таблица используется.
![image](https://user-images.githubusercontent.com/17782689/75037849-29d05b80-54c6-11ea-9fb6-a5303868e932.png)
![image](https://user-images.githubusercontent.com/17782689/75037911-453b6680-54c6-11ea-91fb-e83a26f20134.png)

**Comment by alexandra-gsoftware** [comment]
можно сделать, чтобы настройки фр хранились не в хранилище, а в блоб-поле в таблице USR$MN_POINTOFSALESET (в формате xml или json)
@hirurg-lybitel , что скажешь?

**Comment by hirurg-lybitel** [comment]
Я бы так не усложнял.
Отдельный путь в том же хранилище для каждого типа оборудования.

**Comment by hirurg-lybitel** [comment]
@alexandra-gsoftware 

![image](https://user-images.githubusercontent.com/11502258/75987100-62c5f280-5f00-11ea-97e1-29dfe5aa3d1d.png)

**Comment by alexandra-gsoftware** [comment]
А ты ПИ со Спарком ставил?

**Comment by hirurg-lybitel** [comment]
да

![image](https://user-images.githubusercontent.com/11502258/75989776-eaadfb80-5f04-11ea-9d69-79ff16b039b0.png)

**Comment by alexandra-gsoftware** [comment]
это мастер или кэш?

**Comment by alexandra-gsoftware** [comment]
@hirurg-lybitel вроде во всех ветках лежит правильный класс спарка, может, он у тебя все-таки не обновился?

**Comment by hirurg-lybitel** [comment]
@alexandra-gsoftware версия на скрине. Ветка **cash**

**Comment by alexandra-gsoftware** [comment]
@hirurg-lybitel а какой md5 у ПИ спарк?
должен быть 42CE397245F84C0C6E32C7320E0B5422, вот сам файл https://github.com/GoldenSoftwareLtd/gedemin-apps/blob/70661c134a79854259449b1efacbdfd7eda05a33/%D0%A2%D0%BE%D1%80%D0%B3%D0%BE%D0%B2%D0%BE%D0%B5%20%D0%BE%D0%B1%D0%BE%D1%80%D1%83%D0%B4%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5/GS.%D0%A2%D0%BE%D1%80%D0%B3%D0%BE%D0%B2%D0%BE%D0%B5%20%D0%BE%D0%B1%D0%BE%D1%80%D1%83%D0%B4%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5.%D0%A4%D0%A0.%D0%A1%D0%BF%D0%B0%D1%80%D0%BA.yml

**Comment by hirurg-lybitel** [comment]
@alexandra-gsoftware так а причём тут спарк? этот же атрибут для всех классов вызвается.
Вероятно у одного из них его нет.

**Comment by alexandra-gsoftware** [comment]
Вызывается только у класса, который выбран в качестве фр для компа. Если это спарк - то спарк. Или какой фр выбран?

**Comment by hirurg-lybitel** [comment]
Не знаю. Вероятно был выбран какой-то другой, у которого такого атрибута нет.

**Comment by startkkc** [comment]
2 терминала и 1 фискальник. При заказе с терминала у которого нет ФР (служба ФР) появляется ошибка.
![Безымянный1243](https://user-images.githubusercontent.com/17782689/77540562-58ba6280-6eb4-11ea-8489-1ff8cddd95ba.png)

**Comment by startkkc** [comment]
@alexandra-gsoftware После обновления ПИ, не сохраняет изменение в номере ком порта.
![image](https://user-images.githubusercontent.com/17782689/78554427-d0bd4c80-7813-11ea-94d2-01933f403f14.png)

**Comment by alexandra-gsoftware** [comment]
@startkkc 
в смысле, вы открываете на редактирование, пытаетесь поменять, сохраняете, открываете, а значение прежнее? А что на страничке Настройки?

**Comment by startkkc** [comment]
@alexandra-gsoftware я нажимаю параметры, меняю номер порта ОК, ОК, Переподключаюсь номер ком порта старый
![image](https://user-images.githubusercontent.com/17782689/78898078-e16ffb80-7a7b-11ea-89bc-d26bbe55719f.png)

**Comment by startkkc** [comment]
@alexandra-gsoftware Можно что-то сделать с журналом действий, он очень медленно работает, и в нем тяжело что-то найти.

**Comment by alexandra-gsoftware** [comment]
>>>я нажимаю параметры, меняю номер порта ОК, ОК, Переподключаюсь номер ком порта старый

Вы собирали чистую БД из ПИ?

**Comment by startkkc** [comment]
> > > > я нажимаю параметры, меняю номер порта ОК, ОК, Переподключаюсь номер ком порта старый
> 
> Вы собирали чистую БД из ПИ?

Обновлял ранее установленную БД с сайта. Я её актуализирую свежими ПИ для теста.

**Comment by alexandra-gsoftware** [comment]
@startkkc возьмите сейчас обновления

**Comment by startkkc** [comment]
> @startkkc возьмите сейчас обновления

Ок спасибо. @alexandra-gsoftware можно попросить тебя, если что-то исправлено по issue, чтобы я видел, что можно качать новые ПИ и актуализировать БД. Интересует пару вопросов назад было "2 терминала и 1 фискальник. При заказе с терминала у которого нет ФР (служба ФР) появляется ошибка"

**Comment by alexandra-gsoftware** [comment]
В этих коммитах было следующее:
1) изменение хранения параметров ФР. Была проблема, что на одной базе хранятся несколько ФР с разными компьютерами, и у них перетирались параметры
2) та ошибка со службой Спарк
3) переделан контроль , когда ФР сам перепечатывает чек. По идее, сейчас этот контроль должен работать, даже если эл-во вырубилось, или гедымин закрыли и запустили заново
4) изменеия по отчетам какие-то (это Юра делал)

**Comment by startkkc** [comment]
- не оплачивается чек, по счетчика все ок
![image](https://user-images.githubusercontent.com/17782689/78989887-8b638c80-7b3d-11ea-9205-886790ae5eed.png)
- кнопка оплаты не активна, пока не распечатаешь предчек. Заказ и сразу оплата (быстрый чек)
![image](https://user-images.githubusercontent.com/17782689/78989993-dc738080-7b3d-11ea-9a96-47943450e809.png)

**Comment by alexandra-gsoftware** [comment]
Illegal command - исправила
кнопка оплаты не активна, пока не распечатаешь предчек. Заказ и сразу оплата (быстрый чек) - в белгиссе сказали, что нельзя закрывать заказ без пречека, если включены счетчики заказов. В стб то же самое написано :-(
по службе фр буду смотреть

**Comment by startkkc** [comment]
@alexandra-gsoftware Есть что проверять?

**Comment by alexandra-gsoftware** [comment]
@startkkc сделала, пока проверяю сама. Работает, но медленно. Смотрю, что можно ускорить

**Comment by alexandra-gsoftware** [comment]
вот этот коммит. завтра его должны подтвердить https://github.com/GoldenSoftwareLtd/gedemin-apps/pull/1094

Пока что все равно медленно.  Есть еще один баг, что при печати с удаленного компа на компе с фр может перебиться официант на удаленного (это завтра исправлю)

**Comment by startkkc** [comment]
> вот этот коммит. завтра его должны подтвердить [GoldenSoftwareLtd/gedemin-apps#1094](https://github.com/GoldenSoftwareLtd/gedemin-apps/pull/1094)
> 
> Пока что все равно медленно. Есть еще один баг, что при печати с удаленного компа на компе с фр может перебиться официант на удаленного (это завтра исправлю)

Спасибо, жду отмашку на проверку

**Comment by alexandra-gsoftware** [comment]
Изменения уде в мастере

**Comment by startkkc** [comment]
обновил 17.04.2020 ПИ. При заказе с терминала у которого нет ФР (служба ФР), на терминале у которого ФР появляется данное сообщение:
![image](https://user-images.githubusercontent.com/17782689/79576228-9f723580-80cb-11ea-9b9f-44045bc40f10.png)
![image](https://user-images.githubusercontent.com/17782689/79576241-a436e980-80cb-11ea-811e-e7cb685a3394.png)

**Comment by alexandra-gsoftware** [comment]
https://github.com/GoldenSoftwareLtd/gedemin-apps/pull/1099
исправила

**Comment by startkkc** [comment]
@hirurg-lybitel при отправке на печать с применением КУРСОВ, печатается все в одном сервис чеке без разбиения.

**Comment by yoannawx** [comment]
какая модель сервис-принтера?

**Comment by startkkc** [comment]
> какая модель сервис-принтера?
sinocan (fast-report), там принтер не стандартный (не стыковались) но предчеки и сервис чеки выходят

**Comment by startkkc** [comment]
@hirurg-lybitel Добрый день. Снова появилась проблема, она уже была раньше её правили и снова здравствуйте. Делается заказ и нажимается предчек, заказ ИСЧЕЗАЕТ ДЛЯ ДАННОГО ТЕРМИНАЛА, т.к. ему не проставляется номер фискальника.

**Comment by startkkc** [comment]
@alexandra-gsoftware Возвращаемся к службе ФР. С терминала, у которого нет ФР (Служба ФР) x-отчет печатается, а при отправке в производство пишет "Фискальный регистратор не подключен!"

**Comment by alexandra-gsoftware** [comment]
@startkkc в смысле, х работает, а отправка в производство - нет?

**Comment by startkkc** [comment]
> @startkkc в смысле, х работает, а отправка в производство - нет?

Да, со второго терминала (где нет ФР) я могу зайти в КАССА и снять x-отчет (связь с ФР есть), но при отправке в производство выдает сообщение "Фискальный регистратор не подключен!"

**Comment by alexandra-gsoftware** [comment]
@startkkc счетчики заказов включены? Можно проверить с отключенными?

**Comment by startkkc** [comment]
@alexandra-gsoftware когда счётчики включены - не работает. Когда счетчики выключены - работает.

**Comment by alexandra-gsoftware** [comment]
а это работало 2 месяца назад, ілі нет?

**Comment by startkkc** [comment]
@alexandra-gsoftware Столик имеет специфический номер, с терминала у которого ФР счёт распечатался, а вот к у которого служба дал такое сообщение. Может стоит запретить какие-то символы в названиях столика или выяснить в чем проблема.
![image](https://user-images.githubusercontent.com/17782689/84906953-4880e080-b0bb-11ea-9623-202e422c968e.png)
![image](https://user-images.githubusercontent.com/17782689/84906993-520a4880-b0bb-11ea-942d-02f76e328f2f.png)
![image](https://user-images.githubusercontent.com/17782689/84907369-c513bf00-b0bb-11ea-9a22-a522bdfce37a.png)

**Comment by alexandra-gsoftware** [comment]
@startkkc  Добавила конвертацию номера столика в строку.

**Comment by startkkc** [comment]
> В отправленном на производство заказе, удалить более одной позиции приводит к ошибке. Счетчик заказов включён.
> При удалении более одной позиции
> ![image](https://user-images.githubusercontent.com/17782689/72904404-e6a49080-3d3f-11ea-83b1-4dd1c86b5df1.png)

@alexandra-gsoftware Добрый день. Обновил последними ПИ, старая ошибка появляется.

**Comment by startkkc** [comment]
@alexandra-gsoftware 2 терминала и 2 ФР. 1) делаю заказ на одном терминале, 2) делаю заказ на втором терминале, 3) делаю "перенос на существующий столик" всего заказа ( доступны все заказы вне зависимости где были созданы). 5) пишет "Недопустимая команда" Заказы перенеслись, а счетчик остался без изменения.

**Comment by startkkc** [comment]
@alexandra-gsoftware добрый день. Делали что-нибудь?

**Comment by hirurg-lybitel** [comment]
Что-то делали, но пока отследить причины проблемы не удаётся.
