### ISSUE TITLE
Авансы и сертификаты в скно

### ISSUE THREAD

**Issue by hirurg-lybitel** [gsbelarus/check-and-cash#236]
Появились новые регистры с скно

[Письмо о реализации авансовых платежей.pdf](https://github.com/gsbelarus/check-and-cash/files/4034598/default.pdf)

**Comment by hirurg-lybitel** [comment]
@startkkc нам надо прошивку новую на скно поставить?

**Comment by startkkc** [comment]
@hirurg-lybitel прошивку ставить не надо.

**Comment by hirurg-lybitel** [comment]
т.е. просто при продаже сертификата/аванса передаём специальные коды gtin? 
больше никакиз изменений не требуется?

**Comment by startkkc** [comment]
@hirurg-lybitel там все написано.

**Comment by startkkc** [comment]
@hirurg-lybitel Заказы, которые используют предоплату (авансы), должны закрываться на счетчик Авансы + остальная сумма (другой способ оплаты). Точно такое же сейчас с сертификатами.
![image](https://user-images.githubusercontent.com/17782689/72966106-1a7ac700-3dcf-11ea-82f1-233a4d97f148.png)

**Comment by startkkc** [comment]
@alexandra-gsoftware что-нибудь готово по этой задаче?

**Comment by hirurg-lybitel** [comment]
всё готово и в мастере лежит
