### ISSUE TITLE
Импорт большого объема карт

### ISSUE THREAD

**Issue by startkkc** [gsbelarus/check-and-cash#238]
Добрый день. Появилась заявка от клиента на загрузку 2млн карт (Моцная карта) в бонусную систему. DBF файл я сделал. Существующим импортом у меня файл с 1млн карт грузится уже 4 сутки (железо обычная касса), и загрузилось всего 500к. Есть ли альтернативный способ эти карты импортировать.

**Comment by hirurg-lybitel** [comment]
Добрый день.
Файл бы получить

**Comment by startkkc** [comment]
> Добрый день.
> Файл бы получить

Отправил на почту

**Comment by hirurg-lybitel** [comment]
Сложность загрузки такого большого объёма данных растёт в геометрической прогрессии, так что пока вижу два варианта:

- разбить файл на более мелкие, например, по 10 000;
- создать карты сразу на базе через какой-нибудь макрос

**Comment by startkkc** [comment]
Пока задача стоит в том, как будет работать база с 2млн карт. Создай их через макрос. По 10к карт  уже будем грузить клиенту.

**Comment by hirurg-lybitel** [comment]
скинул всё в личном сообщении

**Comment by hirurg-lybitel** [comment]
@startkkc  Вопрос актуален?

**Comment by startkkc** [comment]
@hirurg-lybitel не нашел времени протестить. Пока закрываю.
