### ISSUE TITLE
Спец питание

### ISSUE THREAD

**Issue by startkkc** [gsbelarus/check-and-cash#239]
Добрый день. Можно ли в Positive Check провести более чем 1 спец питание в день?

**Comment by hirurg-lybitel** [comment]
Добрый день. В стандартном решении Positive Check провести более чем 1 спец. питание в день нельзя.

**Comment by startkkc** [comment]
@stasgm какой-то клиент просил такое сделать, может осталась настройка

**Comment by stasgm** [comment]
@startkkc если будет известно какому клиенту уже делали, то может найду доработку. А пока говорить, что платная доработка.

**Comment by startkkc** [comment]
@stasgm это можешь сказать только ты, какому клиенту делали. Клиенту сообщил, задачу закрываю.
