### ISSUE TITLE
Отчет по отказам

### ISSUE THREAD

**Issue by gsbelarus** [gsbelarus/check-and-cash#24]
Отчет по отказам - при попытке просмотреть - пустой отчет с заголовком, начальная дата в заголовке - дата окончания периода, которая задавалась в форме отчета, конечная дата в  заголовке - 30.04.2006 г. (см. скрин). Это отчет по отменам предчека, возвратам или отказам от бронирования? Нужен отчет по отменам предчека и др. опасным операциям (может он есть, но я не нашел), где можно было бы посмотреть все отмены/возвраты за день/период и причины отмен.
![fail](https://cloud.githubusercontent.com/assets/20344214/16867923/5980de9c-4a7d-11e6-8c39-290cd352af0b.jpg)

**Comment by stasgm** [comment]
Исправлено.
