### ISSUE TITLE
Сводный отчёт Check

### ISSUE THREAD

**Issue by startkkc** [gsbelarus/check-and-cash#240]
При построении сводного отчёта, когда был использован аванс, появляется большие минусы по блюдам и деньгам, и блюдо Аванс.

**Comment by startkkc** [comment]
@stasgm пока решил данную проблему установкой старого сводного отчёта.

**Comment by hirurg-lybitel** [comment]
@startkkc не получилось воспроизвести.

Что-то не так сделал?

![image](https://user-images.githubusercontent.com/11502258/76568883-e1073380-64c2-11ea-8879-91032afe7b03.png)

![image](https://user-images.githubusercontent.com/11502258/76568893-e6647e00-64c2-11ea-9347-47aebb99450b.png)

**Comment by startkkc** [comment]
@hirurg-lybitel Внес авансовую оплату на 100р, а использовал в этот же день другой аванс на 150р,
![image](https://user-images.githubusercontent.com/17782689/76755849-aab50700-6795-11ea-8397-5d245ecf0d6e.png)
![image](https://user-images.githubusercontent.com/17782689/76756212-58c0b100-6796-11ea-953a-ee0ac8f48148.png)

**Comment by hirurg-lybitel** [comment]
попробуйте обновить ПИ GS.PositiveCheck. Отчёты

**Comment by startkkc** [comment]
проверено, все ок
