### ISSUE TITLE
Новая форма оплат в cash: особые типы оплаты попадают в Наличные

### ISSUE THREAD

**Issue by alexandra-gsoftware** [gsbelarus/check-and-cash#242]
Если в чеке не выбрать аванс или сертификат, но выбраны эти типы оплаты в формочке оплаты, соответствующие поля в шапке чека не заполнятся

Надо или не отображать эти виды оплаты, или заполнять поля в шапке, даже если сертификат не выбран

**Comment by hirurg-lybitel** [comment]
никогда и нельзя было

**Comment by alexandra-gsoftware** [comment]
сейчас это легко ввести из формы - значит, будет баг
