### ISSUE TITLE
Неправильно строится кассовый отчёт

### ISSUE THREAD

**Issue by supportkkc** [gsbelarus/check-and-cash#244]
Неправильно строится кассовый отчёт в PositiveCheck
![2](https://user-images.githubusercontent.com/20512230/75012207-96c9fe00-5492-11ea-84a9-4d14b578db0f.JPG)
![Кассовый отчёт](https://user-images.githubusercontent.com/20512230/75012209-97fb2b00-5492-11ea-91b4-4677b301c80d.JPG)
Если нужна БД - скажите кому выслать.

**Comment by hirurg-lybitel** [comment]
Уверены, что все подразделения указали?
Возможно, какое-нибудь одно блюдо в меню числится на другом подразделении.
