### ISSUE TITLE
Разработать Кассовый отчет для Cash

### ISSUE THREAD

**Issue by yoannawx** [gsbelarus/check-and-cash#245]
Нужен Кассовый отчет для Cash по аналогии с Кассовым отчетом в Check, такой же формы, который бы показывал выручку по кассам в разрезе подразделений. 
т.е. Необходимо, чтобы выручка разбивалась по видам оплаты в разрезе подразделений. Ссылка на подразделение есть в позиции чека, суммы по видам оплаты - в шапке чека.
Отчет добавить в папку Отчеты - Стандартные: на кассовом сервере и на форме удаленного просмотра в бэке.
Параметры: период, подразделения (множественный выбор)

![image](https://user-images.githubusercontent.com/11497358/77535294-72a37780-6eab-11ea-9a7a-a606d2a9765f.png)

**Comment by hirurg-lybitel** [comment]
@yoannawx 
Здравствуйте.
Проверьте отчёт на кассовом сервере. 
Закрепим и перенесём на бэк.

**Comment by hirurg-lybitel** [comment]
@yoannawx 
Можно проверять обновлённую версию

**Comment by yoannawx** [comment]
проверено на рабочей базе. можешь делать для формы удаленного просмотра

**Comment by hirurg-lybitel** [comment]
@yoannawx проверяй

**Comment by yoannawx** [comment]
проверила на рабочей базе, где на одной кассе 2 подразделения. все ок.
при случае надо будет проверить на рабочей базе, где несколько касс и у каждой кассы одно подразделение

**Comment by startkkc** [comment]
@yoannawx @hirurg-lybitel Можно ли данный отчет перенести на КС Cash?

**Comment by yoannawx** [comment]
нужно

**Comment by hirurg-lybitel** [comment]
@startkkc @yoannawx  Этот отчёт основан на разделении товаров по типам оплат.  Конкретно под нал/карта. Таким образом он решает конретную задачу.

Сделать такой адекватный отчёт по всем типам оплат невозможно, так как в программу не заложена аналитика товаров в таком разрезе.
