### ISSUE TITLE
Медленно печатает ФР Спарк-115ТФ (Cash)

### ISSUE THREAD

**Issue by startkkc** [gsbelarus/check-and-cash#248]
Добрый день. У клиента есть проблема, очень медленно печатается чек из ФР. Производили следующие действия: обновили БД, почистили БД, ставили подменный ФР, меняли системный блок. Все эти действия не помогли. На объекте 2 кассы, одна печатает нормально, и эта проблемная. Делал копию БД нормальной кассы, чистил и устанавливал на проблемную, помогло на 2-3 недели. Сейчас снова печатает медленно.

**Comment by startkkc** [comment]
После обновления ПИ скорость значительно возросла.

**Comment by hirurg-lybitel** [comment]
То есть закрывать можно?

**Comment by startkkc** [comment]
Если это будет в основных ПИ Cash и Check то да, можно закрывать
