### ISSUE TITLE
Медленно строится сводный отчет

### ISSUE THREAD

**Issue by startkkc** [gsbelarus/check-and-cash#249]
Positive Check. Медленно идет построение отчета. БД старая, обновил ПИ до последних, отчёт все так же строится долго. Сводной как пример, любой отчет строится медленно.

**Comment by startkkc** [comment]
Всем доброго дня. Кто-то возьмется за данный вопрос? 16 дней прошло

**Comment by startkkc** [comment]
@stasgm @hirurg-lybitel @yoannawx @MesnikRoman @alexandra-gsoftware кому переслать БД для решения данного вопроса

**Comment by alexandra-gsoftware** [comment]
Я могу завтра глянуть, а откуда этот отчет вызывается?

**Comment by startkkc** [comment]
@alexandra-gsoftware Теперь строится быстро, спасибо
