### ISSUE TITLE
отчеты по ФР

### ISSUE THREAD

**Issue by startkkc** [gsbelarus/check-and-cash#251]
Positive Check. Обнаружили проблему в отчётах по ФР "Отчет по спец.питанию". Если поставить подменный ФР, и распечатать этот отчёт, он тянет не только спец питание пробитое по данному ФР, но и старые данные. Предположительно из-за совпадения номера смены фискальных регистраторов.

**Comment by hirurg-lybitel** [comment]
Обновить ПИ **GS.PositiveCheck. Term. Формы. Касса. Отчеты** после того, как [тут](https://github.com/GoldenSoftwareLtd/gedemin-apps/pull/1428) добавят эту доработку
