### ISSUE TITLE
Отчет по секциям

### ISSUE THREAD

**Issue by startkkc** [gsbelarus/check-and-cash#256]
Check, сеть столовых. При построении отчета по секциям за определенную дату происходило зацикливание и отчёт не строился.

**Comment by startkkc** [comment]
@alexandra-gsoftware помогла решить этот вопрос, отключив кое-что. На сколько это важно, не известно. Нужно мнение экспертов, кто писал доработку.

**Comment by hirurg-lybitel** [comment]
Зависит от того, что было сделано.

**Comment by startkkc** [comment]
@hirurg-lybitel узнай у @alexandra-gsoftware , она  27го будет доступна.

**Comment by hirurg-lybitel** [comment]
@alexandra-gsoftware ну так что там?

**Comment by alexandra-gsoftware** [comment]
Я сделала только для одной кассы. Там есть кросс таблица, которая связывает позиции меню и типы оплаты. В отчете она привязывалась и множила записи, получался бесконечный цикл. Я убрала ее из запроса. Зачем эта таблица - не знаю. Наверно, доя чего-то нужна.

**Comment by hirurg-lybitel** [comment]
@alexandra-gsoftware а как таблица называется? что-то нв эталоне такого не нахожу в отчёте этом

**Comment by alexandra-gsoftware** [comment]
Там своя какая-то таблица была. Надо к ним подулючаться и смотреть

**Comment by hirurg-lybitel** [comment]
тогда ждём данных для подключения или бд
