### ISSUE TITLE
Выгрузка чеков DBF

### ISSUE THREAD

**Issue by startkkc** [gsbelarus/check-and-cash#257]
CASH. После обновления ПИ. В файле выгрузки чеков, у чеков возвратов отсутствует каким видом оплаты был произведен возврат. У всех полей нули.
![image](https://user-images.githubusercontent.com/17782689/104810875-c1d6e200-5808-11eb-9fd9-859ff5e4fbc0.png)

**Comment by hirurg-lybitel** [comment]
Такой проблемы не замечено на эталоне.
Нужная конкретная база с конкретным примером для проверки.

**Comment by startkkc** [comment]
Отправил на почту

**Comment by hirurg-lybitel** [comment]
Обновить ПИ **GS.PositiveCash.Общее.Глобальные макросы**

**Comment by startkkc** [comment]
Обновил ПИ для кассы и КС на всякий случай. В выгрузке один возврат по безналу, в файле он в наличке.

![image](https://user-images.githubusercontent.com/17782689/105974381-e2235e00-609e-11eb-904f-c906651e969b.png)
![image](https://user-images.githubusercontent.com/17782689/105974477-fff0c300-609e-11eb-8b60-c08ec2396993.png)

**Comment by hirurg-lybitel** [comment]
> Обновил ПИ для кассы и КС на всякий случай. В выгрузке один возврат по безналу, в файле он в наличке.
> 
> ![image](https://user-images.githubusercontent.com/17782689/105975422-00d62480-60a0-11eb-957f-b7e17bbad436.png)
> 
> ![image](https://user-images.githubusercontent.com/17782689/105975550-206d4d00-60a0-11eb-88cd-547032d3095b.png)
> 
> 
> 
> 
> 
> 
После обновления новые чеки пробили?

**Comment by startkkc** [comment]
> > Обновил ПИ для кассы и КС на всякий случай. В выгрузке один возврат по безналу, в файле он в наличке.
> > ![image](https://user-images.githubusercontent.com/17782689/105975422-00d62480-60a0-11eb-957f-b7e17bbad436.png)
> > ![image](https://user-images.githubusercontent.com/17782689/105975550-206d4d00-60a0-11eb-88cd-547032d3095b.png)
> 
> После обновления новые чеки пробили?

Да, пробил новые чеки.

**Comment by hirurg-lybitel** [comment]
Обновить на сервере ПИ **GS.PositiveCash.CashServer.Синхронизация.Макросы**

**Comment by startkkc** [comment]
Проверил, все отлично, спасибо
