### ISSUE TITLE
gedemin control center

### ISSUE THREAD

**Issue by startkkc** [gsbelarus/check-and-cash#258]
Positive Cash. После оплаты, окно gedemin control center выходит на передний план. У двоих клиентов появилась данная проблема, предположительно после добавления нового пользователя. Версии программы у клиентов разные.
![изображение_viber_2021-01-25_10-50-52](https://user-images.githubusercontent.com/17782689/105701722-cb083300-5f1b-11eb-9d00-68d22ff18bd1.jpg)
![d19e0887-1a43-47de-992a-443687519acf](https://user-images.githubusercontent.com/17782689/105701790-e6733e00-5f1b-11eb-8e8e-36ef8e1fb10d.jpg)

**Comment by hirurg-lybitel** [comment]
а в логе синхронизации что-нибудь есть интересное на эту тему?

**Comment by startkkc** [comment]
Очистил лог, больше на передний план не переходит.
