### ISSUE TITLE
Не верная аннулирования сумма

### ISSUE THREAD

**Issue by startkkc** [gsbelarus/check-and-cash#259]
Cash, произвели аннулирование чека продажи. Чек аннулирования получился на 0.01 меньше чем чек продажи.

**Comment by hirurg-lybitel** [comment]
Судя по логам, в фр была передана корректная сумма. Теперь ждём комментария разработчика

**Comment by startkkc** [comment]
Сотрудник ККС, проверил работу аннулирования в ФР. Такой сбой был единичный, за все время работы жалоб не было. В HL логе сумма одна, в LL логе сумма на копейку меньше. Задачу закрываем
