### ISSUE TITLE
Сканер штрих-кода

### ISSUE THREAD

**Issue by startkkc** [gsbelarus/check-and-cash#260]
В Check и Cash используется сканер штрих-кода. В Cash настраивать его не надо, а в Check надо.
![image](https://user-images.githubusercontent.com/17782689/112480818-705a4e80-8d87-11eb-8d36-7db46ad2d8ff.png)
В Check в режиме ресторана и кафе есть кнопка поиск товара по штрих-коду, в режиме столовая её НЕТ (чаще сканера стоят в столовой). Варианты решения 1)Кнопку штрих-код добавить в режим столовой, 2) сделать возможным без нажатия этой кнопки проводить штрих-код, и ПО будет искать товар.

**Comment by hirurg-lybitel** [comment]
Добавили кнопку поиска по ШК на главное окно.

**Comment by supportkkc** [comment]
POSitive Check , обновил ПИ (от18.05.21), в режиме столовой нет формы штрихкодирования.
![нет скан шк](https://user-images.githubusercontent.com/20512230/118617591-725eed80-b7cb-11eb-806b-93dd1420ac22.jpg)

**Comment by hirurg-lybitel** [comment]
В эталон это ПИ ещё не выгружали

**Comment by startkkc** [comment]
в эталоне появилась, спасибо
