### ISSUE TITLE
Автозадача  БКП

### ISSUE THREAD

**Issue by startkkc** [gsbelarus/check-and-cash#262]
Можно ли использовать автозадачу по Архивированию БД и делать контроль по кол-ву хранимых БКПов, т.к. столкнулись с проблемой переполнения хранилища.

**Comment by hirurg-lybitel** [comment]
Да, можно. Соотвествующий скрипт был выслан.
Пользовательского интерфейса для настройки данного механизма не имеется на данный момент.

**Comment by startkkc** [comment]
Спасибо, буду тестировать.
