### ISSUE TITLE
Отрицательное значение в оплатах

### ISSUE THREAD

**Issue by supportkkc** [gsbelarus/check-and-cash#263]
@hirurg-lybitel Positive Check, у клиента в оплатах(столбец сумма) отрицательное значение на некоторых заказах. Такое происходит периодически. К примеру 02.03.21 есть две такие оплаты. -2руб (в 11:21:03) и -11,7руб. (в 15:48:41). Возвраты и аннулирования в этот день отсутствовали. Хотелось бы выяснить причину возникновения данной проблемы и возможность ее как-то исправить. Спасибо

**Comment by hirurg-lybitel** [comment]
Не получаетс воспроизвести такую проблему. Нужна ваша помощь в этом вопросе
