### ISSUE TITLE
Накопительные карты

### ISSUE THREAD

**Issue by startkkc** [gsbelarus/check-and-cash#268]
В Cash, если настроить шаги в накопительных картах  1% - 100р, 2% - 200р. 5% - 500р. Если я с первого же раза совершу покупку на более 500р, то у меня сразу применится 5%, хотя в накоплениях у меня было ноль. Я считаю, что скидка должна примениться уже со второй покупки этой картой, а не сразу.

**Comment by hirurg-lybitel** [comment]
Ну вроде все эти годы так работали.
Точно так стоит делать?

**Comment by startkkc** [comment]
Да) так и работало. Ими вроде пользовалось пару человек и шаги там были наверное большие, люди не замечали такой фишки как и я. + фидбэк от клиента пришел, что так точно работать не может. Еще ничего не купил, а тебе идет скидка сразу.

**Comment by hirurg-lybitel** [comment]
Ну хорошо. Сделаем.

**Comment by startkkc** [comment]
@hirurg-lybitel еще не готово?

**Comment by hirurg-lybitel** [comment]
Готово. [Ждём добавление](https://github.com/GoldenSoftwareLtd/gedemin-apps/pull/1597) в эталон
