### ISSUE TITLE
Закрыть систему

### ISSUE THREAD

**Issue by gsbelarus** [gsbelarus/check-and-cash#27]
В форме фронта "Касса" есть кнопки "открыть систему" и " закрыть систему", в форме "Менеджер" - "открыть день" и "закрыть день". 

Если закрыть систему (предпологается закрытие смены) с помощью кнопки "закрыть систему", то Спарк затем не может открыть день (возможно, частный случай, но уже случалось несколько раз).

**Comment by stasgm** [comment]
Вот так настраивается запрос пароля
![image](https://cloud.githubusercontent.com/assets/8355925/16957890/f6386356-4de6-11e6-9fab-778010110213.png)
Я добавлю ещё вопрос к операции"Закрыть программу?"
