### ISSUE TITLE
Кодировка вместо букв

### ISSUE THREAD

**Issue by startkkc** [gsbelarus/check-and-cash#270]
В работе ПО вместо букв кодировка, системный язык перевели на русский - не помогло.
![изображение_viber_2021-06-22_13-43-29](https://user-images.githubusercontent.com/17782689/123545045-e1324d80-d75e-11eb-83d5-b50f455c5ed2.jpg)

**Comment by gsbelarus** [comment]
а что за операционная система?

нд, 27 чэр 2021, 15:47 карыстальнік system engineer <
***@***.***> напісаў:

**Comment by startkkc** [comment]
@gsbelarus отправил Вам на почту

**Comment by startkkc** [comment]
@gsbelarus рекомендации из письма не помогли

**Comment by startkkc** [comment]
Добрый день, @gsbelarus. Есть какая информация по кодировке?

**Comment by gsbelarus** [comment]
завтра скажу. попросил человека установить на чистый комп. завтра проверю.

**Comment by gsbelarus** [comment]
1. на сайте микрософт взял media creation tool и сделал инстоляционную флэшку для Windows 10 Pro. Язык интерфейса английский. Русский/белорусский вообще не ставил.
2. Установил на чистый ноут.
3. Установил Russian для non unicode programs.
4. Скачал Гедымин.
5. Установил, запустил. 

Подробности в [видео](https://drive.google.com/file/d/1d6-6nTtHTvoO4DI5C5-1Y-j1thrbgxy8/view?usp=sharing).

Проверяйте, может у вас в домене заданы какие Group Policy по установке/использованию шрифтов.

**Comment by gsbelarus** [comment]
Если не будет получаться -- везите ноут. Установим винду чтобы работало.

**Comment by startkkc** [comment]
Добрый день, @gsbelarus. Отправил вопрос на почту от клиента. Спасибо

**Comment by gsbelarus** [comment]
Привозили ноуты, смотрели. Надо сделать следующее:

1. Сделать архивную копию БД
2. Заменить экзешник на бэке на [новейший](http://gsbelarus.com/pw/downloads/gedemin-platform/gedemin/)
3. Отключить всех пользователей, запустить экзешник и провести апгрейд структуры БД.
4. Работать с новым экзешником. Там проблемы нет со шрифтами.
5. На фронтах я не знаю. Можно не менять, так как у нас была в реестре какая-то модель фискальника с привязкой к конкретному номеру версии экзешника. Я не знаю у них та версия или нет.

**Comment by startkkc** [comment]
@gsbelarus Понял. У них нет ФР. Мы тогда поменяем exe где они работают с админкой. Там где фронт - оставим. Спасибо за помощь
