### ISSUE TITLE
Ошибка чтения бд

### ISSUE THREAD

**Issue by supportkkc** [gsbelarus/check-and-cash#273]
В отчётах из гедымина и x отчете, появились 50 коп наличных, хотя данное место работает, только по безналу, заказы сформировать удалось, но не удалось выяснить откуда 50 коп, при попытке посмотреть раздел оплат и фильтровки за нужное число возникает такая ошибка 
![IMG_20210822_125656](https://user-images.githubusercontent.com/20512230/130350973-684816d9-0dfa-4948-8e2a-01567d150c96.jpg)
![IMG_20210822_125732](https://user-images.githubusercontent.com/20512230/130351007-7981289b-ffcf-4b44-9ee9-d40f6d2a18d0.jpg)

**Comment by hirurg-lybitel** [comment]
База повреждена. 

Попробуйте её [восстановить](http://gsbelarus.com/gs/wiki/index.php/%D0%92%D0%BE%D1%81%D1%81%D1%82%D0%B0%D0%BD%D0%BE%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5_%D0%BF%D0%BE%D0%B2%D1%80%D0%B5%D0%B6%D0%B4%D0%B5%D0%BD%D0%BD%D0%BE%D0%B9_%D0%B1%D0%B0%D0%B7%D1%8B_%D0%B4%D0%B0%D0%BD%D0%BD%D1%8B%D1%85_Interbase_%D0%B8%D0%BB%D0%B8_Firebird)

**Comment by supportkkc** [comment]
Спасибо
