### ISSUE TITLE
Неверное отображения итоговой суммы на дисплее покупателя

### ISSUE THREAD

**Issue by supportkkc** [gsbelarus/check-and-cash#274]
При применении скидки на дисплее покупателя не отображается сумма со скидкой, отображается только сумма без скидки
![photo_2021-08-24_12-47-45](https://user-images.githubusercontent.com/20512230/130596854-a5c68531-3a5f-4b1f-b5bb-2c1c919ee985.jpg)

**Comment by hirurg-lybitel** [comment]
Дисплей нужен

**Comment by supportkkc** [comment]
Дисплей покупателя Spark-PD-2001.3U

**Comment by hirurg-lybitel** [comment]
Нужен физически дисплей, чтобы что-то на нём смотреть

**Comment by supportkkc** [comment]
Вам его нужно привезти?Дисплей есть PB-2600

**Comment by hirurg-lybitel** [comment]
а это одинаковые дисплеи?

нужно или на офис или удалённое подключение к дисплею с нормальной обратной связью.

**Comment by supportkkc** [comment]
Могу дать удаленку, сюда писать?

**Comment by hirurg-lybitel** [comment]
Нет. Пишите в объединённый чат ККС и Золотых программ
