### ISSUE TITLE
Предупреждение о превышении лимита для Гедымин-Кэша и Чека

### ISSUE THREAD

**Issue by yoannawx** [gsbelarus/check-and-cash#275]
При работе с картами сотрудников необходима следующая доработка: 
при оплате чека, в случае если остатка по лимиту не хватает для оплаты всего чека (либо остаток нулевой) необходимо выводить предупреждение о том, что лимит по карте исчерпан и остаток по чеку (либо всю сумму) придется оплатить другим типом оплаты.

**Comment by hirurg-lybitel** [comment]
а смешанный тип оплаты долже быть в принципе запрещён?

**Comment by yoannawx** [comment]
нет

**Comment by hirurg-lybitel** [comment]
тогда каким образом это должно работать?
какие ситуацию могут быть?
что ддолжно происходить псоле предупреждения? Полнйы запрет на оепрацию или на усмотрение кассира?

**Comment by yoannawx** [comment]
на усмотрение кассира. это мои клиенты просили.
но если делать по-хорошему, то лучше бы параметризировать: запрет или на усмотрение кассира

**Comment by hirurg-lybitel** [comment]
Так а чем не подходит обычный запрет на смешанный тип оплаты в таком случае?

**Comment by yoannawx** [comment]
потому что запрета нет, смешанный тип оплаты возможен. но кассиру должно выйти предупреждение, что он наступил, и ему надо проконтролировать, чтоб спросить с человека деньги.

**Comment by hirurg-lybitel** [comment]
Так без выбора другого типа оплаты оплата нет произойдёт и так ведь.

**Comment by yoannawx** [comment]
в том то и дело, что по умолчании не предлагается никакого выбора: программа сама закидывает остаток на нал, кассир не обращает внимания.
или есть какой-то параметр, чтоб был выбор?

**Comment by hirurg-lybitel** [comment]
Тогда, может, проще не закидывать остаток? Чтобы ничего нового городить

**Comment by yoannawx** [comment]
хороший вариант

**Comment by hirurg-lybitel** [comment]
проверяй

![image](https://user-images.githubusercontent.com/11502258/134591165-ac0c1fe5-07cc-40a2-8990-c277ee0b741d.png)

**Comment by hirurg-lybitel** [comment]
@yoannawx подходит?

**Comment by yoannawx** [comment]
если галка не установлено, что будет происходить при превышении / отсутствии лимита? предупреждение, что чек закрыть нельзя, потому что сумма не соответствует? при этом не должен быть доступен вид оплаты в кредит

**Comment by hirurg-lybitel** [comment]
лучше один раз проверить и увидеть ;)

**Comment by yoannawx** [comment]
а еще лучше проверить не один раз )))
я так поняла, пока есть решение только для кэша?

**Comment by gs7600300** [comment]
Нет души в этом решении. Нужно искать другой подход. Т.к. если эту галочку снять => кассир идёт вешаться. Т.к. при расчете чека подставляется 0 и нужно каждый раз вводить сумму вручную. При наличных проблем нет. Если банковский терминал не подключен -> вводи ручками.. в счет кредита и тд ...

**Comment by hirurg-lybitel** [comment]
Ну можете понакидывать своих идей.
