### ISSUE TITLE
Разработка механизма контроля максимальной суммы покупки товара со скидкой по дисконтным картам

### ISSUE THREAD

**Issue by yoannawx** [gsbelarus/check-and-cash#279]
Разработка для МХП. Но делать типовой вариант для дальнейшего включения в эталон.

1. Ежемесячно устанавливается сумма лимита для дисконтной карты.
2. В течение месяца из нее минусуются суммы всех покупок (только позиции с применением скидки!) по данной дисконтной карте.
3. Когда при расчете очередного чека оказывается, что сумма позиций со скидкой по данному чеку превышает остаток по лимиту - выдается предупреждение: "лимит по карте превышен. скидка не будет применена. остаток - ..."
4. Синхронизация данных по лимитам - через складскую бд.

**Comment by yoannawx** [comment]
не должна

**Comment by gs7600300** [comment]
Поступили изменения в ТЗ. Ограничивать нужно лимит не на сумму товаров со скидкой, а на  _сумму скидки_.

**Comment by hirurg-lybitel** [comment]
@yoannawx требуется проверка.

**Изменения в исследователе:**
 ![image](https://user-images.githubusercontent.com/11502258/144229255-7aeba3f0-ef32-4637-8b9a-be3ab9b0adf7.png)
 
**Изменения в документе лимитов:**
![image](https://user-images.githubusercontent.com/11502258/144229438-60bb1053-4151-42e6-b78c-7499007448a4.png)

**Примеры исключительных ситуаций:**
![image](https://user-images.githubusercontent.com/11502258/144230043-bfb047b8-bb0d-43d6-b7d0-24ad2f3bc7d6.png)

![image](https://user-images.githubusercontent.com/11502258/144230125-a4d5e35e-2f0a-45f3-a521-a161d76d4d0a.png)

**Comment by yoannawx** [comment]
в справочнике Дисконтные карты добавить макрос "Сформировать скидочные лимиты". В параметрах:
- сумма лимита,
- период действия,
- выбор: - для всех карт, - только для выделенных.
Создавать лимиты только для тех карт, к которым привязаны контакты. Если активный скидочный лимит для контакта уже существует, выдавать соответствующее сообщение и спрашивать, заменять ли.

**Comment by hirurg-lybitel** [comment]
а в какой ситуации модет понадобиться не заменять лимит?

**Comment by hirurg-lybitel** [comment]
а в какой ситуации может понадобиться не заменять лимит?

**Comment by hirurg-lybitel** [comment]
@yoannawx так что у нас тут?
