### ISSUE TITLE
Учет сертификатов на суммовых магазинах Волковысского мясокомбината.

### ISSUE THREAD

**Issue by yoannawx** [gsbelarus/check-and-cash#280]
1. Для каждого суммового магазина создать и настроить кассовый сервер.
2. На этом сервере настроить синхронизацию сертификатов со складской базой.
3. На этом сервере создать пользователя, которому доступны только сертификаты и чеки.
4. В макросах сертификатов создать макрос "Оплатить сертификатом". Параметры:
- выбор сертификата,
- дата оплаты,
- сумма оплаты сертификатом.
Макрос должен создавать чек с пустыми позициями, привязывать к нему ссылку на выбранный сертификат.
Дальше должно работать стандартное обновление сумм в данном сертификате и синхронизация данных со складом.

**Comment by hirurg-lybitel** [comment]
@gs7600300 какие-то комментарии будут?

**Comment by hirurg-lybitel** [comment]
- Нужно ли формировать чек или просто списываем сумму сертфиката?
- Если чек формируем, то должен ли он потом импортироваться в бэк?
- Если да, то какой твоар должке быть в чеке?

**Comment by gs7600300** [comment]
1) Нужно
2) Не должен
3) Товар не нужен

**Comment by gs7600300** [comment]
`На этом сервере создать пользователя, которому доступны только сертификаты и чеки.`
Предлагаю 2 варианта:
1) Форма удалённого просмотра - макрос;
2) Просто макрос и в параметрах бабушка выбирает КС где должен создаться чек;

По мне вариант 1 предпочтительнее.

**Comment by hirurg-lybitel** [comment]
можно проверять
