### ISSUE TITLE
Отчёт по продажа товара

### ISSUE THREAD

**Issue by hirurg-lybitel** [gsbelarus/check-and-cash#281]
В параметрах выбираем товар и период дат, в отчет выводится список чеков, в которых есть этот товар (дата, номер, время (из позиции для этого товара), цена, количество, сумма)

**Comment by yoannawx** [comment]
отчет делать на кассовом сервере

**Comment by hirurg-lybitel** [comment]
@yoannawx можно проверять

**Comment by yoannawx** [comment]
шапку отчета переносить на другие листы. 
сделать итоговое суммирование количества и суммы по каждому товару и в конце отчета.

**Comment by hirurg-lybitel** [comment]
@yoannawx больше изменений не требуется?

**Comment by yoannawx** [comment]
не требуется
