### ISSUE TITLE
Интеграция с API Titan Pos Mobile

### ISSUE THREAD

**Issue by hirurg-lybitel** [gsbelarus/check-and-cash#283]
Документация:
https://disk.yandex.ru/d/qu5pxnRS-XUuxQ

Описание API:
[Описание API TitanPosMobile.pdf](https://github.com/gsbelarus/check-and-cash/files/7738149/API.TitanPosMobile.pdf)

ПО:
https://vial.by/titan-pos/

**Comment by gs7600300** [comment]
Контактное лицо, которое предоставило инфо +375 (29) 570-55-55 Валерий

**Comment by hirurg-lybitel** [comment]
@gs7600300 что в итоге-то получилось?

**Comment by MIchaelShoihet** [comment]
Сделано. Теперь нужен клиент как я понимаю.
