### ISSUE TITLE
Отключение триггеров таблицы USR$PF_LOGSYNCHRPRICE

### ISSUE THREAD

**Issue by gs7600300** [gsbelarus/check-and-cash#287]
Триггеры: 
USR$PF_AI_LOGSYNCHRPRICE
USR$PF_AU_LOGSYNCHRPRICE
делают записи в не актуальную таблицу USR$PF_CASHLOG.
Данная таблица может хранить десятки миллионов не нужных записей.

**Comment by hirurg-lybitel** [comment]
Эт старые триггеры, которые не входят ни в какие ПИ. Соответсвенно, их можно просто удалить руками при обновлении. Либо же разворачивать базу из установочника, где их нет, и импортировать туда необходимые данные.
