### ISSUE TITLE
Баг обновления остатка в сертификатах

### ISSUE THREAD

**Issue by gs7600300** [gsbelarus/check-and-cash#290]
Со слов пациента: 
"Вводим товар, нажимает шифт Л , вводим номер, интер, и показывает сумму 50, а должно остаток 23.04
Отоварили на второй, часть оставшуюся хотим на номер Один
24 числа было
Мосты. Касса 2. 24 сентября рассчитались сертификатом на 26.96
Остаток не поменялся
Перед вводом  товара в чек ввели сертификат.
Касса 2 ip 192.168.15.4
![image](https://user-images.githubusercontent.com/13334057/192278604-c909f36c-8be4-48a1-97db-8a03de3e8ca0.png)
![image](https://user-images.githubusercontent.com/13334057/192278644-7b7b00cd-6f79-4c0d-abba-c2c4bba40667.png)
"

Как проблему понял я:
При выборе типа оплаты сертификатом(привязке сертификата к чеку) имеет значение в какой момент привязан сертификат (до ввода позиций чека или перед расчетом), хотя ожидаем, что разницы не должно быть..

**Comment by hirurg-lybitel** [comment]
Извиняюсь, что-то пропустил это ишью.
Тут такой момент, что механим сертификатов у данного клиента сильно отличается от нашего текущего, который уже решил многие пррблемы синхронизации сертификатов, в том числе и описанную.
Так что обновленеи должно решить эту проблему
