### ISSUE TITLE
Некорректная работа Денежного ящика

### ISSUE THREAD

**Issue by hirurg-lybitel** [gsbelarus/check-and-cash#293]
https://github.com/GoldenSoftwareLtd/gedemin/issues/4292

**Comment by hirurg-lybitel** [comment]
@supportkkc
как я понимаю, сейчас работает иначе немного

1. при открытии окна оплаты программой открывается денежный ящик 
2. при печати чека, в котором есть наличные (или другие типы оплаты с признаком _Денежный ящик_) он снова открывается уже фискальником, если был закрыт.

Кассиру явно требуется открытие ящика ДО момента начала печати чека.

Поэтому вопрос, а собственно что требуется? В какой момент открывать ДЯ?

**Comment by supportkkc** [comment]
Отключить открытие денежного ящика при вызове окна оплаты, в ином случае, настройки открытия денежного ящика по типам оплат являются бесполезным.

**Comment by hirurg-lybitel** [comment]
![image](https://user-images.githubusercontent.com/11502258/199980275-94617c5c-559e-458c-a020-65c97ab3f119.png)

**Comment by supportkkc** [comment]
Отлично, спасибо!
