### ISSUE TITLE
Работа с Банковским терминалом. POSitive Cash

### ISSUE THREAD

**Issue by supportkkc** [gsbelarus/check-and-cash#295]
В данный момент, доступ к операциям с банковским терминалом имеет только группа прав "Менеджер", добавьте пожалуйста такое разрешение и для группы прав "Старший кассир". Старший кассир при вызове команды shifr+ctrl+F10 (доп. операции), получает сообщение "Недостаточно прав".

**Comment by hirurg-lybitel** [comment]
Теперь настройка данной операции вынесена в _04. Права на действия_.
По умолчанию данные такие, как указано на картинке
![image](https://user-images.githubusercontent.com/11502258/232462120-d0b96e1f-fd10-410f-8030-5c739c0fced9.png)

**Comment by hirurg-lybitel** [comment]
После [данного пуллреквеста ](https://github.com/GoldenSoftwareLtd/gedemin-apps/pull/2475) обновления появятся в общем доступе.
