### ISSUE TITLE
Оплата в кредит для интеграла

### ISSUE THREAD

**Issue by supportkkc** [gsbelarus/check-and-cash#31]
На чеке не отображается информация о том кто оплатил в кредит. Настройку которую выслал Стас установил и активировал. Бэкап отправил Стасу.

**Comment by supportkkc** [comment]
После установки доработки выскакиевает ошибка. Заказ проходит по ФР но не закрывается.
![img_20160825_105044](https://cloud.githubusercontent.com/assets/20512230/18245288/08c82e6a-736d-11e6-975c-ff10319a66ad.jpg)
![img_20160825_105034](https://cloud.githubusercontent.com/assets/20512230/18245289/08cc1020-736d-11e6-958c-7a43c26a21c2.jpg)
![img_20160825_105039](https://cloud.githubusercontent.com/assets/20512230/18245287/08c6b378-736d-11e6-97e5-27afa0389bdc.jpg)

**Comment by stasgm** [comment]
@supportkkc проблема ещё актуальна?

**Comment by supportkkc** [comment]
@stasgm да.

**Comment by hirurg-lybitel** [comment]
@supportkkc так а как они сейчас работают тогда с такой проблемой???

**Comment by supportkkc** [comment]
Обычно, на бэкапе без доработки. 
Однако вопрос с питанием штата до сих пор не решен.

**Comment by stasgm** [comment]
@supportkkc а база хоть новая?

**Comment by supportkkc** [comment]
@stasgm Да, база после деноминации.

**Comment by supportkkc** [comment]
Оперативность, как всегда удивляет. Что с решением данной проблемы?

**Comment by hirurg-lybitel** [comment]
Её уже неделю как нет

**Comment by supportkkc** [comment]
Нет оперативности или проблемы?

**Comment by hirurg-lybitel** [comment]
Проблемы точно нет. 
Насчет оперативности ничего сказать не могу.

**Comment by stasgm** [comment]
Вопрос решён ещё на прошлой неделе. Напрямую с клиентом контактировали
