### ISSUE TITLE
Неправильно печатается ФИО кассира

### ISSUE THREAD

**Issue by gsbelarus** [gsbelarus/check-and-cash#32]
POSitive Cash - при печати X, Z-отчетов на чеке вместо Кассир - Иван Иванов, печатается Кассир - кассир. При этом на фискальных чеках оплаты данные кассира печатаются правильно.

**Comment by hirurg-lybitel** [comment]
Скачал версию с сайта. Проверил. Всё нормально печатается. 
Попробуйте просто обновить базу.
