### ISSUE TITLE
Виртуальный фискальный регистратор

### ISSUE THREAD

**Issue by gsbelarus** [gsbelarus/check-and-cash#33]
При попытке сделать возврат аванса ( в окне бронирования) в нефискальном режиме ошибка. - "Не установлен фискальный регистратор, система находится в нефискальном режиме."

Можно ли сделать некое подобие виртуального фискального регистратора, чтобы все функции (нефискальные) фискального регистратора выполнял чековый принтер и этот режим можно было бы явно установить? Чтобы "Самурай без меча подобен самураю с мечом, но только без меча."

**Comment by stasgm** [comment]
Исправлено. Обрабатывается корректно возврат с нефискальным регистратором. 

Разработка виртуального фискального регистратора, он же самурай без меча, требует времени. Возможно в будущем будет реализован, но не сейчас.
