### ISSUE TITLE
Бонусная система

### ISSUE THREAD

**Issue by supportkkc** [gsbelarus/check-and-cash#35]
Слышал, что для **positive check** разрабатывается бонусная система. Планируется ли на **positive cash**, что-нибудь из этого направления?
- [x] использование бонусов, как скидки
- [x] использование бонусов, как отдельного типа оплаты
- [x] отчёты
- [x] начисление бонусов за продажу через указанное кол-во дней (служба на headoffice)
- [x] сжигание бонусов 
- [x] перерасчёт бонусов при частичном возврате
- [x] импорт из dbf
- [x] синхронизация магазинов

**Comment by gsbelarus** [comment]
Да, после опробации.

**Comment by supportkkc** [comment]
Когда ждать реализации  (сроки) бонусной системы на **positive cash**, есть заинтересованный действующий клиент (от бонусной системы зависит расширение сети заведений)?

**Comment by hirurg-lybitel** [comment]
@supportkkc ещё актуальна эта система в рознице?

@MAliaksandr бонусная система уже отлажена?

**Comment by hirurg-lybitel** [comment]
@MAliaksandr бонусная система уже отлажена?

**Comment by MAliaksandr** [comment]
Система переделывается.

**Comment by supportkkc** [comment]
Система переделалась? Клиенты интересуются.

**Comment by hirurg-lybitel** [comment]
@MBurakina

**Comment by hirurg-lybitel** [comment]
@MBurakina Александр сказал, что ты в курсе текущего состояния

**Comment by MBurakina** [comment]
Она установлена у клиента, как они ей пользуются знает Александр. На эталоне для общепита её пока что нет, для кассы никогда и не разрабатывалось.

**Comment by hirurg-lybitel** [comment]
@MAliaksandr ваши комментарии, Александр?

**Comment by MAliaksandr** [comment]
Комментарий начальника АСУ "Вроде работает. Тогда ошибку подправили и нормуль."

**Comment by supportkkc** [comment]
Может на CASH перекинуть и по тестировать?

**Comment by hirurg-lybitel** [comment]
@MAliaksandr эта система уже вынесена в отдельный модуль?

**Comment by startkkc** [comment]
Есть результат?

**Comment by hirurg-lybitel** [comment]
нет

**Comment by hirurg-lybitel** [comment]
- [ ] использование бонусов, как скидки
- [ ] использование бонусов, как отдельного типа оплаты
- [ ] отчёты
- [ ] начисление бонусов за продажу через указанное кол-во дней (служба на headoffice)
- [ ] сжигание бонусов 
- [ ] перерасчт бонусов при частичном возврате

**Comment by supportkkc** [comment]
@hirurg-lybitel программа не даёт использовать бонусы, если все товары акционные (применена скидка). После последних установленных изменений, если на все 3 товара установить скидку и затем применить бонусную карту, то скидка с последнего товара слетает.

**Comment by hirurg-lybitel** [comment]
Доработки готовы. В эталоне появятся вместе с выходом новой версии.

Пока возможны **только ручные** обновления рабочих баз клиентов
