### ISSUE TITLE
Периодически товар не попадает на кассу

### ISSUE THREAD

**Issue by supportkkc** [gsbelarus/check-and-cash#36]
**Positive Cash.** 
При вводе накладной с указанием количества товара информация не передаётся на кассу.
Если зайти в прайс, поменять количество на любое другое, а затем снова вернуть нужное количество - товар появляется на кассе в нужном количестве.

**Comment by hirurg-lybitel** [comment]
Ввод накладной на складской базе не меняет ничего на кассе. Её надо экспортировать.
