### ISSUE TITLE
Chek проводит оплату на ФР номер -1

### ISSUE THREAD

**Issue by startkkc** [gsbelarus/check-and-cash#37]
Периодически PositiveChek проводит оплату на ФР номер -1, база и ПИ конец августа с сайта. Т.е. оплата идет не на установленный в системе ФР а на какой-то -1. Закономерности пока не выявлено. Сам фискальник ни как не реагирует, ошибок по логам нет. Создается не только новый ФР -1 но и нумерация с нуля.(в устройствах не отображается) Это уже второй случай на объекте, поэтому чек номер 3(в первый раз было две таких оплаты с разностью в 15 мин. причем между ними проходила и нормальная оплата на реальный ФР). В системе установлен только ФР Спарк и нефискальный режим (отключен)

**Comment by startkkc** [comment]
![1](https://cloud.githubusercontent.com/assets/17782689/18446736/5747b5a0-792c-11e6-8255-296ac1d7a1c7.jpg)
![2](https://cloud.githubusercontent.com/assets/17782689/18446737/574ad3ca-792c-11e6-8394-a7220a95cc7f.jpg)

**Comment by hirurg-lybitel** [comment]
Без базы ничего сказать не получиться

**Comment by stasgm** [comment]
@startkkc такое возможно только при потери связи с ФР или при окончании бумаги. Посмотрим журналы (если были включены) и попытаемся определить проблему.

**Comment by hirurg-lybitel** [comment]
@startkkc такая ситуация может получится только когда оплата заказа выполняется с компьютера, к имени которого не привязан ФР.

**Comment by startkkc** [comment]
логи включены, вероятность оплаты с другого ПК мала.

**Comment by stasgm** [comment]
@startkkc с этой проблемой разобрались или она всё ещё висит?

**Comment by supportkkc** [comment]
Переключили спарк на usb, чтобы исключить проблему в кабеле - проблема осталась, проявляется редко, точной закономерности не выявлено, чаще когда много заказов (выходные)

**Comment by supportkkc** [comment]
Есть решение?

**Comment by hirurg-lybitel** [comment]
Такую проблему симулировать не удалось.

**Comment by supportkkc** [comment]
Так что говорить клиенту? https://yadi.sk/d/mQ3DxDs73CEkks база и лог с ФР

**Comment by hirurg-lybitel** [comment]
Эта база от июля месяца.

**Comment by hirurg-lybitel** [comment]
@supportkkc вопрос актуален ещё?

**Comment by stasgm** [comment]
Снимаем вопрос из-за неактуальности.
