### ISSUE TITLE
Информирование о накопленных бонусах

### ISSUE THREAD

**Issue by gsbelarus** [gsbelarus/check-and-cash#4]
Информирование о накопленных бонусах на рабочем месте кассира.

**Comment by MAliaksandr** [comment]
можно и так, почему нет?
![image](https://cloud.githubusercontent.com/assets/11478712/15546967/96368364-22aa-11e6-92dc-16eec6ce5cda.png)

**Comment by hirurg-lybitel** [comment]
Откуда это?

**Comment by MAliaksandr** [comment]
Оттуда

**Comment by hirurg-lybitel** [comment]
@MAliaksandr  таки что там с этими бонусами? Можно их спокойно ставить на последнюю версию эталона?

**Comment by MAliaksandr** [comment]
Спокойно? хм...

**Comment by hirurg-lybitel** [comment]
@MAliaksandr  Пожалуйста, ответь более многосложно.

**Comment by MAliaksandr** [comment]
Ситуация немного нестабильна. Вроде все должно было работать. Сейчас появляются разные нюансы, которые тут же исправляются. Поэтому сказать что вот все класс и можно ставить на эталон - НЕЛЬЗЯ.

**Comment by alexandra-gsoftware** [comment]
если будете ставить, то ставьте только аккуратно, сначала собрать базу из новых пи и сравнить с бонусами.
