### ISSUE TITLE
Задача: Экспорт данных о покупках клиентов

### ISSUE THREAD

**Issue by gsbelarus** [gsbelarus/check-and-cash#40]
1. Покупатель предъявляет на кассе карту клиента. 
2. В базе чеков фиксируется, что эта покупка произведена этим покупателем.
3. Реализовать выгрузку в формате XML списка чеков за заданный период с указанием покупателя по чеку и списка товаров в чеке, с ценами. Выгружаются только чеки, для которых указан покупатель.

**Comment by hirurg-lybitel** [comment]
Что такое карта клиента?
Каково её  предназначение?

**Comment by gsbelarus** [comment]
Идентифицировать клиента. Надо совместить это с нашими бонусами.

Идентификация клиента может разными способами происходить:

1. У клиента есть карточка (скидочная карта, бонусная карта, пропуск на предприятие и т.п.). Данные с нее считываются через считывание с магнитной полосы, безконтактным считывателем, считыванием штрихкода.
2. У клиента есть мобильное приложение. На экране штрих код или QR код, который считывается.
3. Клиент просто называет свой код. Например, в некой кофейне говорит "Я Вася Пупкин" и покупка относится на Васю Пупкина.

Т.е. с вводом клиента так же как с вводом товара. Можно сканировать штрих код, а можно ввести штрих код вручную.

**Comment by gsbelarus** [comment]
Дослал заказчик свои пожелания:

В файле должен быть список клиентов магазина, у каждого клиента:

1.     id (его штрихкод)
2.     размер предоставляемой скидки (в зависимости от программы лояльности магазина
3.     список покупок

В файле должны быть списки покупок клиентов, которые используют программы лояльности

У каждого клиента есть список покупок, у каждой покупки:

1.     id клиента (его штрихкод)
2.     № чека
3.     Дата и время покупки
4.     Итого без скидки
5.     Итого со скидкой
6.     список приобретенных товаров

В файле должны быть товары конкретного магазина.

У каждого товара:

1.     название
2.     артикул
3.     цена
4.     скидка %
5.     цена со скидкой
6.     масса
7.     еденица измерения
8.     торговая марка
9.     состав
10.     белки (для прод товаров)
11.     жиры (для прод товаров)
12.     углеводы (для прод товаров)
13.     энергетическая ценность на 100 г (для прод товаров)
14.     описание

**Comment by hirurg-lybitel** [comment]
@MBurakina @MAliaksandr сделано?

**Comment by MAliaksandr** [comment]
вроде да. но с заказчиком пока не обсуждали

**Comment by MBurakina** [comment]
Тут не совсем корректно сформулировано. 
Клиенты+их покупки+описание товара в покупках уже есть.
Но еще они хотят выгрузку всех товаров по магазину со скидочными ценами. Скидочные цены динамически считаются и нигде не храняться. Пока что мы сошлись на том, что будем выгружать цены с постоянными скидками, т.е. скидки, действующие весь день. Сейчас я дописываю для этого две процедуры, они на базе чековых процедур. Если ты можешь с этим помочь - будет быстрее.

**Comment by hirurg-lybitel** [comment]
Скидочные цены (цена, по которой продали товар) хранятся в поле usr$pf_checkline.usr$pricesale

**Comment by MBurakina** [comment]
Тут вопрос о проценте скидки и цене со скидкой просто в прайсе, а не в чеке.
Когда просто скидка, без карты. 
Например на товар1 всю субботу -5%. Вот и нужно посчитать цену со скидкой и выгрузить товар1, цена, цена со скидкой.  Еще нет никакой продажи, есть прайс и правила округления.

**Comment by hirurg-lybitel** [comment]
@MAliaksandr ну что с этим вопросом?

**Comment by MBurakina** [comment]
Я сделала что они хотели, теперь хотят уже больше, обсуждаем интеграцию дальше. Тебе переслать переписку? Ты хочешь учавствовать в обсуждении?

**Comment by hirurg-lybitel** [comment]
Нет

**Comment by hirurg-lybitel** [comment]
@MBurakina @MAliaksandr можно закрывать?

**Comment by MBurakina** [comment]
Да, задача давно мутировала в отдельный договор.
