### ISSUE TITLE
positive check + ingenico itc (банковский терминал)

### ISSUE THREAD

**Issue by supportkkc** [gsbelarus/check-and-cash#41]
Банковский терминал ingenico был состыкован с positive check, но в работе этой связки возникли следующие вопросы.
1) Банковский терминал не признает фискальные регистраторы с регистрационным знаком больше 99. Для временного решения в настройках ФР поменяли номер с 721, на 21 - пока работает.
2) Была проблема с копейками. Если отправляешь на банковский терминал итог 1,60 ( в конце 0) на банковском терминале отобразится сумма 0,16. Возраты не проверил, просьба проверить на офисе.
3) Не проверены нестандарные ситуации (сбои), т.е. обрыв связи во время пересылки данных банк.
4) Нет инструкции по работе с Банковским терминалом (инструкция по работе, подключению, ошибкам, НЕТ АЛГОРИТМА ДЕЙСТВИЙ, ЧТО ДЕЛАТЬ ПРИ ОБРЫВЕ ЛЕНТЫ И КУДА СМОТРЕТЬ).
5) Нет возможности работы с меню банковского терминала, в positive cash есть клавиатура и реализовано это через функциональные клавиши, в check`е появляются просто цифры, а т.к. нет клавиатуры - работать в этом меню не возможно.

**Comment by hirurg-lybitel** [comment]
5) а чем данная форма не устраивает?

![image](https://cloud.githubusercontent.com/assets/11502258/18879726/13c268ee-84de-11e6-8028-24cd7f0baaa7.png)

**Comment by supportkkc** [comment]
Дальше......Зайди пожалйста в меню просмотр\печать итогов, меню печати отчетов.

**Comment by supportkkc** [comment]
Обнаружена новая проблема
6) при смешанной оплате, карточка +наличка, выходит просто фискальный чек( без взаимодействия с  Банковским терминалом). В фискальном чеке отображено все верно (наличка +карточка). Проверьте так же смешаннные возвраты.

**Comment by hirurg-lybitel** [comment]
Добрый день 

1) Как было отмечено в вопросе, это вопрос к банковскому терминалу. Вот описание из документации. 
![image](https://cloud.githubusercontent.com/assets/11502258/18955181/911301b8-8656-11e6-8a4a-9544b2e2c360.png)

2) Проверено

3) В БПЦ проверяли. Будем надеятся, что все случаи учли.

4) Инструкция по настройке и подключению будет. По ошибкам надо говорить.

5) Всё должно хорошо нажиматься. Просто некоторые окна выводит сам терминал (большие белые и некрасивые). Но и там всё должно хорошо откликаться на нажатие пальцем.

6) Проблема возникала, когда сначала шла карта, а потом остальное. **Исправлено**

**Comment by supportkkc** [comment]
5) был на объекте где банковский и Check. Да, в окне, которое выводит Банковский терминал, можно передвигаться нажатием на надписи. Но когда заходишь глубже в меню, там есть операции, где надо ввести пароль, либо при печати копии чека, надо ввести номер чека. Виртуальной клавиатуры нету, но почему-то срабатывает нижняя строка windows, и можно пройти в меню ПУСК и там включить виртуальную клавиатуру.

**Comment by hirurg-lybitel** [comment]
Максимум, что можно сделать - это автоматически запускать экранную клавиатуру при работе с банковским терминалом.

**Comment by stasgm** [comment]
@supportkkc ещё актуальна проблема?
