### ISSUE TITLE
Шведский стол

### ISSUE THREAD

**Issue by gsbelarus** [gsbelarus/check-and-cash#43]
Такую доработку хотят одни клиенты:
1. Гость на входе платит фиксированную сумму.
2. В течение Н часов он может без ограничений питаться по системе "шведский стол".
3. В случае превышения времени должен доплатить.
4. Официант должен видеть на карте столов сколько времени осталось и в случае превышения должна быть какая-то сигнализация предусмотрена. Например, цветом выделять стол.

**Comment by stasgm** [comment]
@gsbelarus Кто эту задачу ставил? Пусть напишет заказчик мне на email т.к. из краткого описания неясно как должна работать система. Да и сам процесс неясен. Например, как программа должна регистрировать окончание времени, 
Могу конечно прикинуть, что уйдёт на всё от 20 до 80 часов.

**Comment by stasgm** [comment]
@gsbelarus  Нет развития постановки. Закрываем тему?
