### ISSUE TITLE
ТЗ по РНТ

### ISSUE THREAD

**Issue by supportkkc** [gsbelarus/check-and-cash#45]
ТЗ отправлено Юре Ш., жду сроки и часы. Спасибо

**Comment by hirurg-lybitel** [comment]
Ждём-с последние базки.

**Comment by supportkkc** [comment]
Отправил базы которые были установлены после деноминации, с того времени не обновлялись

**Comment by hirurg-lybitel** [comment]
Отправил доработки на тестирование
