### ISSUE TITLE
PositiveCash проблема с аннулированными чеками

### ISSUE THREAD

**Issue by supportkkc** [gsbelarus/check-and-cash#46]
При распечатывании контрольной ленты и последующем снятии X-отчёта, чек продажи, следующий за X-отчётом попадает в разряд аннулированных. При этом связь с ФР есть.

**Comment by hirurg-lybitel** [comment]
@supportkkc 
Такой проблемы не обнаружено.
Это вообще ещё актуально?

**Comment by supportkkc** [comment]
Думаю, что уже не актуально, с версией 2.9 отпадает необходимость в контрольной ленте.
