### ISSUE TITLE
Экпорт меню в XML. несоответсвие DateValue

### ISSUE THREAD

**Issue by supportkkc** [gsbelarus/check-and-cash#48]

**Comment by supportkkc** [comment]
![image](https://cloud.githubusercontent.com/assets/20512230/19485212/0643c9a2-9563-11e6-9053-3d08671fb79f.png)

**Comment by supportkkc** [comment]
![image](https://cloud.githubusercontent.com/assets/20512230/19485240/227772b8-9563-11e6-8d87-1582b30c1fbd.png)

**Comment by hirurg-lybitel** [comment]
@supportkkc xml файлик бы сам увидеть.

**Comment by stasgm** [comment]
@supportkkc Экспорт - это выгрузка. 
Волне возможно, что в xml дата записана не в формате даты.

**Comment by gsbelarus** [comment]
а как идет преобразование даты в строку и обратно? должно делаться через фиксированный формат своими функциями и ни в коем случае не преобразованиями и функциями VBS. Потому что они зависят от региональных настроек компьютера. 

Стандарт XML определяет следующий формат для дат:

http://www.w3schools.com/xml/schema_dtypes_date.asp

В таком формате записываются даты у нас в YAML^

https://github.com/GoldenSoftwareLtd/gedemin-apps/blob/master/%D0%91%D1%83%D1%85%D0%B3%D0%B0%D0%BB%D1%82%D0%B5%D1%80%D0%B8%D1%8F/16%20%D0%B2%D0%B5%D0%B4%D0%BE%D0%BC%D0%BE%D1%81%D1%82%D1%8C%20(%D0%B4%D0%B0%D0%BD%D0%BD%D1%8B%D0%B5).yml

В Гедымине есть функции для преобразования туда-обратно.

**Comment by supportkkc** [comment]
[menu.zip](https://github.com/gsbelarus/check-and-cash/files/541765/menu.zip)

надеюсь упростит задачу

**Comment by hirurg-lybitel** [comment]
@supportkkc просто заполните поле "По дату"

**Comment by stasgm** [comment]
@supportkkc Если даты окончания нет, то не надо добавлять атрибут active_to и делать его =""
