### ISSUE TITLE
Расширение синхронизации

### ISSUE THREAD

**Issue by supportkkc** [gsbelarus/check-and-cash#49]
Сейчас Бэк Гедымина собирает (объединяет) данные с Кассовых серверов, и пересылает данные на КС. В цепочке, где используется сторонний Бэк, такого механизма объединения нет. Сразу ставится под вопрос работы с накопительными скидками, просмотром отчетов (подключаться к каждому магазину отдельно). Предлагаю использовать еще один КС для объединения данных с других КС.

**Comment by hirurg-lybitel** [comment]
Синхронизировать всю эту информация не проблема.
А вот с отчётами посложнее.
Тут или переделывать все существующие или их аналоги создавать для головного сервера.

**Comment by supportkkc** [comment]
@hirurg-lybitel  закрывай проблему. С накопительными видимо решили, пока всё.
