### ISSUE TITLE
Обмен со сторонним бэком.

### ISSUE THREAD

**Issue by gsbelarus** [gsbelarus/check-and-cash#5]
Автоматический «подхват» файла импорт-экспорт при работе со сторонним бэком.

**Comment by hirurg-lybitel** [comment]
@alexandra-gsoftware а на каком сейчас всё этапе?

**Comment by alexandra-gsoftware** [comment]
тз есть, больше ничего.

**Comment by gsbelarus** [comment]
так надо делать

**Comment by hirurg-lybitel** [comment]
@alexandra-gsoftware а сейчас на каком этапе?

**Comment by alexandra-gsoftware** [comment]
Нужно было решение для конкретного клиента, где был один файл обмена.  Это решение готово. 
Глобальное решение не сделано. Мне кажется, это иссъю можно закрыть, а для глобального решения есть отдельная задачка https://github.com/GoldenSoftwareLtd/gedemin-apps/issues/138
