### ISSUE TITLE
тормозит FBserver.exe занимает процессор на 100% 

### ISSUE THREAD

**Issue by supportkkc** [gsbelarus/check-and-cash#51]
Суть проблемы, процесс FBserver.exe занимает процессор на 100%. Наблюдаются задержки между операциями (просмотр заказов- выход, новый заказ, карта зала - выход и т.п.) от 2 до 5 секунд. Это PositiveCheck. После деноминации все работало нормально, последний месяц есть проблемы. Пробовал переустановить FB. Дефрагментировал винт, база не большая 240 МБ. Базу архивировал и распаковывал. Работает на железе 1,6 celeron   1 Гб оперативки. Что еще можно посмотреть почистить?

**Comment by hirurg-lybitel** [comment]
Процессор постоянно забит?

Попробуйте зайти под администратором. Процессор при этом также загружен будет?

**Comment by supportkkc** [comment]
без позитива система работает хорошо, процессор забивается на 100% только между операциями, если просто открыта программа (любое окно, заказы например) то он успокаивается, но как только начинают происходить действия - начинаются тормоза.

**Comment by hirurg-lybitel** [comment]
Попробуйте убрать все процессы с того ядра, на котором ФБ работает

**Comment by MAliaksandr** [comment]
Я бы глянул на скрины:
1. Служб (конкретно FB)
2. Диспетчера задач
3. И каталога bin  установленного FB

**Comment by hirurg-lybitel** [comment]
Так а что было то?
