### ISSUE TITLE
POSitive Check: Списание аванса в выручку кухни

### ISSUE THREAD

**Issue by supportkkc** [gsbelarus/check-and-cash#52]
Есть ли возможность настройки авансов таким образом, чтобы аванс списывался только в выручку кухни, а не рандомно (часть в выручку кухни, часть в выручку бара)?

**Comment by stasgm** [comment]
@supportkkc 
В параметрах указывается подразделение для получения и списания аванса. 
На эталонной базе сделал пример и проверил. Аванс проходит по кухне, как я и указал в параметрах
![image](https://cloud.githubusercontent.com/assets/8355925/20265210/cc5aff34-aa80-11e6-8680-96c8e5f2b0eb.png)

**Comment by stasgm** [comment]
@supportkkc 
В параметрах указывается подразделение для получения и списания аванса. 
На эталонной базе сделал пример и проверил. Аванс проходит по кухне, как я и указал в параметрах
![image](https://cloud.githubusercontent.com/assets/8355925/20265313/791a382a-aa81-11e6-876a-130b228a3971.png)

**Comment by stasgm** [comment]
@supportkkc отправлено письмо - не созданы подразделения, а использованы категории вместо них, что не верно.
