### ISSUE TITLE
Возврат/реестр ошибочно сформированных чеков

### ISSUE THREAD

**Issue by supportkkc** [gsbelarus/check-and-cash#53]
В кассовой дисциплине есть возврат и реестр ошибочно сформированных чеков. Возврат, для ситуаций, когда человек возвращает товар, а мы деньги. Но бывает и, когда кассир ошибается. Сейчас при ошибке кассира люди пользуются возвратом, что не есть правильно. В клавиатуре есть функция отмена чека (возврат в день)(ctrl+b), но это тот же возврат, только возвращается сразу весь чек, не частично (возврата одной позиции). 
Можно ли сделать механизм отмены чека в системе? У пользователя есть права на такое действие, набирает номер чека и кнопку (удаление чека). В системе указанный чек отменяется (не возврат), а по ФР остается.

**Comment by hirurg-lybitel** [comment]
А какой смысл отменять чек в программе, но не отменять в ФР?
Это ведь вызовет расхождения в отчетах

**Comment by supportkkc** [comment]
Операции отмены чека после оплаты в ФР нет. Отменять чек в программе нужно, чтобы он не пошел в реализацию, а на разницу в ФР в бухгалтерии пишется акт.
Если считаешь, что эта функция не нужна, тогда я сообщу клиенту, чтобы писали ТЗ, и будем оформлять, как доработку.

**Comment by hirurg-lybitel** [comment]
Базы с соответствующими доработками высланы на tsa@kkc.by

**Comment by hirurg-lybitel** [comment]
@supportkkc проверили?
