### ISSUE TITLE
Positive Check

### ISSUE THREAD

**Issue by supportkkc** [gsbelarus/check-and-cash#54]
1) прислать настройку на tsa@kkc.by, для разделения в предчеке позиций на бар и кухня (она у Вас должна быть на каком-то из объектов)
2) добавить в основной функционал (обговаривали с программистом Станиславом), возможность видеть терминалом меню предназначенное только для этого терминала (эта доработка уже есть).
3) не печатаются отчеты с терминала на принтере posiflex pp9000 (размытое изображение)
4) в сводном отчете (для печати с терминала) сейчас есть разбиение выручки на бар и кухня, можно еще добавить разбиение на наличку и карточку (как в сводном отчете с Администраторской части).
5) возможно ли добавить жирный шрифт (для читаемости), сервис документов (производство) на принтер posiflex pp9000

**Comment by supportkkc** [comment]
1. - СПАСИБО

**Comment by stasgm** [comment]
@supportkkc  пункт 2 сделан. Брать в гите. 
![image](https://cloud.githubusercontent.com/assets/8355925/20755267/6456ec9e-b71f-11e6-8545-8d99da48b86b.png)
Указываем имя терминала и подразделение 
![image](https://cloud.githubusercontent.com/assets/8355925/20755275/6ad4df54-b71f-11e6-9bc3-df28f533f1b6.png)

**Comment by supportkkc** [comment]
2. СПАСИБО, проверяю

**Comment by stasgm** [comment]
@supportkkc 

Вопрос 4 проверил. Всё так и работает - по типам оплаты в разрезе подразделений.

![image](https://cloud.githubusercontent.com/assets/8355925/20792279/0077cb90-b7d2-11e6-8cae-675ee7e7a5c8.png)

**Comment by stasgm** [comment]
@supportkkc Вопросы 3 и 5 - нужен принтер.

**Comment by supportkkc** [comment]
4. Спасибо
3. и 5. в ближайшие дни отправлю

**Comment by supportkkc** [comment]
9.01.17 - принтер привезут на офисе, с пометкой "для Стаса"

**Comment by supportkkc** [comment]
@stasgm Как идет процесс?

**Comment by stasgm** [comment]
@support_kkc ![](http://i.imgur.com/DA2wpjr.jpg) печать отчёта из формы меню, вопрос 3. Кроме ширины печати проблем нет. Вопрос 5 ещё смотрю

**Comment by supportkkc** [comment]
3. Отпишись как закончишь.
5. Этот вопрос так сказать широкий, его можно и на другие принтера (Синокан p11), если помнишь я тебе звонил еще по поводу длинны сервис чеков,  что они сильно длинные (там печатается курс), ты говорил про динамический шаблон, чтобы можно было что-то включать/выключать из шаблона, там та и применить возможность выбирать шрифт, или тип шрифта.

**Comment by supportkkc** [comment]
Как дела?

**Comment by stasgm** [comment]
@supportkkc пока задача отложена. Внедрения идут

**Comment by supportkkc** [comment]
@stasgm Как дела?

**Comment by supportkkc** [comment]
Добрый день. Как пункт 3?

**Comment by supportkkc** [comment]
Добрый день. Как пункт 3?

**Comment by stasgm** [comment]
Был отложен в долгий ящик. если приоритет высокий то буду смотреть

**Comment by startkkc** [comment]
@stasgm Нужна доделать, а то и принтер пустует у Вас, ну и клиенту нужен, как раз отчет, который не работает (по официантам), можно его то же разбить по точкам продажи (привязки к фр) или лучше по подразделению.

**Comment by stasgm** [comment]
@startkkc принято. Поставил задачу себе в график.

**Comment by stasgm** [comment]
Сводный отчёт
![image](https://user-images.githubusercontent.com/8355925/38140619-3ffc4f82-343d-11e8-94ce-54bc091398d5.png)
