### ISSUE TITLE
Сеть магазинов

### ISSUE THREAD

**Issue by supportkkc** [gsbelarus/check-and-cash#55]
Если клиент использует сторонний Бэк, фронт Positive Cash и у него несколько (отдельных) магазинов. Часть функций не будет работать: кол-ный учет на кассе (ограничение по продаже конкретного магазина), или синхронизация накопительных карт (помесячных карт). Нет связующего КС для объединения данных по КС на магазинах.
Если клиент использует Бэк Гедымин и фронт Positive Cash, все эти функции работают - объединением занимается БЭК.

**Comment by MIchaelShoihet** [comment]
Делать какой-то еще промежуточный функционал слишком накладно. И иметь две дублирующие технологии то же. Клиент либо дорабатывает свой бэк, либо использует наш.

**Comment by supportkkc** [comment]
Я Вас понял, спасибо за ответ.
