### ISSUE TITLE
Аннулированный чек

### ISSUE THREAD

**Issue by supportkkc** [gsbelarus/check-and-cash#56]
Есть клиент, у которого частенько получается ситуация, когда чек по ФР прошел, а в системе он висит как аннулированный. По логам чек действительно аннулирован, но что стало причиной не понятно. Это не окончание ленты в фр. Замечено единственное отличие от того как работают другие фронты, они делают копию чека после каждой оплаты. (positive cash)

**Comment by hirurg-lybitel** [comment]
Обновите программу.
В параметрах появилась галочка "печатать копию чека".

**Comment by hirurg-lybitel** [comment]
@supportkkc каков статус проблемы?

**Comment by supportkkc** [comment]
проверяю
