### ISSUE TITLE
Артикул+Весы

### ISSUE THREAD

**Issue by supportkkc** [gsbelarus/check-and-cash#57]
В positive cash есть кнопка Артикул+Весы. Кассир кладет на весы товар, набирает артикул и нажимает эту кнопку. Вводится товар с введенным артикулом и берется вес с весов. Появилась проблема с использованием этой кнопки. Если я ввел товар, не важно какой, весовой или штучный, а за тем случайно ввел не верный артикул (товара, которого нет) и воспользовался этой кнопкой. Появится сообщение, что товар не найден и изменится кол-во в предыдущем товаре.

**Comment by hirurg-lybitel** [comment]
В текущей версии не получается воспроизвести такую ситуацию.
Попробуйте обновить программу.
