### ISSUE TITLE
Вывод на второй монитор

### ISSUE THREAD

**Issue by supportkkc** [gsbelarus/check-and-cash#59]
Есть сенсорный терминал с двумя мониторами (второй идет как расширение первого). Клиент хочет, чтобы на дополнительном мониторе отображалась реклама магазина (акции, итд) и чтобы он же работает, как дисплей покупателя. Т.е. касса не производит продажу - на втором мониторе идет реклама, как только я добавил позицию, второй экран работает как дисплей покупателя. Возможно ли реализовать и сколько по времени?

**Comment by gsbelarus** [comment]
По идее не сложно. Надо предусмотреть окно для вывода информации покупателю и установить ему координаты второго монитора.

http://stackoverflow.com/questions/206400/start-program-on-a-second-monitor

Что касается вывода рекламы, то там моэно использовать компонент TWebBrowser и выводить HTML.

**Comment by gsbelarus** [comment]
Пару вариантов решения просматриваются. Первый -- используем только средства Гедымина. Несколько мониторов трактуются операционной системой как одно большое поле, где у каждого монитора своё начало координат. У первого 0, 0. У второго правее и т.д. В объекте Screen: TScreen есть массив мониторов, через который можно узнать начальные координаты каждого.

Итого, потребуется немодальное окно, которое расположим на втором мониторе. По мере обновления информации на первом (меняется чек), посылаем сообщения окну на втором экране, оно обновляется. (Калдырский вариант -- таймер на втором окне и обновление по нему, но это не правильно и не красиво). Когда надо вывести рекламу -- выводим заранее подготовленное изображение в формате JPG или PNG.

Второй вариант. Более геморройный, но за-то позволяющий вывести информацию хоть на другом компьютере в сети, а не только на втором мониторе. Используем то, что Гедымин имеет встроенный веб-сервер. На втором мониторе открываем браузер и грузим в него страницу со скриптом. Скрипт периодически опрашивает Гедымин и обновляет отображаемую информацию. Либо, более сложный вариант, вешаем в скрипте параллельную функцию, которая будет слушать поступающие от сервера сообщения. Т.е. самостоятельная реализация Push технологии.

При выборе браузера сразу начнутся проблемы с блокированием трафика всякими файр-волами, с размещением окна браузера и т.п.

Первый вариант, через немодальное дочернее окно, реализовать проще.

**Comment by hirurg-lybitel** [comment]
@gsbelarus
"В объекте Screen: TScreen есть массив мониторов".
Это в делфи. А в гедемине, насколько я помню, такого нет.

**Comment by gsbelarus** [comment]
Надо добавить

**Comment by hirurg-lybitel** [comment]
@supportkkc Тестовый экземпляр программы отправлен в ККС для проверки на конечном компьютере

**Comment by hirurg-lybitel** [comment]
@supportkkc  что-нибудь скажите?
