### ISSUE TITLE
Отчеты в торговле(складе)

### ISSUE THREAD

**Issue by MAliaksandr** [gsbelarus/check-and-cash#61]
Обнаружил, что в последних настройках(эталонных) периодически проскакивают недочеты с типами данных при выводе, например:
**call q11.AddField("TO_USR$INV_COSTRETAILNCU", **"ftBCD", 0, 0)****
думаю, комментировать излишне. надо бы в эталонных отчетах подкрутить...
конкретная функция для поиска RetailInv_rp_AddwBill_Order147050326_8851147789117_709839519
хотя ковырнув в базе, можно найти и еще отчеты "Справка о заработной плате (новая)" и т.е.

**Comment by hirurg-lybitel** [comment]
@MAliaksandr так а что не так с типом данных?

**Comment by MIchaelShoihet** [comment]
call q11.AddField("TO_USR$INV_COSTRETAILNCU", "ftBCD", 0, 0) такое описание предполагает целое число. Для дробного надо call q11.AddField("TO_USR$INV_COSTRETAILNCU", "ftBCD", 15, 0)

**Comment by hirurg-lybitel** [comment]
@MAliaksandr это ты репозиторием ошибся. Здесь вопросы по фронтам записываем
