### ISSUE TITLE
Акт перемера

### ISSUE THREAD

**Issue by MAliaksandr** [gsbelarus/check-and-cash#64]
Все время хотел спросить, почему нет в эталоне торговли/общепите акта перемера? Это ж обычное дело у поставщика, привезти\недовезти\перенедовезти товары. Или он есть, но он как-то иначе реализован и я его не вижу?

**Comment by MBurakina** [comment]
Почему ты пишешь в ветку общепита и кассы? Пиши в Gedemin-apps.

**Comment by hirurg-lybitel** [comment]
Снова не в тот репозиторий
