### ISSUE TITLE
Накопительные карты

### ISSUE THREAD

**Issue by gsbelarus** [gsbelarus/check-and-cash#65]
Сейчас накопительные карты работают по следующей схеме.

Есть накопительные карты, и есть скидка автомат (применяется автоматически 20%). Если я создам запрет на накопительные карты, пробью товар со скидкой и применю Накопительную карту - скидка накопительной карты пройдет, но сумма чека пойдет в зачет накопительной карты. В принципе эта верная обработка. Но тут сумма идет в зачет накопительной карте из-за того, что в чеке есть хоть какая-то скидка (в данной ситуации это 20%).

Если в правиле запретов, добавить оба этих правила, и проделать те же действия, то в накопление эта сумма не пойдет.

Хотелось бы, чтобы сумма шла в зачет накопительной карты  в обоих случаях.

**Comment by hirurg-lybitel** [comment]
![image](https://cloud.githubusercontent.com/assets/11502258/21263038/90b0f5ea-c3a5-11e6-922a-f9c4a2cfde90.png)
