### ISSUE TITLE
Задвоение товара в фронт части

### ISSUE THREAD

**Issue by supportkkc** [gsbelarus/check-and-cash#68]
В Бэке (Гедымин) поменяли данные по товару. На кассовом сервере в прайсе один товар, в Бэке один товар, в фронт части - в прайсе два товара.

**Comment by hirurg-lybitel** [comment]
1. Обновить кассовый сервер и кассу.
2. Открыть Служебная информация » Синхронизация » Лог информации
3. Выбрать все записи по: **Документ** - прайс, **Тип операции** - 2,  **Касса** - пусто. 
4. Из полученного списка по полю **ИД объекта** найти на **кассе** соответствующие прайсы и удалить их, а затем очистить и сам список.
