### ISSUE TITLE
Бронирование остается висеть после возврата денег.

### ISSUE THREAD

**Issue by supportkkc** [gsbelarus/check-and-cash#69]
Бармен пытался сделать возврат денег за бронирование от которого отказались, фискальный чек распечатался, но бронирование осталось.
Была сделана бронь, из фронта она видна, но из отчета, допустим из "Отчета по бронированиям -  нет."
#POSitive Check

**Comment by stasgm** [comment]
По первому вопросу - тестировал без фискальника, без проблем операция возврата прошла и отобразилась в отчётах. 
![image](https://cloud.githubusercontent.com/assets/8355925/22655587/b1ca0710-eca1-11e6-99aa-4c33ae8f898c.png)

Проверял журнал и нашёл запись по отмене. Фискальный чек не распечатался, видно в записи. 
![image](https://cloud.githubusercontent.com/assets/8355925/22658170/33b6bf36-ecaa-11e6-8a48-02cc4f43f720.png)


По второму вопросу. Нужно заполнить параметры аванса, перезагрузить программу и можно строить отчёты.
![image](https://cloud.githubusercontent.com/assets/8355925/22657753/9eb4066a-eca8-11e6-9be5-462e9227df08.png)

**Comment by supportkkc** [comment]
проверили, помогло
