### ISSUE TITLE
Не втягиваются данные в Бэк, в логе висит ошибка.

### ISSUE THREAD

**Issue by supportkkc** [gsbelarus/check-and-cash#70]
В логе синхронизации на бэке висит ошибка. Ваш сотрудник смотрел и сказал, что проблема в чеках на КС. Кому переслать БД (бэк, фронт, КС)?

**Comment by hirurg-lybitel** [comment]
Лог синхронизации на БЭКе не имеет никакого отношения к данным, которые попадают НА него.

Либо скидывайте тому сотруднику, с которым общались, либо ещё раз нормально опишите проблему.

**Comment by supportkkc** [comment]
![1](https://cloud.githubusercontent.com/assets/20512230/22548230/8de1366e-e956-11e6-948a-25c6caac488b.png)

**Comment by hirurg-lybitel** [comment]
Как мне сказали, наш сотрудник уже объяснил возможну причину этого.

Экспортируйте справочник товаров.
Сделайте слияние ТМЦ-дубликатов.
Переимпортируйте продажи.

**Comment by supportkkc** [comment]
Свежие БД переслал. Создание товаров на КС или фронте - исключено. Почему так происходит надо выяснять.

**Comment by supportkkc** [comment]
Выполнил действия по инструкции.
