### ISSUE TITLE
Установка Check

### ISSUE THREAD

**Issue by supportkkc** [gsbelarus/check-and-cash#72]
После установки ПО с сайта, и первом запуске БД, появилось сообщение. При повторном, больше не появлялось. Критично?
![default](https://cloud.githubusercontent.com/assets/20512230/22639010/e829729a-ec5c-11e6-823a-84cd51a50be1.PNG)

**Comment by stasgm** [comment]
@supportkkc не критично, но недопустимо. Пересоберём и проверим.

**Comment by gsbelarus** [comment]
Это значит что где то вызывается progress.startstep, но перед этим не было
progress.startwork. раньше эта ошибка просто игнорировалась.

Проверить можно progress.workstarted.

И в любом случае исправить ошибочный код.

**Comment by stasgm** [comment]
@supportkkc исправлено.

**Comment by supportkkc** [comment]
Спасибо

**Comment by supportkkc** [comment]
@stasgm Стас, такое же сообщение при обновлении ПИ positive cash
