### ISSUE TITLE
Проблема при запуске POSitive:Check

### ISSUE THREAD

**Issue by hirurg-lybitel** [gsbelarus/check-and-cash#73]
https://github.com/GoldenSoftwareLtd/gedemin-apps/issues/292

**Comment by hirurg-lybitel** [comment]
@supportkkc всё-таки это связано с настройками гедымина.

Видимо, не стоит гадочка "Разрешать более одного подключения под одним логином" в Сервис - Параметры - Аудит и безопасность

**Comment by stasgm** [comment]
@supportkkc Разрешилась проблема?
