### ISSUE TITLE
Невозможно ввести пароль

### ISSUE THREAD

**Issue by supportkkc** [gsbelarus/check-and-cash#75]
ПО и БТ в связке, при попытке произвести возврат чека, появляется trpos и просит пароль, и это пароль кассира 0000, на экране нет виртуальной клавиатуры чтобы ввести пароль. Клиент звонит в офис и сервис им вводит этот пароль.

**Comment by hirurg-lybitel** [comment]
Скиньте, пожалуйста, скриншот.

**Comment by supportkkc** [comment]
Не сильно красиво реализовано (про виртуальную клавиатуру). Но если лучше нельзя, то можно закрывать задачу.
