### ISSUE TITLE
Не передается правило скидки

### ISSUE THREAD

**Issue by supportkkc** [gsbelarus/check-and-cash#76]
У клиент при отправке скидки с бэка на фронт, не заводится Правило скидки. Кому выслать БКП?

**Comment by hirurg-lybitel** [comment]
@supportkkc если проблема её не решена, то кидайте на yurashoihet@gmail.com

**Comment by hirurg-lybitel** [comment]
1. Обновить ПИ **GS.PositiveCash.Склад.Скидки.Дополнение** с признаком "Всегда перезаписывать".
2. В правиле скидок указать для какого оно подразделения (в данном случаем "Магазин")
