### ISSUE TITLE
Сделать возможность указывать главную группу ТМЦ для в меню

### ISSUE THREAD

**Issue by stasgm** [gsbelarus/check-and-cash#77]
Вопрос возник после того как начали грузить прайс на фронт.
По умолчанию главная группа для доступа кассиру из меню задаётся в параметрах как Готовые изделия, но с использованием прайса нам нужно переопределять группу на Все тмц. 
А это значит что в меню уровень вложенности увеличивается на 1 уровень. т.е. сначала нажимаем на кнопку с названием меню, а затем нажимаем или "Товары из накладной" или "Готовые изделия"

**Comment by supportkkc** [comment]
Еще момент. Розничный прайс - это в основном штучные товары. Можно ли на основании остатков удалять из прайса товары которые уже закончились и следовательно удалять из меню на кассе. Жизнеспособен ли такой вариант?

**Comment by hirurg-lybitel** [comment]
Или такой вариант. 
Можно вести количественный учёт через поле **кол-во** в меню и не отображать те его позиции, в которых кол-во = 0.

**Comment by stasgm** [comment]
@hirurg-lybitel господин хирург, это не выход т.к. иногда выгружают в прайс и собственную продукцию (полученную, например, на бар с кухни) кол-во = 1 шт т.к. не знают сколько продадут.
а вообще эту тему я открыл в issue бэка https://github.com/GoldenSoftwareLtd/gedemin-apps/issues/326

**Comment by stasgm** [comment]
https://github.com/GoldenSoftwareLtd/gedemin-apps/commit/43f28dc2f465af2a2e4cb7276fbb2842b1c264c9
