### ISSUE TITLE
Ошибки check

### ISSUE THREAD

**Issue by supportkkc** [gsbelarus/check-and-cash#79]
1) После замены exe файла взятого с сайта, exe не хочет обновлять структуру БД. В Control centre - ничего.
![imag0425](https://cloud.githubusercontent.com/assets/20512230/23554283/796e6a58-0035-11e7-874c-d3eb43431899.jpg)
2) Не работает кнопка "выключить терминал" на экране блокировки. После нажатия этой кнопки ОС делает "выход из системы".
3) ПО не может выполнить "открытие системы" на ФР Спарк 115-ТФ, пишет "bad value". Из-за этого приходится делать "открытие системы" на ФР через Драйвер - как следствие не подтягиваются дискрипторы из ПО для ФР Спарк-115.

**Comment by hirurg-lybitel** [comment]
1. Используйте для обновления базы [этот](http://gsbelarus.com/pw/downloads/gedemin-platform/gedemin/) экзешник. После обновления можно снова пользоваться текущим.

2. Какая версия ОС ? На Windows 7 x64 всё работает корректно. 

3. Нужна база, на который происходит ошибка. В текущей версии такой проблемы не обнаружено.

**Comment by gsbelarus** [comment]
1. должно уже и просто с последним экзешником чека пройти

2017-03-06 14:32 GMT+03:00 hirurg-lybitel <notifications@github.com>:

**Comment by supportkkc** [comment]
2. у нас в основном еще XP стоит на терминалах.
3. перешлю.

**Comment by hirurg-lybitel** [comment]
2. На Windows XP тоде проверил.

**Comment by hirurg-lybitel** [comment]
Какая-тнибудь из проблем ещё актуальна?

**Comment by supportkkc** [comment]
Проблемы решены
