### ISSUE TITLE
СМС рассылка

### ISSUE THREAD

**Issue by hirurg-lybitel** [gsbelarus/check-and-cash#80]
Один клиент хочет видеть [такой](http://docs.devinotele.com/modyl1c.html) механизм в Гедемине.

Способны ли мы реализовать подобную систему?

**Comment by gsbelarus** [comment]
Так элементарнейшая же вещь. Возьми сделай. Вот API:

http://sms-assistent.by/

Из макроса формируешь POST запрос для отсылки СМС и всё.

Клиенту придется создать акаунт и прописать его в программе.

Цены тут:

http://sms-assistent.by/ceny/minsk/

**Comment by gsbelarus** [comment]
Делается за 1-2 дня. Заодно всем будет такая настройка полезна.

**Comment by hirurg-lybitel** [comment]
я говорю о реализации на уровне платформы.

**Comment by gsbelarus** [comment]
А платформа причем тут?

**Comment by gsbelarus** [comment]
Такую вещь надо делать как прикладное решение. И у них так же сделано. Вот связь с внешним сервисом отправки смс:

http://docs.devinotele.com/_images/3.jpg

**Comment by andreylis** [comment]
У нас у клиента был желание увидеть наш сервис https://rocketsms.by в Гедемине. 
https://rocketsms.by/storage/rocketsms_api.pdf

Эта задача пока отложена?

**Comment by stasgm** [comment]
@andreylis а Вы, собственно, кто?

**Comment by andreylis** [comment]
@stasgm скорее всего — человек, который передает запросы клиентов, которые игнорируются с конца 2015 года, в публичный тудушник на гитхабе

**Comment by hirurg-lybitel** [comment]
@andreylis 
Здравствуйте.
Скажите, пожалуйста, о каком клиенте идёт речь? С кем Вы или ваш клиент общались на эту тему?

**Comment by hirurg-lybitel** [comment]
Тезнические требования высланы представителю фирмы sms-рассылки

**Comment by hirurg-lybitel** [comment]
Клиент пропал.
Задача утратила актуальность
