### ISSUE TITLE
Замечания по СКНО

### ISSUE THREAD

**Issue by hirurg-lybitel** [gsbelarus/check-and-cash#83]
1. Сделать возможность печати дубликата последнего чека, используя метод PrintDuplicate ().
2. Отображать в окне ПО статус, что смена в ФР открыта/закрыта. GetDeviceInfo(4) - 1- True, 0 – False.
3. Сделать возможность печати из ПО расширенного теста ФР (чтобы в любое время была возможность, не выходя из ПО, прочитать статус СКНО). Метод TestPrinter(3). Или выводить статус СКНО на экран из GetDeviceInfo(140). В описании интерфейса есть описание. Если реализовывать через GetDeviceInfo(140), то требуется выводить только 2й бит нулевого байта «соединение с сервером».
4. Сделать возможность работы ПО в режиме «без СКНО». ФР может работать как в режиме «с СКНО», так и в режиме «без СКНО». Режим можно получить GetDeviceInfo(139) 1 – с СКНО, 0 – без СКНО. Для режима «без СКНО» чек возврата надо оставить как было раньше – в чеке может быть несколько позиций.

**Comment by stasgm** [comment]
Статист!
