### ISSUE TITLE
В usrf_MakePayment добавить удаление пробелов у номера кассы

### ISSUE THREAD

**Issue by stasgm** [gsbelarus/check-and-cash#85]
Нужно сделать так `gdcDoc.FieldByName("USR$REGISTER").AsString = trim(mn_Options.CashNumber)`
Также проверить все места, где подставляется номер кассы.

**Comment by hirurg-lybitel** [comment]
Так а откуда берутся пробелы в этом номере?

**Comment by stasgm** [comment]
У одного клиента после того как зажевало ленту номер кассы проставился с пробелом.  Наверное берётся из справочника касс.

**Comment by gsbelarus** [comment]
Может лучше удалять в тот момент когда считываются и заполняются mn_Options?

**Comment by hirurg-lybitel** [comment]
хотел тоже самое постнуть

**Comment by stasgm** [comment]
Точно

**Comment by stasgm** [comment]
Странно, конечно. В классе свойство получает значения целочисленного типа 
FCashNumber = ibsql_C.FieldByName("Number").AsInteger

**Comment by hirurg-lybitel** [comment]
удалил?

**Comment by stasgm** [comment]
Нет, см. выше.

**Comment by stasgm** [comment]
Снова была обнаружена эта проблема. Связан с чеком который был закрыт после того как зажевало ленту в ФР.
