### ISSUE TITLE
Задваивание товара при возврате

### ISSUE THREAD

**Issue by hirurg-lybitel** [gsbelarus/check-and-cash#89]
В розничной торговле при импорте продаж задваивается (-траивается и т.д.) количество возвращаемого товара, если чек возврата ссылается на чек продажи, в котором возвращаемая позиция вносилась несколькими строками - из-за вот этого:
LEFT JOIN USR$PF_CHECKLINE cc on cc.USR$MASTERKEY = ch.USR$CONCERNEDCHECKKEY and cc.USR$PRICEINT = chl.USR$PRICEINT

Перенесено из [Задваивание товара при возврате](https://github.com/GoldenSoftwareLtd/gedemin-apps/issues/356#issuecomment-294753040)

**Comment by hirurg-lybitel** [comment]
Нужна база склада, чтобы воспроизвести ситуацию

**Comment by yoannawx** [comment]
если у вас нет эталонной розничной базы, то вот запрос, который ВЫПОЛНЯЕТСЯ НА СЕРВЕРЕ, и который вытягивает количество и др для импорта (ИД в запросе и дата уже для твоей базы, чтоб сразу выйти на чек возврата)

SELECT   good.ID AS GoodKey,   good.NAME AS GoodName,   good.ALIAS AS GoodAlias,   good.BARCODE AS GoodBarCode,   goodr.XID AS GoodXID,
goodr.DBID AS GoodDBID,   IIF(ch.USR$CHECKKEY = 147014676, 0, 1) AS CheckType,   CAST((147844802) as INTEGER) as USR$PFD_DEPARTMENTINT,
chl.USR$PRICE AS Price,   chl.USR$PRICESALE AS PriceSale,   chl.USR$DATE,   chl.usr$alias as NewAlias,   chl.USR$BARCODE,   ch.USR$CONCERNEDCHECKKEY,
ch.USR$CONCERNEDCHECKNUMBER,   good.name as pr,   SUM(chl.USR$QUANTITY) AS Quantity
FROM USR$PF_CHECK ch
JOIN USR$PF_CHECKLINE chl ON chl.USR$MASTERKEY = ch.ID
LEFT JOIN GD_GOOD good ON good.ID = chl.USR$GOODKEY
LEFT JOIN GD_RUID goodr ON goodr.ID  = good.ID
LEFT JOIN USR$PF_GETRUID(ch.USR$CARDKEY) cardd ON 1 = 1
LEFT JOIN USR$PF_CHECKLINE cc on cc.USR$MASTERKEY = ch.USR$CONCERNEDCHECKKEY and cc.USR$PRICEINT = chl.USR$PRICEINT
WHERE  ch.USR$PRINT = 1 AND   COALESCE(ch.USR$PFD_DELIVERED, 0) = 0
AND   ch.USR$DATE = '18.04.2017' and   ch.USR$CHECKKEY IN (147014676, 147014678)

GROUP BY 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11 , 12 , 13, 14, 15, 16 ORDER BY 11, 7, 12, 8, 1, 9, 10

**Comment by yoannawx** [comment]
если не помогло - тел. заказчика, где можно подключиться и увидеть обе базы - 8-01641-606-59 . извините, они слишком большие, чтоб забрать по тимвьюверу

**Comment by hirurg-lybitel** [comment]
Нужен склад с оприходаванным товаром.

**Comment by MIchaelShoihet** [comment]
А зачем вообще эта часть запроса LEFT JOIN USR$PF_CHECKLINE cc on cc.USR$MASTERKEY = ch.USR$CONCERNEDCHECKKEY and cc.USR$PRICEINT = chl.USR$PRICEINT? Ведь алиас cc нигде не используется в данном запросе

**Comment by hirurg-lybitel** [comment]
cc.USR$PRICE as pr

**Comment by MIchaelShoihet** [comment]
В запросе я не вижу. Но если это надо, то эту строку надо однозначно выкидывать. Писать процедуру, которая будет искать первое значение из продажи по этому возврату подключать сюда и все. Тут же все прозрачно, зачем столько время тратить ...

**Comment by hirurg-lybitel** [comment]
@yoannawx 

Такая ситуация?

![image](https://cloud.githubusercontent.com/assets/11502258/25138828/404b8564-2464-11e7-908d-e4ad7182fff7.png)

![image](https://cloud.githubusercontent.com/assets/11502258/25138872/57606148-2464-11e7-88f3-6e80c95ae943.png)

![image](https://cloud.githubusercontent.com/assets/11502258/25138905/6883ef08-2464-11e7-8b48-ace9b55ea049.png)

![image](https://cloud.githubusercontent.com/assets/11502258/25138922/78555af2-2464-11e7-9ad4-5521f335c741.png)

**Comment by yoannawx** [comment]
нет, в чеке продажи - все так,  в чеке возврата количество должно быть 1

**Comment by yoannawx** [comment]
при этом в реализацию попадает 2
