### ISSUE TITLE
Скидка исходя из номера товара в чеке

### ISSUE THREAD

**Issue by gsbelarus** [gsbelarus/check-and-cash#9]
На 2-ю позицию, 3-ю позиции и т.д. с настраиваемым процентом.

Учесть, что в акциях типа "второй товар за полцены" продавец потребует чтобы первым шел более дорогой товар, а скидка считалась на более дешевый.

**Comment by MAliaksandr** [comment]
здесь для магазинов с большой пропускной способностью было бы здорово использовать что-то типо автоматической сортировки. Представьте, у покупателя телега с товаром. на каждую 2 скидка. Продавец опухнет отбирать где товар дороже а где дешевле. А с автоматической сортировкой он все отсканировал и на выходе получил то, что надо. Но тут вопрос с грамотностью сортировки. 200тыс и 199тыс 900руб или когда товары одинаковой цены. десять пар носок по 1,5руб
