### ISSUE TITLE
ТСД

### ISSUE THREAD

**Issue by MAliaksandr** [gsbelarus/check-and-cash#90]
У одного нашего клиента есть несколько ТСД(терминал сбора данных) **НЕ INVENTORY**
Он интересуется, можно ли их подружить с нашим складом. Понятно что можно. Интересует конкретика: сроки, условия и т.д.
![0-02-05-77596fd58d46c41e3b452533a1c856b583daed59d64a0728ee18b33c10e12d14_full](https://cloud.githubusercontent.com/assets/11478712/25139237/604401e2-2465-11e7-9004-0ddaf6d95f83.jpg)
![0-02-05-06f364623bf7e64a3d891995320329ab5df2d5d574a7a4236e24426f939a9d48_full](https://cloud.githubusercontent.com/assets/11478712/25139244/65878ee4-2465-11e7-9850-c70bdffe2c3c.jpg)

**Comment by hirurg-lybitel** [comment]
а кто дружил подобные терминалы с нашими складами ранее?

**Comment by alexandra-gsoftware** [comment]
Мне кажется Илона с похожим работала

**Comment by MAliaksandr** [comment]
Думаю, вариантов немного)

**Comment by hirurg-lybitel** [comment]
что по этому вопросу?

**Comment by MAliaksandr** [comment]
Пока стоит колом....

**Comment by hirurg-lybitel** [comment]
Это вообще ещё актуально?

**Comment by MAliaksandr** [comment]
да

**Comment by hirurg-lybitel** [comment]
и кто-то что-то делает?

**Comment by MAliaksandr** [comment]
никто ничего
