### ISSUE TITLE
Номера чеков при синхронизации

### ISSUE THREAD

**Issue by MAliaksandr** [gsbelarus/check-and-cash#91]
При первоначальном внесении данных в кассу с кассового сервера предусмотреть синхронизацию номеров имеющихся чеков в КС. 
Ситуация следующая: заменили кассу на новую. вместе с оборудованием. Начали работать. при синхронизации обнаружили откровенную лажу: в КС чеки апдейтились и к имеющимся суммам добавлялись вновь пробитые позиции и как результат - лажа и в реализации и т.д.

**Comment by hirurg-lybitel** [comment]
Для этого используется макрос **Установить генератор номера чека в заданное значение** в документе **Чеки**

**Comment by MAliaksandr** [comment]
Пусть будет так, тогда нужно в мануале сделать это КРАСНЫМ ЖИРНЫМ ШРИФТОМ пометку для установки кассы.
