### ISSUE TITLE
Проблема взаимосвязи ФР, Cash и банковского терминала

### ISSUE THREAD

**Issue by supportkkc** [gsbelarus/check-and-cash#97]
PositiveCash стоит работа с БТ.  При расчете банковской картой часто не выходит фискальный чек. Продажа не закрывается. В конце 4-го месяца (27-30 числа) после Z отчета не выходили отчеты по карте.

**Comment by supportkkc** [comment]
В магазине 2 кассы. Проблема наблюдается на обеих. Ссылка на базы касс и сервера https://yadi.sk/d/FWT6_v3a3JDfKk

**Comment by stasgm** [comment]
@supportkkc название клиентов и ссылки на базы сюда не кидайте, т.к. это публичный репозиторий.

**Comment by supportkkc** [comment]
@stasgm Есть информация?

**Comment by hirurg-lybitel** [comment]
@stasgm а какой информации вы от нас ждёте?
у нас ни банковского терминала, ни логов (в весрии программмы у клиента отсутсвует логирование банковских операций)

**Comment by supportkkc** [comment]
Давайте тогда дальше молчать, БД были отправлены Вам. Вы молчите. Если Вам что-то надо, можно написать сюда, какие операции произвести на объекте, что еще нужно для решения вопросов.

**Comment by hirurg-lybitel** [comment]
Как посмотрели, так и ответили.

Нужны, как минимум, логи банковского терминала, проблемные даты.
Также банковский терминал и обновить ПО у клиента для появления механизма логирования операций связанных с банковским терминалом.

**Comment by supportkkc** [comment]
Обновлены ПИ на кассах и сервере установлен лог спаркдрайвер

**Comment by hirurg-lybitel** [comment]
Ок. Ждём.
